# -*- coding: utf-8 -*-
"""Section checks: ownership, land use, valuation, financing.

Two short questions after each section of reading, testing that section only.
"""

def Q(stem, choices, answer, why):
    return {"q": stem, "choices": choices, "answer": answer, "why": why}

CHECKS = {
"national/ownership": {
 "The bundle of rights": [
  Q("Which right lets an owner keep other people off the land?",
    ["Exclude", "Dispose", "Encumber"], 0,
    "Exclude is the right to keep others out. Dispose is the right to sell or will it."),
  Q("An owner sells the mineral rights but keeps the surface. This is possible because:",
    ["The bundle's rights can be separated and sold individually",
     "Mineral rights were never part of ownership",
     "Only fee simple defeasible allows it"], 0,
    "The sticks in the bundle can be split off and conveyed on their own."),
 ],
 "Freehold estates: ownership without a fixed end": [
  Q("'To the city so long as it is used as a park' creates a:",
    ["Fee simple determinable", "Fee on condition subsequent", "Life estate"], 0,
    "Durational words - so long as, while, until - create a determinable fee that ends automatically."),
  Q("A life estate measured by someone else's life is:",
    ["Pur autre vie", "A reversion", "A remainder"], 0,
    "Pur autre vie means 'for another's life'."),
 ],
 "Leasehold estates: possession with an end date": [
  Q("A 60-day lease with fixed start and end dates is an:",
    ["Estate for years", "Periodic estate", "Estate at will"], 0,
    "Fixed start and end makes it an estate for years, regardless of length."),
  Q("A tenant who stays after the lease ends without permission holds an:",
    ["Estate at sufferance", "Estate at will", "Periodic estate"], 0,
    "Sufferance: possession with no right, but entry was originally lawful."),
 ],
 "Co-ownership": [
  Q("Which form has NO right of survivorship?",
    ["Tenancy in common", "Joint tenancy", "Tenancy by the entirety"], 0,
    "Tenancy in common shares pass by will or inheritance."),
  Q("One joint tenant sells her share to a stranger. The buyer becomes a:",
    ["Tenant in common", "Joint tenant", "Life tenant"], 0,
    "Selling severs the unities as to that share; the buyer takes as a tenant in common."),
 ],
 "Condominiums, cooperatives, and timeshares": [
  Q("A cooperative resident owns:",
    ["Shares of stock plus a proprietary lease", "The unit in fee simple",
     "An undivided share of the land"], 0,
    "A co-op owner holds personal property - stock - not real property."),
  Q("A condo owner's percentage of the common elements mainly determines:",
    ["Assessments and usually voting weight", "The unit's square footage",
     "The property tax rate"], 0,
    "The percentage set in the declaration drives assessments and voting."),
 ],
 "Fixtures": [
  Q("Which test carries the most weight in deciding whether something is a fixture?",
    ["Intent", "Method of annexation", "Cost of the item"], 0,
    "MAI: method, adaptation, intent - and intent weighs heaviest."),
  Q("A restaurant tenant's bolted-down pizza oven is:",
    ["A trade fixture the tenant may remove", "A fixture that stays with the building",
     "An emblement"], 0,
    "Commercial tenants' business equipment stays their personal property."),
 ],
 "Encumbrances: other people's claims on your land": [
  Q("The parcel that BENEFITS from an easement appurtenant is the:",
    ["Dominant tenement", "Servient tenement", "Licensed parcel"], 0,
    "Dominant benefits; servient is burdened."),
  Q("A utility company's right to run a line across land is an:",
    ["Easement in gross", "Easement appurtenant", "Encroachment"], 0,
    "It benefits a company, not a parcel, so there is no dominant tenement."),
 ],
 "Water and air rights": [
  Q("Rights along a flowing river are:",
    ["Riparian", "Littoral", "Prior appropriation"], 0,
    "Riparian = flowing water. Littoral = still water."),
  Q("Rights along a lake are:",
    ["Littoral", "Riparian", "Percolating"], 0,
    "Littoral attaches to static bodies: lakes, seas, ponds."),
 ],
},

"national/landuse": {
 "The four public powers (PETE)": [
  Q("Which power requires the government to pay just compensation?",
    ["Eminent domain", "Police power", "Escheat"], 0,
    "Only eminent domain takes and must pay. Police power regulates for free."),
  Q("Property passing to the state when someone dies with no will and no heirs is:",
    ["Escheat", "Eminent domain", "Condemnation"], 0,
    "Escheat prevents land from being ownerless."),
 ],
 "Zoning and relief from it": [
  Q("An owner needs relief from a setback requirement. They seek a:",
    ["Variance", "Special use permit", "Rezoning"], 0,
    "A variance addresses a dimensional hardship."),
  Q("A store that predates new residential zoning may continue as a:",
    ["Nonconforming use", "Variance", "Spot zoning"], 0,
    "A lawful pre-existing use is grandfathered."),
 ],
 "When regulation becomes a taking": [
  Q("A regulation becomes a taking when it:",
    ["Denies all economically viable use", "Reduces value by more than a third",
     "Changes the zoning classification"], 0,
    "Loss of value alone, even large, is not a taking."),
  Q("An owner suing on the ground that a regulation went too far brings an action in:",
    ["Inverse condemnation", "Escheat", "Quiet title"], 0,
    "Inverse condemnation claims a regulatory taking."),
 ],
 "Private controls": [
  Q("Recorded subdivision covenants are enforced by:",
    ["Any benefited lot owner or the HOA", "The zoning board", "The state commission"], 0,
    "CC&Rs are private; government does not enforce them."),
  Q("Where a covenant and zoning conflict, which controls?",
    ["The more restrictive one", "Zoning always", "The covenant always"], 0,
    "The more restrictive requirement governs."),
 ],
 "Codes, permits, and environmental review": [
  Q("The document confirming a building may lawfully be occupied is the:",
    ["Certificate of occupancy", "Building permit", "Variance"], 0,
    "The permit starts the work; the certificate of occupancy ends it."),
  Q("An Environmental Impact Statement is required for:",
    ["Major federal actions significantly affecting the environment",
     "Every subdivision", "Any home resale"], 0,
    "NEPA applies to major FEDERAL actions."),
 ],
},

"national/valuation": {
 "Value, price, and cost are three different things": [
  Q("What a property actually sold for is its:",
    ["Market price", "Market value", "Assessed value"], 0,
    "Price is the historical fact; value is an opinion."),
  Q("Insurable value covers:",
    ["The improvements only", "Land and improvements", "The assessed amount"], 0,
    "Land does not burn, so it is excluded."),
 ],
 "The four characteristics of value (DUST)": [
  Q("DUST stands for demand, utility, scarcity and:",
    ["Transferability", "Taxation", "Title"], 0,
    "Transferability - title must be conveyable."),
  Q("A property nobody can legally convey lacks:",
    ["Transferability", "Utility", "Scarcity"], 0,
    "Without transferability there is no market value."),
 ],
 "Appraisal principles": [
  Q("A modest house among mansions gains value. This is:",
    ["Progression", "Regression", "Conformity"], 0,
    "Progression pulls the lesser property up."),
  Q("Combining two lots so the whole exceeds the parts creates:",
    ["Plottage", "Assemblage", "Contribution"], 0,
    "Assemblage is the act; plottage is the added value."),
 ],
 "The three approaches": [
  Q("Valuing a 40-year-old church relies most on the:",
    ["Cost approach", "Income approach", "Sales comparison approach"], 0,
    "Special-purpose property rarely sells and earns no rent."),
  Q("A comparable is INFERIOR to the subject. You:",
    ["Add to the comparable", "Subtract from the comparable",
     "Adjust the subject"], 0,
    "CIA - Comp Inferior, Add. Never adjust the subject."),
 ],
 "Building NOI correctly": [
  Q("Which is NEVER an operating expense?",
    ["Debt service", "Property taxes", "Management fees"], 0,
    "Debt service comes out after NOI, not before."),
  Q("Effective gross income is potential gross income less:",
    ["Vacancy and collection loss", "Operating expenses", "Debt service"], 0,
    "Vacancy first, then expenses give NOI."),
 ],
 "Depreciation: three kinds": [
  Q("A new highway beside the house causes:",
    ["External obsolescence", "Functional obsolescence", "Physical deterioration"], 0,
    "The cause is outside the property line, so it is external and incurable."),
  Q("Curable vs. incurable is decided by:",
    ["Whether the cost is recovered in added value", "Whether it can physically be fixed",
     "The age of the building"], 0,
    "It is an economic test, not a physical one."),
 ],
 "CMA vs. appraisal vs. BPO": [
  Q("A broker's CMA is:",
    ["A pricing opinion, not an appraisal", "An appraisal requiring a licence",
     "A statement of assessed value"], 0,
    "It must never be presented as an appraisal."),
  Q("Who may perform an appraisal?",
    ["A licensed or certified appraiser", "Any licensed broker", "The county assessor"], 0,
    "Appraisals require appraiser credentials."),
 ],
 "The appraisal process ends in reconciliation": [
  Q("In reconciliation the appraiser:",
    ["Weights the approaches by reliability", "Averages the three values",
     "Uses only the highest"], 0,
    "Averaging is always wrong."),
  Q("Reconciliation produces:",
    ["A single value conclusion", "Three separate opinions", "A range with no conclusion"], 0,
    "One conclusion, weighted by reliability."),
 ],
},

"national/financing": {
 "The two documents": [
  Q("Which document is the borrower's promise to repay?",
    ["The promissory note", "The security deed", "The deed of trust"], 0,
    "The note is the debt; the security instrument pledges the collateral."),
  Q("Georgia's security instrument is a:",
    ["Security deed", "Mortgage", "Deed of trust"], 0,
    "A security deed passes legal title to the lender until payoff."),
 ],
 "Clauses you must recognise": [
  Q("Which clause is triggered by a TRANSFER rather than a default?",
    ["Alienation", "Acceleration", "Defeasance"], 0,
    "Alienation is the due-on-sale clause."),
  Q("The clause requiring the lender to release the lien on payoff is:",
    ["Defeasance", "Subordination", "Acceleration"], 0,
    "Defeasance defeats the lien when the debt is paid."),
 ],
 "Taking over an existing loan": [
  Q("Which arrangement leaves the buyer with NO personal liability?",
    ["Taking title subject to the loan", "Assumption", "Novation"], 0,
    "'Subject to' means the buyer risks only the property."),
  Q("What releases the original borrower from liability?",
    ["Novation", "Assumption", "Acceleration"], 0,
    "Only a novation substitutes the party and releases the original."),
 ],
 "Amortization": [
  Q("A loan with level payments that leaves a balloon is:",
    ["Partially amortized", "Fully amortized", "A term loan"], 0,
    "Fully amortized retires the debt by maturity; a term loan is interest only."),
  Q("In an amortized loan, over time the interest portion of each payment:",
    ["Shrinks", "Grows", "Stays the same"], 0,
    "As principal is repaid, interest on the balance falls."),
 ],
 "Points, yield, and LTV": [
  Q("One discount point equals 1% of the:",
    ["Loan amount", "Sale price", "Appraised value"], 0,
    "Always the loan. This is the most common math error."),
  Q("LTV is based on:",
    ["The lesser of price and appraised value", "The sale price always",
     "The appraised value always"], 0,
    "Lenders lend on the lower figure."),
 ],
 "Loan programmes": [
  Q("PMI protects:",
    ["The lender", "The borrower", "The seller"], 0,
    "Private mortgage insurance covers the lender's risk above 80% LTV."),
  Q("An ARM's interest rate equals:",
    ["Index plus margin", "Index minus margin", "The cap rate"], 0,
    "The margin is the lender's constant markup; the index moves."),
 ],
 "The markets": [
  Q("The secondary mortgage market:",
    ["Buys existing loans from lenders", "Originates loans to consumers",
     "Sets federal interest rates"], 0,
    "It provides liquidity so lenders can lend again."),
  Q("A consumer applying for a mortgage deals with the:",
    ["Primary market", "Secondary market", "Federal Reserve"], 0,
    "Consumers never deal with the secondary market directly."),
 ],
 "Consumer protection law": [
  Q("The Closing Disclosure must be received:",
    ["3 business days before consummation", "3 business days after application",
     "At the closing table"], 0,
    "The Loan Estimate is the one tied to application."),
  Q("RESPA Section 8 prohibits:",
    ["Payment for the mere referral of settlement business",
     "Charging an origination fee", "Requiring a survey"], 0,
    "Fees for services actually performed are fine."),
 ],
},
}
