# -*- coding: utf-8 -*-
"""Section checks: agency, disclosures, contracts, transfer, practice, math."""

def Q(stem, choices, answer, why):
    return {"q": stem, "choices": choices, "answer": answer, "why": why}

CHECKS = {
"national/agency": {
 "The six duties (OLD CAR)": [
  Q("Which duties SURVIVE the end of the agency?",
    ["Confidentiality and accounting", "Loyalty and obedience", "Disclosure and care"], 0,
    "The other four end with the relationship."),
  Q("The duty of obedience covers:",
    ["Lawful instructions only", "All client instructions", "Instructions in writing only"], 0,
    "An unlawful instruction must be refused."),
 ],
 "How agency is created and ended": [
  Q("Agency created by conduct rather than agreement is:",
    ["Implied agency", "Express agency", "Ratification"], 0,
    "This is the accidental-agency trap."),
  Q("Which does NOT terminate an agency?",
    ["The client refusing an offer", "Death of the principal",
     "Destruction of the property"], 0,
    "Refusing an offer is just the client exercising judgement."),
 ],
 "Scope of authority": [
  Q("A listing broker is usually a:",
    ["Special agent", "General agent", "Universal agent"], 0,
    "Narrow authority for one transaction."),
  Q("A property manager is usually a:",
    ["General agent", "Special agent", "Subagent"], 0,
    "Ongoing authority across a range of matters."),
 ],
 "Who is who": [
  Q("A customer is owed:",
    ["Honesty and disclosure of known material defects", "Full fiduciary duties",
     "Confidentiality"], 0,
    "Advocacy and advice belong to clients."),
  Q("A subagent owes fiduciary duties to:",
    ["The seller", "The buyer", "Both equally"], 0,
    "A subagent works through the listing broker."),
 ],
 "Where licensees get into trouble": [
  Q("Mixing client funds with the broker's own money is:",
    ["Commingling", "Conversion", "Novation"], 0,
    "Spending them is conversion - worse."),
  Q("'The best view in town' is:",
    ["Puffing", "Misrepresentation", "Fraud"], 0,
    "Exaggerated opinion is puffing; a false statement of fact is not."),
 ],
 "When commission is earned": [
  Q("Commission is classically earned when the broker produces a buyer who is:",
    ["Ready, willing and able on the seller's terms", "Pre-approved by any lender",
     "Merely interested"], 0,
    "Under most listings it is earned then, even if the seller refuses to close."),
  Q("A dispute between two brokers over procuring cause is decided by:",
    ["Arbitration or the courts", "The licensing commission", "The MLS board"], 0,
    "Commissions are not a licence-law matter."),
 ],
},

"national/disclosures": {
 "Material facts and defects": [
  Q("A hidden defect not discoverable by ordinary inspection is:",
    ["Latent", "Patent", "Stigmatic"], 0,
    "Known latent defects must be disclosed."),
  Q("A basement leak repaired two years ago is:",
    ["Still material and must be disclosed", "No longer material once repaired",
     "Disclosable only if asked"], 0,
    "History bears on recurrence and insurability."),
 ],
 "What must NOT be disclosed": [
  Q("A buyer asks whether a former occupant had AIDS. You:",
    ["Decline - handicap is a protected class", "Answer truthfully",
     "Answer only in writing"], 0,
    "Disclosing it would itself be discriminatory."),
  Q("A buyer asks about the racial makeup of a neighbourhood. You should:",
    ["Decline and refer them to public data", "Describe it accurately",
     "Give your impression"], 0,
    "Answering steers, however well intentioned."),
 ],
 "Stigmatized property": [
  Q("Stigma arises from:",
    ["Events rather than physical condition", "Structural defects",
     "Environmental hazards"], 0,
    "A death, crime, or rumour - not condition."),
  Q("Georgia's protection covers:",
    ["Not volunteering the information", "Denying it if asked", "Both"], 0,
    "Nondisclosure is protected; an affirmative lie is not."),
 ],
 "Lead-based paint (federal, applies everywhere)": [
  Q("The lead rule applies to housing built before:",
    ["1978", "1988", "1968"], 0,
    "Pre-1978 target housing."),
  Q("The seller must:",
    ["Disclose known hazards and allow a 10-day test window", "Test the property",
     "Remove any lead paint"], 0,
    "Sellers are never required to test."),
 ],
 "Environmental hazards": [
  Q("Asbestos is most dangerous when it is:",
    ["Friable", "Painted", "Encapsulated"], 0,
    "Friable means it crumbles and releases fibres."),
  Q("CERCLA liability is:",
    ["Strict, joint and several, and retroactive", "Limited to the polluter",
     "Limited to commercial owners"], 0,
    "An innocent current owner can be liable."),
 ],
 "Timing": [
  Q("Seller disclosure should reach the buyer:",
    ["Before or at the time of the offer", "At closing", "After inspection"], 0,
    "Late delivery usually gives a right to rescind."),
  Q("A Phase I environmental assessment involves:",
    ["Records, interviews and a site visit", "Soil sampling", "Remediation"], 0,
    "Sampling is Phase II, and only if Phase I finds a concern."),
 ],
},

"national/contracts": {
 "The four essentials": [
  Q("Which is NOT required for a valid contract?",
    ["Earnest money", "Consideration", "Lawful object"], 0,
    "A promise for a promise is consideration enough."),
  Q("The Statute of Frauds requires a real estate contract to be:",
    ["In writing and signed by the party to be charged", "Notarised", "Recorded"], 0,
    "Writing and signature - not notarisation."),
 ],
 "Valid, void, voidable, unenforceable": [
  Q("A minor's contract is:",
    ["Voidable by the minor", "Void", "Voidable by the adult"], 0,
    "The adult party remains bound."),
  Q("A contract for an illegal purpose is:",
    ["Void", "Voidable", "Unenforceable"], 0,
    "It was never a contract at all."),
 ],
 "Offer and acceptance": [
  Q("Acceptance is effective when:",
    ["Communicated to the offeror", "Signed by the offeree", "Notarised"], 0,
    "Signing alone is not acceptance."),
  Q("Changing one term in an offer creates a:",
    ["Counteroffer", "Conditional acceptance", "Valid contract"], 0,
    "A counteroffer rejects and replaces the original."),
 ],
 "Contract classifications": [
  Q("An option is the classic example of a:",
    ["Unilateral contract", "Bilateral contract", "Executed contract"], 0,
    "The optionee need not buy; the optionor must sell if they do."),
  Q("A contract signed but not yet closed is:",
    ["Executory", "Executed", "Void"], 0,
    "Executed means fully performed."),
 ],
 "Contingencies": [
  Q("A contingency for financing at no more than 6.5% is satisfied by approval at 6.75%?",
    ["No", "Yes, it is close enough", "Only with seller consent"], 0,
    "Courts enforce the number the parties wrote."),
  Q("A contingency is a:",
    ["Condition precedent", "Condition subsequent", "Covenant"], 0,
    "The duty to perform does not arise until it is met or waived."),
 ],
 "Breach and remedies": [
  Q("A court ordering the actual transfer of the property is:",
    ["Specific performance", "Rescission", "Reformation"], 0,
    "Available because land is legally unique."),
  Q("Correcting a wrong parcel number both parties agree was a typo is:",
    ["Reformation", "Rescission", "Novation"], 0,
    "The court rewrites the document to match true intent."),
 ],
 "Assignment and novation": [
  Q("After assigning a purchase contract, the original buyer is:",
    ["Secondarily liable", "Fully released", "Primarily liable"], 0,
    "Only a novation releases them."),
  Q("Real estate purchase contracts are:",
    ["Assignable unless they say otherwise", "Never assignable",
     "Assignable only with seller consent"], 0,
    "Silence means assignable."),
 ],
 "Special contract forms": [
  Q("In a land contract the seller keeps:",
    ["Legal title", "Possession", "Equitable title"], 0,
    "The buyer takes possession and equitable title."),
  Q("A right of first refusal:",
    ["Lets you match an offer the owner receives", "Sets a price and forces a sale",
     "Is the same as an option"], 0,
    "It is weaker than an option - no fixed price, no forced sale."),
 ],
 "Time and risk": [
  Q("Without a 'time is of the essence' clause, courts allow:",
    ["Performance within a reasonable time", "No delay at all",
     "A 30-day extension automatically"], 0,
    "The clause is what makes dates strict."),
  Q("Under the Uniform Vendor and Purchaser Risk Act, risk of loss before closing is on the:",
    ["Seller", "Buyer", "Insurer"], 0,
    "The older doctrine of equitable conversion put it on the buyer."),
 ],
},

"national/transfer": {
 "Requirements for a valid deed": [
  Q("Title actually passes on:",
    ["Delivery and acceptance", "Recording", "Notarisation"], 0,
    "Recording gives notice; it does not pass title."),
  Q("Who signs the deed?",
    ["The grantor only", "Both grantor and grantee", "The grantee only"], 0,
    "The grantee never signs."),
 ],
 "Types of deed, strongest to weakest": [
  Q("Which deed offers the grantee the most protection?",
    ["General warranty", "Special warranty", "Quitclaim"], 0,
    "It warrants against defects through the entire chain."),
  Q("A quitclaim deed is most often used to:",
    ["Clear a cloud on title", "Convey a new home", "Transfer a mortgage"], 0,
    "It releases whatever interest the grantor may have."),
 ],
 "The covenants of title": [
  Q("The covenant of seisin is breached, if at all:",
    ["At delivery", "On a later eviction", "When the grantee resells"], 0,
    "It is a PRESENT covenant, so the clock starts at delivery."),
  Q("Quiet enjoyment is a:",
    ["Future covenant", "Present covenant", "Statutory warranty"], 0,
    "Future covenants are breached only on later disturbance."),
 ],
 "Recording, notice, and priority": [
  Q("Recording gives:",
    ["Constructive notice to the world", "Actual notice to the grantee",
     "A guarantee of clear title"], 0,
    "Everyone is charged with knowledge whether they looked or not."),
  Q("Under a race-notice statute a later buyer wins only if they:",
    ["Took without notice AND recorded first", "Recorded first", "Took without notice"], 0,
    "Both conditions are required."),
 ],
 "Title evidence": [
  Q("A Schedule B exception in a title commitment is:",
    ["Something the policy will NOT cover", "An extra covered item",
     "A recording fee"], 0,
    "The word means the opposite of what it sounds like."),
  Q("Title insurance protects against:",
    ["Defects that already existed when issued", "Future fire loss",
     "Declines in market value"], 0,
    "It is retrospective, paid once."),
 ],
 "Involuntary and non-sale transfers": [
  Q("Georgia's adverse possession period under colour of title is:",
    ["7 years", "20 years", "10 years"], 0,
    "20 years without colour of title."),
  Q("Sudden loss or addition of land that does NOT move boundaries is:",
    ["Avulsion", "Accretion", "Erosion"], 0,
    "Gradual change moves boundaries; sudden change does not."),
 ],
 "Legal descriptions": [
  Q("Which system is most common in Georgia subdivisions?",
    ["Lot and block", "Rectangular survey", "Metes and bounds"], 0,
    "Georgia does not use the rectangular survey system."),
  Q("A metes and bounds description must:",
    ["Return to the point of beginning", "Reference a section number",
     "Include the acreage"], 0,
    "It must close."),
 ],
},

"national/practice": {
 "Federal fair housing": [
  Q("Which is NOT one of the seven federal protected classes?",
    ["Source of income", "Familial status", "Handicap"], 0,
    "Some states and cities protect it, but not federal housing law."),
  Q("Familial status protects:",
    ["Households with children under 18", "Married couples only",
     "Anyone over 55"], 0,
    "Also pregnant people and those securing custody."),
 ],
 "The named violations": [
  Q("Telling owners a protected group is moving in to induce sales is:",
    ["Blockbusting", "Steering", "Redlining"], 0,
    "Illegal whether or not the claim is true."),
  Q("A neutral policy that falls hardest on a protected class may be:",
    ["Disparate impact", "Puffing", "Lawful in all cases"], 0,
    "Intent is not required for a violation."),
 ],
 "Enforcement": [
  Q("Federal fair housing complaints go to:",
    ["HUD", "The state licensing commission only", "The MLS"], 0,
    "The commission can also discipline the licence separately."),
  Q("A HUD complaint is generally filed within:",
    ["One year", "30 days", "Five years"], 0,
    "One year of the discriminatory act."),
 ],
 "Antitrust": [
  Q("Two competing brokerages agreeing on a commission rate is:",
    ["Price fixing, a per se violation", "Lawful if disclosed",
     "Lawful if the MLS approves"], 0,
    "No defence and no disclosure cure."),
  Q("A single firm setting its own minimum rate is:",
    ["Lawful company policy", "Price fixing", "A group boycott"], 0,
    "Antitrust requires an agreement between competitors."),
 ],
 "Listings and agreements": [
  Q("Under which listing is the broker paid no matter who sells?",
    ["Exclusive right to sell", "Exclusive agency", "Open"], 0,
    "Exclusive agency lets the seller sell it themselves commission-free."),
  Q("A net listing is one where the broker:",
    ["Keeps everything above the seller's stated price", "Charges a flat fee",
     "Splits with the buyer's broker"], 0,
    "Heavily restricted; Georgia allows it only under strict disclosure."),
 ],
 "Trust funds": [
  Q("When buyer and seller both demand a disputed deposit, the broker should:",
    ["Hold the funds and use interpleader", "Release to whoever asked first",
     "Split it evenly"], 0,
    "Picking a side invites a conversion claim."),
  Q("Client funds belong in:",
    ["A separate trust or escrow account", "The brokerage operating account",
     "The agent's account"], 0,
    "Mixing is commingling."),
 ],
 "Advertising, licensing, supervision": [
  Q("An unlicensed assistant may NOT:",
    ["Discuss price or terms with a buyer", "Schedule appointments",
     "Prepare marketing for broker approval"], 0,
    "Anything involving negotiation or advice requires a licence."),
  Q("Under the do-not-call rules a licensee may call a registered number if:",
    ["There is an established business relationship or written consent",
     "The call is before 9pm", "They identify themselves"], 0,
    "FSBO and expired-listing calls are a common violation source."),
 ],
},

"national/math": {
 "Conversions to memorise": [
  Q("One acre equals:", ["43,560 sq ft", "5,280 sq ft", "640 sq ft"], 0,
    "A mile is 5,280 FEET; a section is 640 ACRES."),
  Q("One section equals:", ["640 acres", "36 acres", "43,560 acres"], 0,
    "One square mile. A township is 36 sections."),
 ],
 "Commission": [
  Q("Commission is a percentage of the:",
    ["Sale price", "Loan amount", "Appraised value"], 0,
    "Points are on the loan; commission is on the price."),
  Q("$300,000 sale at 6%, split 50/50 between two brokerages. Each brokerage gets:",
    ["$9,000", "$18,000", "$4,500"], 0,
    "$18,000 total, halved."),
 ],
 "Percentage of loan vs. percentage of price": [
  Q("Discount points are a percentage of the:",
    ["Loan", "Sale price", "Down payment"], 0,
    "The single most common math error on the exam."),
  Q("Georgia transfer tax is a percentage of the:",
    ["Sale price", "Loan", "Assessed value"], 0,
    "$1.00 per $1,000 of consideration."),
 ],
 "Net to seller - divide, never add": [
  Q("To find the price giving a target net after commission, you:",
    ["Divide by (100% - commission%)", "Add the commission percentage",
     "Multiply by the commission rate"], 0,
    "Adding always understates the price."),
  Q("Seller wants $190,000 net with a 5% commission. Price is:",
    ["$200,000", "$199,500", "$180,500"], 0,
    "$190,000 / 0.95. Adding 5% gives $199,500 - the trap."),
 ],
 "Prorations": [
  Q("Unpaid taxes at closing produce a:",
    ["Seller debit and buyer credit", "Seller credit and buyer debit",
     "Debit to both"], 0,
    "The buyer will pay the whole bill later."),
  Q("The seller owns the property through:",
    ["The day before closing", "Closing day", "The day after closing"], 0,
    "The buyer owns closing day forward."),
 ],
 "Interest": [
  Q("One month's interest equals:",
    ["Principal x annual rate / 12", "Principal x annual rate",
     "Principal / rate x 12"], 0,
    "Use the current balance."),
  Q("$200,000 at 6% - one month's interest is:",
    ["$1,000", "$12,000", "$500"], 0,
    "$12,000 / 12."),
 ],
 "Appreciation and depreciation": [
  Q("Compound appreciation applies the rate to:",
    ["The new value each year", "The original value each year",
     "The average value"], 0,
    "Multiply by (1 + rate) once per year."),
  Q("Straight-line depreciation takes:",
    ["The same dollar amount off each year", "A shrinking amount each year",
     "A growing amount each year"], 0,
    "Basis divided by useful life."),
 ],
 "Qualifying ratios": [
  Q("The front-end ratio compares housing expense to:",
    ["Gross monthly income", "Net monthly income", "Annual income"], 0,
    "Convert annual to monthly first."),
  Q("The back-end ratio adds:",
    ["All recurring monthly debt", "Only the mortgage", "Utilities"], 0,
    "Car loans, student loans, credit cards."),
 ],
},
}
