# -*- coding: utf-8 -*-
"""Section checks: the Georgia portion and the comprehensive subtest."""

def Q(stem, choices, answer, why):
    return {"q": stem, "choices": choices, "answer": answer, "why": why}

CHECKS = {
"georgia/license-law": {
 "Getting licensed": [
  Q("The Georgia salesperson prelicense course is:",
    ["75 hours", "25 hours", "60 hours"], 0,
    "60 hours is the broker course; 25 is postlicense."),
  Q("Experience required for a salesperson licence:",
    ["None", "One year", "Three of the past five years"], 0,
    "The three-of-five rule is for broker and associate broker."),
 ],
 "Keeping it: the education ladder": [
  Q("The 25-hour postlicense course is due within:",
    ["One year of original licensure", "Four years", "Two years"], 0,
    "Miss it and the licence lapses. CE does not substitute."),
  Q("Georgia continuing education is:",
    ["24 hours per four-year renewal period", "36 hours per four years",
     "24 hours per year"], 0,
    "Many national guides quote 36 - that is a different state."),
 ],
 "Status and administration": [
  Q("An inactive Georgia licensee:",
    ["Still owes the postlicense requirement", "Has no education obligations",
     "May still list property"], 0,
    "Fees and postlicense still apply; licensed activity does not."),
  Q("A Georgia salesperson may be paid by:",
    ["Their affiliated broker only", "Any party to the transaction",
     "The closing attorney"], 0,
    "Direct payment from a client is a violation."),
 ],
 "The qualifying broker and the firm": [
  Q("Failure to supervise an affiliate is:",
    ["An independent violation by the broker", "Only the affiliate's problem",
     "Excused if no consumer complains"], 0,
    "GREC can act on its own motion."),
  Q("Georgia advertising must:",
    ["Identify the brokerage firm", "Use only the licensee's name",
     "Be pre-approved by GREC"], 0,
    "A licensee may never appear to operate independently."),
 ],
 "What GREC can do - and what it cannot": [
  Q("GREC can do all of these EXCEPT:",
    ["Order a licensee to repay a consumer's loss", "Revoke a licence",
     "Impose a fine"], 0,
    "There is no restitution power - the consumer must sue."),
  Q("GREC members are:",
    ["Appointed by the Governor", "Elected by licensees",
     "Chosen by the REALTOR association"], 0,
    "Gubernatorial appointment."),
 ],
 "The disciplinary process": [
  Q("A GREC investigation may be started by:",
    ["Anyone by sworn written request, or the Commission itself",
     "Only a party to the transaction", "Only the Attorney General"], 0,
    "It can also act on its own motion."),
  Q("After an ALJ decision, the respondent has how long to seek Commission review?",
    ["30 days", "10 days", "90 days"], 0,
    "Otherwise the decision becomes final."),
 ],
 "A licensee is never an ordinary owner": [
  Q("A licensee selling their own home must:",
    ["Disclose licensed status in writing", "Do nothing special",
     "Use another broker"], 0,
    "O.C.G.A. 43-40-29(c) removes the ordinary-owner exemptions."),
  Q("Net listings in Georgia are:",
    ["Permitted only under strict disclosure", "Always illegal",
     "The standard form"], 0,
    "They create a direct conflict with the client's interest."),
 ],
},

"georgia/brreta": {
 "The core definitions": [
  Q("Under BRRETA, agency requires:",
    ["Written authority", "A verbal agreement", "Payment of a commission"], 0,
    "The brokerage engagement is a written contract."),
  Q("A person NOT represented, for whom you may perform ministerial acts, is a:",
    ["Customer", "Client", "Principal"], 0,
    "Ministerial acts require no discretion."),
 ],
 "The point that changes everything": [
  Q("Under BRRETA a Georgia broker is:",
    ["Not deemed a fiduciary", "A fiduciary in all cases",
     "A fiduciary only to sellers"], 0,
    "The broker owes reasonable care in the duties the statute and engagement specify."),
  Q("A broker's duties may be expanded beyond the statute only by:",
    ["An express signed writing", "A verbal promise", "Custom in the market"], 0,
    "10-6A-4(a)."),
 ],
 "Compensation does not create agency": [
  Q("A seller pays the buyer's broker. That broker represents:",
    ["The buyer only", "The seller", "Both"], 0,
    "Compensation and agency are independent under BRRETA."),
  Q("What creates the engagement?",
    ["An express written agreement", "Showing property", "Paying a fee"], 0,
    "Only the writing."),
 ],
 "Disclosures before or within the engagement": [
  Q("Which need NOT be disclosed before an engagement?",
    ["That the broker represents other buyers generally",
     "The broker's compensation and sharing", "Confidentiality obligations"], 0,
    "The statute expressly excludes it."),
  Q("How many pre-engagement disclosures does BRRETA list?",
    ["Four", "Two", "Six"], 0,
    "Agency types, conflicts known, compensation, confidentiality."),
 ],
 "Duration and termination": [
  Q("A Georgia brokerage engagement must have:",
    ["A definite expiration date", "An automatic renewal",
     "A minimum six-month term"], 0,
    "Automatic renewals are prohibited."),
  Q("An engagement with no end date is:",
    ["A licence-law violation", "Valid indefinitely", "Limited to one year"], 0,
    "Disciplinary matter for the broker."),
 ],
 "Dual agency": [
  Q("Dual agency in Georgia is:",
    ["Allowed with written consent", "Prohibited", "Allowed with verbal consent"], 0,
    "Consent is presumed if the writing contains the required elements."),
  Q("A dual agent must disclose:",
    ["Adverse material facts actually known", "The client's bottom line",
     "Everything either client says"], 0,
    "Never information a client asked be kept confidential."),
 ],
 "Designated agency - a genuine Georgia distinction": [
  Q("With designated agents appointed, the broker is:",
    ["Expressly NOT a dual agent", "Automatically a dual agent",
     "Required to withdraw"], 0,
    "O.C.G.A. 10-6A-13(b) says neither the broker, the licensees, nor the firm."),
  Q("A designated agent may share confidential client information with:",
    ["Their broker only", "The other designated agent", "Anyone in the firm"], 0,
    "And the broker may not reveal it either."),
 ],
},

"georgia/trust-accounts": {
 "Why the account exists": [
  Q("Funds in a properly maintained trust account, on the broker's death:",
    ["Do not become part of the estate", "Pass to the heirs",
     "Go to the broker's creditors"], 0,
    "They are also protected from garnishment and bankruptcy."),
  Q("The account's purpose is to:",
    ["Keep the public's money separate from the broker's",
     "Earn interest for the broker", "Simplify tax filing"], 0,
    "Separation is the whole point."),
 ],
 "Setting it up": [
  Q("A Georgia trust account should be opened under:",
    ["An EIN", "The broker's Social Security Number", "A client's tax ID"], 0,
    "SSN-based accounts have been seized for the broker's personal debts."),
  Q("The account must be designated as trust or escrow by:",
    ["The bank", "The broker", "GREC"], 0,
    "And registered with the Commission."),
 ],
 "Prompt deposit": [
  Q("To hold an earnest money check until acceptance, the broker needs:",
    ["Written authority from all parties", "The buyer's verbal request",
     "Nothing - it is standard"], 0,
    "The seller has an interest in the deposit too."),
  Q("Trust funds are deposited by default into:",
    ["A non-interest-bearing account", "An interest-bearing account",
     "The operating account"], 0,
    "Interest-bearing requires written authorisation."),
 ],
 "What counts as trust money": [
  Q("Which is NOT trust money?",
    ["Commission properly earned and disbursed after closing",
     "A tenant's security deposit", "Rent collected for an owner"], 0,
    "Once earned and disbursed it is the broker's."),
  Q("A buyer's advance for a credit report is:",
    ["Trust money", "The broker's fee", "Not reportable"], 0,
    "Funds advanced for expenses are held in trust."),
 ],
 "FDIC coverage": [
  Q("FDIC pass-through coverage treats each client as:",
    ["A separate account owner", "Part of one broker account",
     "Uninsured"], 0,
    "Provided the broker meets the recordkeeping rules."),
  Q("A client with $250,000 already at the same bank:",
    ["Has no coverage for their new deposit", "Gets a second $250,000",
     "Is covered automatically"], 0,
    "The FDIC aggregates their deposits at that bank."),
 ],
 "Records, audits, and affiliates": [
  Q("GREC may examine a trust account:",
    ["On reasonable request", "Only with a warrant", "Only at renewal"], 0,
    "It may accept a CPA certification instead, at its discretion."),
  Q("An affiliate holding an account for their own rentals must provide:",
    ["At least quarterly written reconciliations", "Annual summaries",
     "Nothing to the broker"], 0,
    "And the broker registers it and stays responsible."),
 ],
 "Disputes": [
  Q("Both parties demand the earnest money. The broker should:",
    ["Hold it and use interpleader", "Release to the first to ask",
     "Split it"], 0,
    "Choosing a side invites a conversion claim."),
 ],
},

"georgia/contracts": {
 "The binding agreement date": [
  Q("A Georgia contract becomes binding when:",
    ["Acceptance is communicated to the offeror", "The seller signs",
     "The deed is recorded"], 0,
    "All deadlines run from that date."),
  Q("An offer may be revoked:",
    ["Any time before acceptance is communicated", "Never once signed",
     "Only within 24 hours"], 0,
    "After that, withdrawal is a breach."),
 ],
 "Due diligence": [
  Q("During the due diligence period a Georgia buyer may typically terminate:",
    ["For any reason, recovering the earnest money", "Only for inspection defects",
     "Only with seller consent"], 0,
    "After it expires, the exits narrow sharply."),
  Q("The due diligence period is measured from the:",
    ["Binding agreement date", "Offer date", "Closing date"], 0,
    "Which is why getting that date right matters."),
 ],
 "Form filling vs. practising law": [
  Q("A Georgia licensee may:",
    ["Fill in blanks on approved preprinted forms", "Draft original clauses",
     "Advise on legal effect"], 0,
    "Drafting is the unauthorised practice of law."),
  Q("A typed special stipulation conflicting with preprinted text:",
    ["Prevails over the preprinted text", "Is void",
     "Requires GREC approval"], 0,
    "Specific terms beat boilerplate - which is why sloppy ones are dangerous."),
 ],
 "Description and definiteness": [
  Q("A Georgia contract's property description must:",
    ["Identify the property with reasonable certainty", "State the acreage",
     "Match the tax assessor exactly"], 0,
    "A vague description can make it unenforceable."),
 ],
 "Listing agreements": [
  Q("A Georgia listing agreement must:",
    ["Be in writing with a definite expiration date", "Renew automatically",
     "Be recorded"], 0,
    "Automatic renewals are prohibited."),
 ],
 "Earnest money and default": [
  Q("For a liquidated damages clause to be enforceable it must:",
    ["Be a reasonable pre-estimate of loss", "Exceed actual damages",
     "Be at least 10% of the price"], 0,
    "A sum operating as a penalty is void."),
 ],
 "Contingencies you will see": [
  Q("A kick-out clause lets the seller:",
    ["Keep marketing while a buyer's sale contingency is pending",
     "Cancel at any time", "Raise the price"], 0,
    "The buyer must then remove the contingency or terminate."),
 ],
},

"georgia/disclosures": {
 "The scope of the duty": [
  Q("Under BRRETA the disclosure duty covers:",
    ["Adverse material facts actually known", "Everything an inspector would find",
     "Only what the seller wrote down"], 0,
    "There is no duty to discover - but the duty runs to customers too."),
  Q("A licensee who sees a fresh paint patch over a stain should:",
    ["Point it out and suggest an inspection", "Say nothing",
     "Repaint it"], 0,
    "No duty to discover is not a licence to ignore."),
 ],
 "Stigmatized property": [
  Q("Georgia protects a licensee who:",
    ["Does not volunteer that a death occurred", "Denies a death occurred",
     "Both"], 0,
    "Nondisclosure is protected; an affirmative lie is not."),
  Q("Asked directly whether someone died there, the safest answer is to:",
    ["Decline and refer them to other sources", "Deny it", "Confirm it in writing"], 0,
    "Declining keeps you inside the protection."),
 ],
 "Who fills in the form": [
  Q("Georgia's property disclosure statement is completed by the:",
    ["Seller", "Listing broker", "Closing attorney"], 0,
    "Filling it in for them transfers their liability to you."),
  Q("If a licensee knows an answer on the form is false, they must:",
    ["Not pass it along, and withdraw if the seller refuses to correct it",
     "Change the form themselves", "Disclose only to the buyer's agent"], 0,
    "You cannot be the conduit for a known falsehood."),
 ],
 "What must be disclosed": [
  Q("Which must be disclosed?",
    ["A known failing septic system", "A prior owner's bankruptcy",
     "A neighbour dispute"], 0,
    "Physical conditions affecting value, safety, or use."),
  Q("Flood plain location is:",
    ["An adverse material fact", "Only the lender's concern", "Confidential"], 0,
    "It affects value, insurability, and use."),
 ],
 "What must not be disclosed": [
  Q("A former occupant's HIV status is:",
    ["Protected - handicap is a protected class", "Disclosable on request",
     "Required to be disclosed"], 0,
    "Disclosure would be discriminatory."),
 ],
},

"georgia/procedures": {
 "Attorney closings": [
  Q("A Georgia closing must be supervised by:",
    ["A licensed attorney", "A title company officer", "The listing broker"], 0,
    "Examining title and preparing documents is the practice of law."),
  Q("The closing attorney customarily represents:",
    ["The lender", "The buyer", "Both parties equally"], 0,
    "A buyer wanting an advocate must retain their own counsel."),
 ],
 "The security deed": [
  Q("A Georgia security deed:",
    ["Passes legal title to the lender until payoff", "Creates only a lien",
     "Requires a trustee"], 0,
    "That makes Georgia a title-theory state."),
 ],
 "Foreclosure": [
  Q("Georgia foreclosure sales occur on:",
    ["The first Tuesday of the month", "Any business day",
     "The last Friday of the month"], 0,
    "On the courthouse steps, after advertisement in the legal organ."),
  Q("Georgia foreclosure is:",
    ["Nonjudicial under a power of sale", "Judicial, requiring a lawsuit",
     "Automatic after 90 days"], 0,
    "Which is why it moves comparatively fast."),
 ],
 "Transfer tax and recording": [
  Q("Georgia's transfer tax is:",
    ["$1.00 per $1,000 of consideration", "1% of the price",
     "$0.10 per $1,000"], 0,
    "Customarily paid by the seller."),
  Q("Georgia deeds are recorded with the:",
    ["Clerk of superior court", "Secretary of State", "Probate court"], 0,
    "In the county where the land lies."),
 ],
 "Taxes and prorations": [
  Q("Georgia property taxes become a lien on:",
    ["January 1", "The closing date", "When the bill is mailed"], 0,
    "Which is why closings prorate them."),
 ],
 "Ownership rules that differ": [
  Q("Georgia does NOT recognise:",
    ["Tenancy by the entirety", "Joint tenancy", "Tenancy in common"], 0,
    "Spouses use joint tenancy with right of survivorship instead."),
  Q("Adverse possession without colour of title in Georgia takes:",
    ["20 years", "7 years", "10 years"], 0,
    "7 years applies WITH colour of title."),
 ],
 "At the table": [
  Q("The Closing Disclosure must be received:",
    ["3 business days before consummation", "At closing", "3 days after"], 0,
    "TRID applies in Georgia like everywhere else."),
 ],
},

"georgia/fair-housing": {
 "The seven federal classes": [
  Q("Which is federally protected in housing?",
    ["Familial status", "Source of income", "Marital status"], 0,
    "Source of income and marital status are not among the seven."),
 ],
 "Steering and blockbusting in practice": [
  Q("Giving school ratings only to certain buyers is:",
    ["Steering", "Good service", "Blockbusting"], 0,
    "Selective information channels buyers just as effectively."),
  Q("An ad saying 'no children under 12' violates:",
    ["Familial status protection", "Nothing", "Age discrimination law"], 0,
    "Describe the property, not the occupant."),
 ],
 "Disability: two different duties": [
  Q("A tenant wants to install a grab bar. This is a:",
    ["Modification, at the tenant's expense", "Accommodation, at the landlord's expense",
     "Prohibited alteration"], 0,
    "Physical change = modification."),
  Q("Charging a pet fee for an assistance animal is:",
    ["Unlawful", "Lawful if uniform", "Lawful if disclosed"], 0,
    "An assistance animal is not a pet."),
 ],
 "Unlawful client instructions": [
  Q("A seller insists you exclude a protected class. You should:",
    ["Refuse and withdraw if they persist", "Comply and document it",
     "Refer them to a colleague"], 0,
    "Referring simply relocates the violation."),
 ],
 "Enforcement": [
  Q("One discriminatory act can result in:",
    ["A HUD case, a lawsuit, and GREC discipline", "Only a HUD case",
     "Only licence discipline"], 0,
    "The tracks are independent."),
 ],
},

"comp/vocabulary": {
 "Pairs that get swapped": [
  Q("Which is a physical intrusion onto another's land?",
    ["Encroachment", "Encumbrance", "Easement in gross"], 0,
    "Every encroachment is an encumbrance; not every encumbrance is physical."),
  Q("In 'mortgagor' and 'mortgagee', the borrower is the:",
    ["Mortgagor", "Mortgagee", "Neither"], 0,
    "The '-or' gives, the '-ee' receives."),
 ],
 "The value words": [
  Q("An opinion of the most probable price is:",
    ["Market value", "Market price", "Cost"], 0,
    "Price is what it actually sold for."),
 ],
 "The income statement in order": [
  Q("What comes immediately after net operating income?",
    ["Debt service, giving cash flow", "Vacancy loss", "Operating expenses"], 0,
    "Debt service is never an operating expense."),
 ],
 "Lien classifications are three independent axes": [
  Q("A judgment lien is:",
    ["General, involuntary, statutory", "Specific and voluntary",
     "Specific and equitable"], 0,
    "A mortgage is specific and voluntary."),
 ],
 "The four leasehold estates": [
  Q("Which renews automatically until notice?",
    ["Periodic estate", "Estate for years", "Estate at sufferance"], 0,
    "An estate for years ends on its own with no notice."),
 ],
 "Deed vocabulary in sequence": [
  Q("Which step actually passes title?",
    ["Delivery and acceptance", "Acknowledgment", "Recording"], 0,
    "Notarisation is for recording; recording is for notice."),
 ],
 "The four public powers": [
  Q("Which power regulates without paying?",
    ["Police power", "Eminent domain", "Escheat"], 0,
    "Only eminent domain requires just compensation."),
 ],
},

"comp/situational": {
 "The decision framework": [
  Q("A client asks you to do something unlawful. You:",
    ["Refuse, and withdraw if they persist", "Comply but document it",
     "Pass them to a colleague"], 0,
    "Referring relocates the violation."),
  Q("You know a material fact about the property. You:",
    ["Disclose it", "Keep it confidential for your client",
     "Disclose only if asked"], 0,
    "Confidentiality never covers a defect."),
 ],
 "Situations that recur": [
  Q("A buyer wants the price inflated with cash back at closing. This is:",
    ["Loan fraud if concealed from the lender", "A normal decorating allowance",
     "Acceptable if both parties agree"], 0,
    "The licensee who writes it participates."),
  Q("You spot an error on the settlement statement. You:",
    ["Raise it before anyone signs", "Mention it afterward",
     "Defer to the closing attorney"], 0,
    "Post-closing corrections are far harder."),
 ],
 "What confidentiality actually covers": [
  Q("A past client asks the neighbour's recorded sale price. You:",
    ["May share it - it is public record", "Must refuse", "Need consent"], 0,
    "Confidentiality covers motivation and position, not public facts."),
 ],
},

"comp/grec-deep": {
 "The education ladder in order": [
  Q("Put in order: prelicense, postlicense, CE:",
    ["75 hours, 25 hours, 24 per four years", "25, 75, 36",
     "60, 25, 24 per year"], 0,
    "The 75 and 25 are frequently transposed."),
 ],
 "Trust account mechanics": [
  Q("Every trust account must be:",
    ["Bank-designated and registered with GREC", "Interest-bearing",
     "Held at a Georgia bank"], 0,
    "A nonresident broker may keep one at home if GREC may examine it."),
 ],
 "What the Commission does": [
  Q("A GREC consent settlement includes:",
    ["Agreed findings, conclusions and a sanction", "Only a fine",
     "Consumer restitution"], 0,
    "No hearing is held."),
 ],
 "What the Commission does NOT do": [
  Q("GREC will not:",
    ["Resolve a commission dispute between brokers", "Revoke a licence",
     "Investigate on its own motion"], 0,
    "Those go to arbitration or the courts."),
 ],
 "Firm operations": [
  Q("A suspended qualifying broker's corporation may continue if it:",
    ["Immediately designates a replacement", "Appeals the suspension",
     "Ceases activity for 30 days"], 0,
    "Otherwise all affiliated licences are suspended too."),
 ],
},

"comp/closing-math": {
 "The anchor entries": [
  Q("The sale price appears as:",
    ["Buyer debit, seller credit", "Buyer credit, seller debit",
     "A debit to both"], 0,
    "Everything else adjusts around this line."),
  Q("The new loan is a:",
    ["Buyer credit", "Buyer debit", "Seller credit"], 0,
    "The lender's money reduces what the buyer owes."),
 ],
 "The one question that settles every proration": [
  Q("Rent collected in advance by the seller produces a:",
    ["Seller debit and buyer credit", "Seller credit and buyer debit",
     "No entry"], 0,
    "The seller is holding cash belonging to the buyer."),
  Q("Prepaid insurance the buyer will benefit from produces a:",
    ["Seller credit and buyer debit", "Seller debit and buyer credit",
     "No entry"], 0,
    "The seller is reimbursed - opposite to rent."),
 ],
 "Cash to close and seller's net": [
  Q("Cash to close equals:",
    ["Debits minus credits", "Price minus loan", "Price plus costs"], 0,
    "Credits include the loan and earnest money already paid."),
 ],
 "Mechanics": [
  Q("The banker's year used for prorations has:",
    ["360 days", "365 days", "366 days"], 0,
    "Twelve 30-day months, unless told otherwise."),
 ],
},
}
