# -*- coding: utf-8 -*-
"""Comprehensive subtest, part A: vocabulary & terminology, situational judgment.

Vocabulary items deliberately pair terms people confuse with each other, so the
distractors are the neighbouring term rather than an obviously wrong word.
"""

def Q(topic, q, choices, answer, concept, explain, d=2):
    return {"topic": "comp/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain, "difficulty": d}

ROWS = [
# --------------------------------------------------------------- vocabulary
Q("vocabulary", "A charge or claim against property that does not prevent transfer but travels with it is an:",
  ["Encumbrance", "Encroachment", "Estoppel", "Escheat"], 0,
  "Encumbrance vs. encroachment",
  "An ENCUMBRANCE is any claim, lien, restriction, or easement limiting the fee. An ENCROACHMENT is the specific case of a physical intrusion. All encroachments are encumbrances; not all encumbrances are physical."),
Q("vocabulary", "The written instrument that conveys title is a deed. The act that makes it effective is:",
  ["Execution", "Acknowledgment", "Delivery and acceptance", "Recording"], 2,
  "Deed vocabulary in sequence",
  "EXECUTION is signing; ACKNOWLEDGMENT is the notary's certification (needed to record); DELIVERY AND ACCEPTANCE is what actually passes title; RECORDING gives constructive notice. Only delivery and acceptance are essential between the parties."),
Q("vocabulary", "A lien that attaches to all of a debtor's property rather than one specific parcel is:",
  ["A specific lien", "A general lien", "A voluntary lien", "A statutory lien"], 1,
  "Lien classifications are independent axes",
  "Liens sort three ways at once: general vs. specific (scope), voluntary vs. involuntary (consent), statutory vs. equitable (source). A judgment lien is general, involuntary, and statutory. A mortgage is specific and voluntary."),
Q("vocabulary", "Money a tenant pays that the landlord holds and may return is a security deposit. Rent paid for the final month in advance is:",
  ["Also a security deposit in every state", "Prepaid rent, which is generally earned income to the landlord",
   "An escrow advance", "A trade fixture"], 1,
  "Security deposit vs. prepaid rent",
  "A security deposit remains the tenant's money held in trust against damage. PREPAID RENT is payment for a specific period and belongs to the landlord when received. Mislabeling one as the other is a common trust-account error."),
Q("vocabulary", "The right of a defaulting borrower to reclaim property AFTER a foreclosure sale is:",
  ["Equitable right of redemption", "Statutory right of redemption",
   "Right of reverter", "Right of first refusal"], 1,
  "Two redemption rights",
  "The EQUITABLE right runs from default up to the moment of sale. The STATUTORY right, where a state grants one, runs for a period AFTER the sale. The dividing line is the sale itself."),
Q("vocabulary", "A written summary of every recorded document affecting a parcel is:",
  ["A chain of title", "An abstract of title", "A title commitment", "A certificate of title"], 1,
  "Title-evidence vocabulary",
  "The ABSTRACT is the condensed history of all recorded instruments. The CHAIN OF TITLE is the ownership sequence within it. A COMMITMENT is the insurer's promise to issue a policy; an attorney's OPINION interprets the abstract."),
Q("vocabulary", "Property acquired by one spouse before marriage, in a community property state, is:",
  ["Community property", "Separate property", "Tenancy by the entirety", "Homestead property"], 1,
  "Community vs. separate property",
  "Property owned before marriage, or received during marriage by gift or inheritance, stays SEPARATE. Community property is what the spouses acquire during marriage through effort. Georgia is not a community property state."),
Q("vocabulary", "The clause in a mortgage requiring the lender to release the lien when the debt is paid is:",
  ["Acceleration", "Alienation", "Defeasance", "Subordination"], 2,
  "Mortgage clauses that sound alike",
  "DEFEASANCE defeats the lien on payment. ACCELERATION calls the balance on default; ALIENATION (due-on-sale) calls it on transfer; SUBORDINATION voluntarily moves a lien to a lower priority."),
Q("vocabulary", "An estate that continues indefinitely and renews automatically until notice is given is a:",
  ["Estate for years", "Periodic estate", "Estate at will", "Estate at sufferance"], 1,
  "The four leasehold estates",
  "A PERIODIC estate (month-to-month) renews automatically until notice. An ESTATE FOR YEARS has a fixed start and end and needs no notice. An ESTATE AT WILL ends at either party's pleasure; SUFFERANCE is a holdover without permission."),
Q("vocabulary", "The appraisal principle that a property's value is influenced by the values of surrounding properties is:",
  ["Conformity", "Contribution", "Substitution", "Anticipation"], 0,
  "Appraisal principles that are easily swapped",
  "CONFORMITY: maximum value arises when properties are reasonably similar. CONTRIBUTION: a component is worth what it adds to the whole, not what it cost. SUBSTITUTION caps value at the cost of an equal alternative; ANTICIPATION values future benefits."),
Q("vocabulary", "Personal property permanently attached to real property becomes:",
  ["An emblement", "A fixture", "A chattel", "A trade fixture"], 1,
  "Real vs. personal property vocabulary",
  "A FIXTURE is former personal property now part of the realty. A CHATTEL is personal property generally. EMBLEMENTS are annual crops, treated as personal property of the tenant who planted them. A TRADE FIXTURE stays the commercial tenant's property."),
Q("vocabulary", "The document a buyer signs promising to repay a loan is the note. The document pledging the property as security in Georgia is the:",
  ["Mortgage", "Security deed", "Deed of trust", "Land contract"], 1,
  "The two loan documents, Georgia edition",
  "The NOTE is the promise to pay; the security instrument pledges the collateral. Georgia uses a SECURITY DEED (deed to secure debt), which transfers legal title to the lender until payoff -- unlike a mortgage, which creates only a lien."),
Q("vocabulary", "A provision allowing a later-recorded lien to take priority over an earlier one is:",
  ["Subrogation", "Subordination", "Substitution", "Satisfaction"], 1,
  "The 'sub-' words",
  "SUBORDINATION voluntarily lowers a lien's priority, commonly so a construction lender can take first position. SUBROGATION is one party stepping into another's legal claim, typical of insurers. SATISFACTION is the recorded proof a debt is paid."),
Q("vocabulary", "The measure of a property's value used to compute property taxes is:",
  ["Market value", "Assessed value", "Insurable value", "Book value"], 1,
  "The many kinds of value",
  "ASSESSED value is the tax base, often a set percentage of market value. INSURABLE value covers the improvements only, since land does not burn. Confusing assessed with market value is a persistent exam trap."),
Q("vocabulary", "A tenant who remains after the lease ends, without the landlord's consent, holds an:",
  ["Estate at will", "Estate at sufferance", "Estate for years", "Periodic estate"], 1,
  "Holdover tenancy",
  "SUFFERANCE is the lowest estate: possession without right, but not quite trespass because entry was originally lawful. If the landlord accepts rent, it typically converts to a periodic tenancy."),
Q("vocabulary", "Compensation paid to a broker who is the direct cause of a completed sale reflects:",
  ["Procuring cause", "Proximate cause", "Ready cause", "Efficient cause"], 0,
  "Procuring cause",
  "PROCURING CAUSE is the uninterrupted chain of events by which a broker produced the buyer. It is the standard used to resolve commission disputes between brokers, usually through arbitration rather than the license law."),
Q("vocabulary", "An agreement where the seller retains legal title while the buyer takes possession and pays over time is a:",
  ["Purchase-money mortgage", "Land contract", "Lease option", "Wraparound mortgage"], 1,
  "Seller-financing arrangements",
  "A LAND CONTRACT (contract for deed) splits title: seller keeps legal title, buyer holds equitable title and possession. A PURCHASE-MONEY MORTGAGE conveys title at closing with the seller taking back a lien. A LEASE OPTION is a lease plus a right to buy."),
Q("vocabulary", "The gradual wearing away of land by water is:",
  ["Accretion", "Erosion", "Avulsion", "Reliction"], 1,
  "Four ways water changes land",
  "EROSION is gradual loss; ACCRETION is gradual gain; AVULSION is sudden change, which does NOT alter boundaries; RELICTION is land exposed by permanently receding water."),
Q("vocabulary", "A blanket term for the government's power to regulate land use for health and safety, without compensation, is:",
  ["Eminent domain", "Police power", "Escheat", "Taxation"], 1,
  "PETE, the four public powers",
  "Police power regulates without paying -- zoning, codes, environmental rules. Eminent domain TAKES and must pay. Escheat claims ownerless property; taxation funds government. Only eminent domain requires just compensation."),
Q("vocabulary", "The dollar amount by which a property's income exceeds operating expenses, before debt service, is:",
  ["Gross rent", "Effective gross income", "Net operating income", "Cash flow"], 2,
  "The income statement in order",
  "Potential gross, minus vacancy, equals EFFECTIVE GROSS. Minus operating expenses equals NET OPERATING INCOME. Minus debt service equals CASH FLOW. Debt service is never an operating expense -- a favorite trap in cap rate problems."),

# ------------------------------------------------------------- situational
Q("situational",
  "You are showing a home. The buyer says, 'Before we go further -- I don't want to be in a neighborhood with too many immigrants.' You should:",
  ["Note the preference and screen listings accordingly",
   "Explain you cannot select or exclude areas on that basis, and continue on objective criteria",
   "End the relationship immediately without explanation",
   "Show only areas matching the request without comment"], 1,
  "A client's discriminatory request does not bind you",
  "Acting on the request is steering, whoever asked for it. The professional move is to state plainly that you select properties on objective criteria -- price, size, schools, commute -- and continue on that basis. Most buyers accept it."),
Q("situational",
  "Your seller client receives two offers. One is $5,000 higher but from a buyer whose lender you know to be unreliable. You should:",
  ["Present only the offer you consider stronger",
   "Present both, with your assessment of each offer's strength and risk",
   "Present both without comment, since price is the seller's decision",
   "Advise the seller to counter both"], 1,
  "Presenting offers plus giving advice",
  "All offers get presented -- but a client is owed advice, not just paperwork. Highlighting financing risk is exactly the value of representation. Presenting without comment under-serves the client; withholding an offer breaches outright."),
Q("situational",
  "At the closing table you notice the settlement statement omits a $1,200 repair credit the parties agreed to. Nobody else has caught it. You should:",
  ["Stay quiet, since the closing attorney prepared the figures",
   "Raise it immediately, before anyone signs",
   "Mention it to your client afterward", "Sign and request a correction later"], 1,
  "Speak up before the signatures",
  "Reasonable care obliges you to flag a known error while it can still be fixed cheaply. Deference to the attorney is not a defense when you personally know the number is wrong, and post-closing corrections are far harder to obtain."),
Q("situational",
  "A buyer client asks you to recommend an inspector. You have a regular referral who pays you $50 per referral. You should:",
  ["Recommend them, since you know their work",
   "Disclose the payment, or better, provide several names and take no fee",
   "Recommend someone else and keep the arrangement",
   "Let the buyer find their own inspector"], 1,
  "Referral fees and undisclosed compensation",
  "Undisclosed compensation for a referral is a conflict, and in a federally related mortgage transaction a referral fee for settlement services violates RESPA Section 8 outright. Offering several names and declining the fee removes the problem."),
Q("situational",
  "Your seller tells you the HVAC failed last winter and was patched, then says, 'Don't put that on the disclosure.' You should:",
  ["Comply -- the disclosure is the seller's document",
   "Explain it must be disclosed, and end the engagement if the seller refuses",
   "Leave it off but tell buyers verbally", "Complete the form yourself with the information"], 1,
  "You cannot participate in concealment",
  "A known defect affecting a major system is material. You never complete the seller's form for them, and you cannot market a property while knowing the disclosure is false. If the seller will not correct it, withdraw."),
Q("situational",
  "You receive an earnest money check made out to your brokerage. The buyer asks you to hold it until Friday when their paycheck clears. You should:",
  ["Hold it, since the buyer asked",
   "Deposit it promptly unless all parties give written authority to hold it",
   "Deposit it and let it bounce", "Return the check and ask for cash"], 1,
  "Prompt deposit and written authority",
  "Trust funds go in promptly. Any deviation -- holding a check, a postdated check, an interest-bearing account -- needs clear written authority agreed to by ALL parties, not just the buyer, because the seller has an interest in the deposit too."),
Q("situational",
  "A past client calls asking what their neighbor's house sold for. The sale was your listing and the price is in the MLS and public records. You may:",
  ["Not disclose it, as it is confidential",
   "Share it, since a closed sale price is public information",
   "Share it only with the seller's permission", "Share only an approximate figure"], 1,
  "What confidentiality actually covers",
  "Confidentiality protects your client's motivations, finances, and negotiating position -- not facts already public. A recorded sale price is public record. Refusing to state public information is not a duty, just unhelpfulness."),
Q("situational",
  "Mid-transaction you realize the buyer you are representing is your broker's brother-in-law, and you were not told. You should:",
  ["Continue, since the relationship is not yours",
   "Raise it with your broker and ensure the relationship is disclosed to the seller",
   "Withdraw from the transaction", "Tell the seller's agent privately"], 1,
  "Firm-level conflicts still need disclosure",
  "A material relationship between the firm and a party must be disclosed to the other side's principal, regardless of which licensee holds it. Going around your broker to the other agent is not the channel; raising it internally and getting proper disclosure is."),
Q("situational",
  "A buyer asks you to write an offer $20,000 above the contract price with a $20,000 'decorating allowance' back at closing, so they can borrow more. You should:",
  ["Write it, since the parties agreed",
   "Refuse -- this is loan fraud if concealed from the lender",
   "Write it and disclose it only if asked", "Suggest a smaller amount"], 1,
  "Silent second / inflated price schemes",
  "Inflating price to extract cash without the lender's knowledge is mortgage fraud, and the licensee who writes it participates. The transaction can be structured legitimately only if every term is fully disclosed to the lender."),
Q("situational",
  "You are a dual agent. The buyer tells you privately they would pay $15,000 more. The seller asks you what the buyer's ceiling is. You should:",
  ["Tell the seller, who is also your client",
   "Decline, explaining you cannot reveal either side's confidential position",
   "Hint at it without stating the number", "Tell the seller only after an offer is signed"], 1,
  "The dual agent's neutrality",
  "As a dual agent you hold both sides' confidences and may reveal neither. Hinting is the same disclosure by another route. This is exactly the limitation both parties acknowledged when they consented in writing."),
Q("situational",
  "An unrepresented buyer at your listing asks, 'Do you think I should offer less than asking?' You represent the seller. You should:",
  ["Advise them to offer full price",
   "Explain you represent the seller and cannot advise them on price, and suggest they get their own representation",
   "Give them your honest opinion", "Refuse to speak with them further"], 1,
  "Customers get honesty, not advice",
  "Advising a customer on negotiating strategy against your own client breaches loyalty and can create accidental agency. Telling them to offer full price is self-serving pressure. Clarify your role and point them toward representation."),
Q("situational",
  "You discover after closing that you miscalculated a proration and your client overpaid $400. Nobody has noticed. You should:",
  ["Say nothing, since the closing is final",
   "Tell your client promptly and work to correct it",
   "Wait to see if anyone raises it", "Quietly reimburse the $400 without explanation"], 1,
  "Accounting survives closing",
  "The duty to account does not end at the closing table. Disclosing your own error is uncomfortable but it is the duty, and errors-and-omissions coverage exists for exactly this. Silent reimbursement hides the error from the person entitled to know."),
Q("situational",
  "A tenant applicant with a visual impairment asks whether they may install a doorbell light signal at their own expense. You should tell the landlord:",
  ["They may refuse, since it alters the unit",
   "This is a reasonable modification the tenant may make at their own expense",
   "They must install it themselves", "They may charge a higher deposit"], 1,
  "Modification vs. accommodation, applied",
  "A physical change is a MODIFICATION, permitted at the tenant's expense with possible restoration on move-out. Had the request been to waive a policy -- a no-pets rule for a service animal -- it would be an ACCOMMODATION at the landlord's expense."),
Q("situational",
  "Your listing has been on the market 90 days with no offers. The seller refuses to lower the price and blames your marketing. The most professional response is:",
  ["Reduce your commission to compensate",
   "Present current comparable sales and days-on-market data and discuss options",
   "Terminate the listing", "Advertise more aggressively at your own cost"], 1,
  "Advice grounded in evidence",
  "Bring data, not opinion or concession. Comparables and market absorption reframe the conversation around the market rather than blame, and give the seller a real basis to decide between a price change, staging, or waiting."),
Q("situational",
  "A licensee in your office asks you to hold their pocket card while they meet a client, because theirs expired last week. You should:",
  ["Lend it, as a courtesy",
   "Refuse and inform your broker -- practising on an expired license is unlicensed activity",
   "Lend it but say nothing", "Suggest they use a colleague's instead"], 1,
  "Unlicensed activity implicates the firm",
  "Practising on an expired license is unlicensed activity, and helping conceal it exposes you and the broker. The broker must know, because supervision failures are charged against the firm as well as the individual."),
Q("situational",
  "A buyer waives the inspection to win a bidding war. You believe the roof is near the end of its life. You should:",
  ["Say nothing, since the buyer chose to waive",
   "Document your recommendation to inspect in writing, and disclose what you actually observe",
   "Refuse to write the offer", "Order an inspection anyway"], 1,
  "Waiver does not erase your duty",
  "The buyer may waive an inspection; you may not waive disclosure of what you actually know or see. Putting your recommendation in writing protects the buyer's decision-making and your own position if the roof fails later."),
]
