# -*- coding: utf-8 -*-
"""Comprehensive subtest, part B: GREC law deep-dive, closing & settlement math."""

def Q(topic, q, choices, answer, concept, explain, d=2):
    return {"topic": "comp/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain, "difficulty": d}

ROWS = [
# --------------------------------------------------------------- grec-deep
Q("grec-deep", "Georgia's education requirements, in order for a salesperson, are:",
  ["25-hour prelicense, then 75-hour postlicense, then 24 hours CE per 4 years",
   "75-hour prelicense, then 25-hour postlicense within one year, then 24 hours CE per 4 years",
   "60-hour prelicense, then 30-hour postlicense, then 36 hours CE per 4 years",
   "75-hour prelicense, then 24 hours CE annually"], 1,
  "The three education stages",
  "75 hours before licensure; 25 hours of postlicense inside the first year; then at least 24 hours of CE per four-year renewal period. The 75/25 numbers are frequently transposed, and the CE figure is often misquoted as 36."),
Q("grec-deep", "A Georgia broker maintains three trust accounts: earnest money, rents, and security deposits. GREC requires that:",
  ["Only the earnest money account be registered",
   "Each account be bank-designated as trust and registered with the Commission, with the broker holding signatory power",
   "The accounts be consolidated into one", "Each account be interest-bearing"], 1,
  "Multiple trust accounts",
  "Brokers must have at least one and may have more. Every one must be designated as a trust or escrow account by the BANK, registered with GREC on Commission forms, and carry the broker's signatory power."),
Q("grec-deep", "A Georgia broker changes banks. The broker must notify GREC:",
  ["At the next renewal", "In writing, on Commission forms, when the change occurs",
   "Only if the account number changes", "Verbally to an investigator"], 1,
  "Trust account change notifications",
  "Written notice on Commission forms is required when the bank changes, the account name or number changes, the bank changes names, or the account closes. A letter satisfies the requirement, but it must be in writing."),
Q("grec-deep", "GREC may initiate an investigation:",
  ["Only on a sworn written complaint from a transaction party",
   "On a sworn written request from anyone, or on the Commission's own motion",
   "Only at the request of the Attorney General", "Only after a civil judgment"], 1,
  "Who can start a GREC case",
  "Anyone may file a sworn written request, and the Commission may also act on its own motion -- so an audit finding or a news report can start a case with no complainant at all. The licensee is notified that they are under investigation."),
Q("grec-deep", "In a GREC consent settlement, the parties agree on:",
  ["Only the sanction", "Findings of fact, conclusions of law, and a sanction, with no hearing held",
   "A hearing date", "The amount of consumer restitution"], 1,
  "What a consent settlement contains",
  "The respondent and Commission agree on specific findings of fact, conclusions of law, and a sanction, and no hearing is held. Restitution is never part of it, because GREC has no power to order repayment of losses."),
Q("grec-deep", "A Georgia licensee wishes to hold their license without affiliating with a broker. They may:",
  ["Not do so -- affiliation is mandatory",
   "Apply for inactive status, paying fees and still meeting postlicense education",
   "Practise independently", "Affiliate with an out-of-state broker only"], 1,
  "Inactive status",
  "A licensee who passes the exam may go inactive rather than affiliate, but must still pay the license and renewal fees and complete the postlicense requirement. Inactive licensees may not perform licensed activity."),
Q("grec-deep", "A nonresident applying for a Georgia salesperson license who holds no license in their home state must:",
  ["Be licensed at home first", "Meet the same requirements Georgia imposes on residents and affiliate with a GREC-licensed broker",
   "Take only the state portion of the exam", "Obtain a waiver from the Commission"], 1,
  "Nonresident licensure",
  "Such an applicant completes the full Georgia requirements and must affiliate with a broker licensed by GREC -- who may themselves be a resident or nonresident. Georgia's postlicense and CE requirements apply to nonresidents too."),
Q("grec-deep", "Two Georgia brokers dispute which of them is entitled to a commission. GREC will:",
  ["Decide the dispute and order payment", "Not resolve it -- commission disputes go to arbitration or the courts",
   "Suspend both licenses pending resolution", "Split the commission equally"], 1,
  "What GREC does not do",
  "GREC administers the license law, makes rules, investigates, and disciplines. It does not adjudicate money disputes between licensees, and it cannot order anyone to pay. Procuring-cause disputes go to association arbitration or civil court."),
Q("grec-deep", "A Georgia salesperson may lawfully accept compensation for licensed activity from:",
  ["Any party to the transaction", "Their affiliated broker only",
   "The closing attorney", "Another licensee who refers business"], 1,
  "The flow of compensation",
  "A salesperson works through the broker and may only be paid by that broker. Accepting money directly from a client, another licensee, or a settlement provider is a license law violation, however the parties label it."),
Q("grec-deep", "A Georgia broker dies with $80,000 of client funds in a properly maintained trust account. Those funds:",
  ["Become part of the broker's estate for the heirs",
   "Are not part of the estate and remain the clients' property",
   "Escheat to the state", "Are divided among the broker's creditors"], 1,
  "Why the trust account exists",
  "The InfoBase lists this as a core purpose: properly maintained trust funds stay outside the broker's estate on death, are not subject to garnishment on a judgment against the broker, and do not go to creditors in bankruptcy."),
Q("grec-deep", "A net listing in Georgia is:",
  ["Illegal in all circumstances", "Permitted only under strict disclosure conditions",
   "The default listing form", "Permitted only for commercial property"], 1,
  "Net listings in Georgia",
  "Georgia permits net listings under strict disclosure, unlike states that ban them outright. They remain disfavored because the broker profits from every dollar above the seller's stated net -- a direct conflict with the client's interest."),
Q("grec-deep", "A Georgia broker's advertising must:",
  ["Use the licensee's name only", "Identify the brokerage firm and not be misleading",
   "Be pre-approved by GREC", "Appear only in the MLS"], 1,
  "Advertising rules",
  "Advertising must name the firm and must not mislead. A licensee may never advertise so as to imply they operate independently of their broker -- a growing issue with personal branding and social media."),
Q("grec-deep", "A suspended Georgia qualifying broker's corporation may keep operating if it:",
  ["Ceases all activity for the suspension period",
   "Immediately designates a new qualifying broker",
   "Transfers the license to a salesperson", "Appeals the suspension"], 1,
  "Suspension of a qualifying broker",
  "If the corporation or LLC immediately designates a replacement qualifying broker, it may continue and keep its wall certificate and its affiliates' licenses. Otherwise the firm's license and all affiliated licenses are suspended for the same period."),

# ------------------------------------------------------------ closing-math
Q("closing-math",
  "On a settlement statement, the buyer's earnest money deposit already held by the broker appears as a:",
  ["Debit to the buyer", "Credit to the buyer", "Credit to the seller", "Debit to the seller"], 1,
  "Debits and credits, buyer's side",
  "The buyer already paid it, so it reduces what they owe at the table -- a CREDIT to the buyer. It is not a seller credit; the money never belonged to the seller. Debits increase what a party owes; credits reduce it."),
Q("closing-math",
  "The sale price appears on a settlement statement as:",
  ["A debit to the buyer and a credit to the seller",
   "A credit to the buyer and a debit to the seller",
   "A debit to both", "A credit to both"], 0,
  "The single largest line",
  "The buyer owes the price (debit to buyer); the seller is owed it (credit to seller). Every prorated item then adjusts around this anchor. Reversing it inverts the entire statement."),
Q("closing-math",
  "A seller's existing loan payoff of $184,000 appears as:",
  ["A credit to the seller", "A debit to the seller", "A debit to the buyer", "A credit to the buyer"], 1,
  "Seller's payoff",
  "The payoff comes out of the seller's proceeds -- a DEBIT to the seller. It does not touch the buyer's side at all unless the buyer is assuming the loan, in which case it becomes a buyer credit and seller debit instead."),
Q("closing-math",
  "Annual taxes of $4,320 are unpaid. Closing is September 1, with the seller responsible through August 31 in a 360-day year. The entry is:",
  ["Seller debit / buyer credit of $2,880", "Seller credit / buyer debit of $2,880",
   "Seller debit / buyer credit of $1,440", "Seller credit / buyer debit of $1,440"], 0,
  "Unpaid taxes reverse the direction",
  "Eight months elapsed x $360/month = $2,880 the seller owes. Because the bill is UNPAID and the buyer will pay it all later, the seller is debited and the buyer credited. Prepaid taxes would reverse both signs."),
Q("closing-math",
  "A buyer assumes the seller's loan with a $312 accrued interest balance owed for the current month. At closing this is:",
  ["A seller debit and buyer credit", "A buyer debit and seller credit",
   "A debit to both", "Not entered on the statement"], 0,
  "Accrued interest on an assumed loan",
  "Mortgage interest is paid in ARREARS, so the seller has used the money but not yet paid the interest. The seller is debited and the buyer credited, because the buyer will make the payment covering that period."),
Q("closing-math",
  "A tenant's $1,500 security deposit on a property being sold is handled at closing as:",
  ["A seller debit and buyer credit", "A buyer debit and seller credit",
   "Returned to the tenant", "Not shown on the statement"], 0,
  "Security deposits transfer with the property",
  "The deposit belongs to the tenant, and the new owner inherits the obligation to return it. So the seller is debited and the buyer credited. The tenant is not paid at closing -- the duty simply moves to the buyer."),
Q("closing-math",
  "A seller has prepaid a $960 annual insurance policy the buyer will assume, with 5 months remaining. The entry is:",
  ["Seller credit and buyer debit of $400", "Seller debit and buyer credit of $400",
   "Seller credit and buyer debit of $560", "No entry -- policies do not transfer"], 0,
  "Prepaid items reimburse the seller",
  "$960 / 12 = $80 per month x 5 remaining = $400 of coverage the buyer will enjoy but the seller paid for. The seller is reimbursed: seller CREDIT, buyer DEBIT. Prepaid always runs the opposite direction from unpaid."),
Q("closing-math",
  "A buyer's loan is $240,000 with a 1% origination fee and $1,850 in other lender charges. The buyer's total lender debits are:",
  ["$1,850", "$2,400", "$4,250", "$24,000"], 2,
  "Reading loan charges together",
  "Origination = 1% x $240,000 = $2,400. Plus $1,850 in other charges = $4,250 debited to the buyer. The origination fee is a percentage of the LOAN, not the sale price -- the same trap as discount points."),
Q("closing-math",
  "Which item is normally a credit to the BUYER on a settlement statement?",
  ["The new loan amount", "The sale price", "The broker's commission", "Recording the deed"], 0,
  "The new loan is buyer money",
  "The lender's funds are applied toward what the buyer owes, so the new loan is a buyer CREDIT. The sale price is a buyer debit; commission is normally a seller debit; recording fees are typically buyer debits."),
Q("closing-math",
  "A Georgia sale closes at $415,000. The transfer tax the seller is debited is:",
  ["$41.50", "$415", "$4,150", "$415,000"], 1,
  "Georgia transfer tax on the statement",
  "$1.00 per $1,000 of consideration: $415,000 / 1,000 = 415, so $415. It is customarily a SELLER debit and is collected by the clerk of superior court when the deed is recorded."),
Q("closing-math",
  "A seller's gross proceeds are $340,000 with total debits of $221,400. The seller's net at closing is:",
  ["$118,600", "$221,400", "$561,400", "$340,000"], 0,
  "Reading the bottom line",
  "Seller credits minus seller debits: $340,000 - $221,400 = $118,600 walking-away money. Every proration and payoff feeds one of those two columns, which is why direction matters more than arithmetic."),
Q("closing-math",
  "Rent of $2,100 for a 30-day month was collected by the seller on the 1st. Closing is on the 11th, with the buyer owning from closing day. The entry is:",
  ["Seller debit / buyer credit of $1,400", "Seller credit / buyer debit of $1,400",
   "Seller debit / buyer credit of $700", "No entry required"], 0,
  "Rent runs opposite to taxes",
  "Days 11 through 30 = 20 days x $70/day = $1,400 belonging to the buyer. The seller is holding the cash, so the seller is DEBITED and the buyer credited -- the reverse of an unpaid tax proration."),
]
