# -*- coding: utf-8 -*-
"""Exam-realistic tier: the comprehensive subtest."""

def Q(topic, q, choices, answer, concept, explain):
    return {"topic": "comp/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain, "difficulty": 3}

ROWS = [
Q("vocabulary",
  "A judgment is entered against a property owner. The resulting lien is BEST classified as:",
  ["General, involuntary, and statutory", "Specific, involuntary, and equitable",
   "General, voluntary, and statutory", "Specific, voluntary, and statutory"], 0,
  "Liens sort on three independent axes at once",
  "A judgment attaches to all of the debtor's property (general), was imposed rather than agreed (involuntary), and arises from statute (statutory). A mortgage by contrast is specific and voluntary."),
Q("vocabulary",
  "Which pairing is correct?",
  ["Avulsion adds land gradually; accretion changes boundaries suddenly",
   "Accretion adds land gradually and moves the boundary; avulsion is sudden and does not",
   "Reliction is the sudden loss of land to water",
   "Erosion exposes land as water recedes"], 1,
  "Four water terms that are constantly swapped",
  "Accretion is gradual deposit and the boundary follows it; the deposited soil is alluvion. Avulsion is sudden and boundaries stay put. Erosion is gradual loss; reliction is land exposed by permanently receding water."),
Q("vocabulary",
  "A borrower cures a default two weeks before the scheduled foreclosure sale. The right exercised is the:",
  ["Statutory right of redemption", "Equitable right of redemption",
   "Right of reinstatement under the alienation clause", "Defeasance right"], 1,
  "The dividing line is the sale itself",
  "The EQUITABLE right runs from default up to the moment of sale. A STATUTORY right, where a state provides one, runs for a period AFTER the sale. Defeasance is the clause requiring release of the lien on payoff."),

Q("situational",
  "At closing you notice the settlement statement omits a $1,900 repair credit your buyer client negotiated. The closing attorney says the figures came from the lender and everyone is ready to sign. You should:",
  ["Sign and request a post-closing correction",
   "Raise it immediately, before any signatures, and have the statement corrected",
   "Advise your client privately to sign and pursue the seller later",
   "Defer to the attorney, who supervises the closing"], 1,
  "Speak while it can still be fixed",
  "You have actual knowledge the figure is wrong and a duty of reasonable care to your client. Deference to the attorney is no defence, and post-closing corrections are far harder to obtain. Raise it before anyone signs."),
Q("situational",
  "A buyer client asks you to write an offer at $415,000 with a $15,000 'renovation credit' returned at closing, so the loan covers more. The seller is willing. You should:",
  ["Write it, since both parties agree",
   "Refuse - concealing the arrangement from the lender is mortgage fraud",
   "Write it and disclose it only if the lender asks",
   "Suggest a smaller credit to stay under the lender's threshold"], 1,
  "Inflated price with cash back is loan fraud when concealed",
  "The lender is advancing money against a price that does not reflect the real bargain. If every term is fully disclosed to the lender the deal can be structured legitimately; concealed, it is fraud, and the licensee who writes it participates."),
Q("situational",
  "Three months after closing you discover you miscalculated a proration and your buyer client overpaid the seller by $620. Nobody has noticed. You should:",
  ["Say nothing, since the closing is final",
   "Tell your client promptly and work to correct it",
   "Quietly reimburse the $620 from your own funds",
   "Wait to see whether the seller raises it"], 1,
  "Accounting survives the closing",
  "The duty to account does not end at the table. Disclosing your own error is uncomfortable but it is the duty, and errors-and-omissions cover exists for exactly this. Silent reimbursement hides the error from the person entitled to know."),

Q("grec-deep",
  "Which sequence correctly states Georgia's education requirements for a salesperson?",
  ["25-hour prelicense, 75-hour postlicense within one year, 36 hours CE per four years",
   "75-hour prelicense, 25-hour postlicense within one year, 24 hours CE per four-year renewal",
   "60-hour prelicense, 25-hour postlicense within two years, 24 hours CE annually",
   "75-hour prelicense, 24 hours CE annually, no postlicense requirement"], 1,
  "The three stages and their numbers",
  "75 hours before licensure, 25 hours of postlicense inside the first year, then at least 24 hours of CE per FOUR-YEAR renewal period. The 75 and 25 are commonly transposed and the CE figure is commonly misquoted as 36, which is another state."),
Q("grec-deep",
  "A Georgia broker maintains separate trust accounts for earnest money, rents and security deposits. Which statement is TRUE?",
  ["Only the earnest money account must be registered with GREC",
   "Each account must be bank-designated as trust or escrow and registered with the Commission, with the broker holding signatory power",
   "Multiple trust accounts are prohibited",
   "Separate accounts are permitted only for firms with more than ten licensees"], 1,
  "Multiple accounts are fine; each must be set up properly",
  "A broker must have at least one and may have several. Every one must be designated as trust or escrow by the BANK, registered with GREC on Commission forms, and carry the broker's signatory power."),

Q("closing-math",
  "A settlement statement shows the following for the seller: sale price $392,000; loan payoff $214,600; commission 6%; other seller costs $2,850; unpaid taxes prorated to the seller $1,940. The seller's net proceeds are:",
  ["$149,090", "$151,030", "$147,150", "$156,470"], 0,
  "Every debit comes off the price",
  "Commission = 6% x $392,000 = $23,520. Seller debits = $214,600 + $23,520 + $2,850 + $1,940 = $242,910. $392,000 - $242,910 = $149,090. Forgetting the tax proration gives $151,030."),
Q("closing-math",
  "Which of these appears as a CREDIT to the buyer on a settlement statement?",
  ["The sale price", "The new loan amount",
   "Recording the deed", "The origination fee"], 1,
  "Whose money reduces what the buyer owes",
  "The lender's funds are applied against what the buyer owes, so the new loan is a buyer credit - as is earnest money already deposited. The sale price, recording fees and origination charges are all buyer debits."),
]
