# -*- coding: utf-8 -*-
"""Exam-realistic tier: the Georgia state portion.

Grounded in the GREC InfoBase and the code it quotes. Georgia is where this
candidate is weakest and where the state portion is passed or failed on its
own, so these lean on the distinctions Georgia actually turns on.
"""

def Q(topic, q, choices, answer, concept, explain):
    return {"topic": "georgia/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain, "difficulty": 3}

ROWS = [
# -------------------------------------------------------------- license law
Q("license-law",
  "A Georgia salesperson licensed 10 months ago has completed 9 hours of continuing education but not the postlicense course. She plans to finish the postlicense course in month 14. Which is TRUE?",
  ["She is compliant, since the postlicense course is due within two years",
   "Her licence will lapse; the 25-hour postlicense course is due within one year and CE does not substitute",
   "The CE hours count toward the postlicense requirement",
   "She may request a six-month extension from GREC"], 1,
  "The postlicense deadline is absolute",
  "The 25-hour Sales Post-license Course is due within ONE year of original licensure, applies whether active or inactive, and CE hours do not count toward it. Missing the deadline costs the licence."),
Q("license-law",
  "A consumer files a sworn complaint alleging a Georgia broker mishandled $22,000 of escrow funds. Following investigation the Commission finds a violation. Which outcome is OUTSIDE GREC's authority?",
  ["Revoking the broker's licence",
   "Ordering the broker to repay the consumer the $22,000",
   "Imposing a fine and requiring additional education",
   "Requiring an independent accountant's report on the trust account"], 1,
  "GREC disciplines; it does not award money",
  "GREC may reprimand, suspend, revoke, fine, require education, and require accountant reports. It has no restitution power - the consumer must sue civilly, and should not wait for the disciplinary case to conclude."),
Q("license-law",
  "An applicant held an active Alabama broker's licence for four of the past five years, has never been licensed in Georgia, and now applies for a Georgia broker's licence. Regarding EXPERIENCE, the applicant:",
  ["Must first hold a Georgia salesperson's licence for three years",
   "Satisfies the requirement, on filing a certified licence history from Alabama",
   "Cannot qualify, because out-of-state experience does not count",
   "Must complete an additional year of Georgia experience"], 1,
  "Out-of-state active licensure counts in Georgia",
  "Georgia requires three of the five years immediately preceding application in ACTIVE status, and active licensure in another state qualifies. The applicant must supply a certified licence history from every state where they have held a licence."),
Q("license-law",
  "A Georgia licensee lists and sells a rental duplex she owns personally, using her own brokerage. Which is REQUIRED?",
  ["She must transfer title to the brokerage before listing",
   "She must disclose her licensed status in writing in the contract and place trust funds in a broker-approved account",
   "Nothing - an owner selling her own property is exempt from the licence law",
   "She must engage an unaffiliated broker to represent the buyer"], 1,
  "Exceptions to licensure never apply to a licensee",
  "O.C.G.A. 43-40-29(c) provides that none of the exceptions to licensure applies to a person holding a licence. Written disclosure of licensed status and broker-approved handling of trust funds are both required."),

# ------------------------------------------------------------------ BRRETA
Q("brreta",
  "A Georgia broker assigns Licensee A to the seller and Licensee B to the buyer in the same transaction, with both clients' written consent. Licensee A learns from the seller that she will accept $18,000 less. Which is TRUE?",
  ["The broker becomes a dual agent and must disclose the figure to both sides",
   "Licensee A may share the figure only with the broker, and neither may reveal it to Licensee B or the buyer",
   "Licensee B is deemed to know the figure, because both work for the same firm",
   "The information must be disclosed as an adverse material fact"], 1,
  "Designated agency: no dual agency and no imputed knowledge",
  "O.C.G.A. 10-6A-13(b) says neither the broker, the licensees, nor the firm is deemed a dual agent. Subsection (c) removes imputation of knowledge between them, and confidential information may go only to the broker, who may not reveal it. A negotiating position is confidential, not an adverse material fact."),
Q("brreta",
  "A Georgia buyer works with a licensee for six weeks. The licensee arranges showings, advises on offer strategy, and is ultimately paid from the seller's commission at closing. No written agreement was ever signed. Under BRRETA the licensee:",
  ["Was the buyer's agent, created by conduct and confirmed by payment",
   "Had no agency relationship with the buyer, because agency requires written authority",
   "Was the seller's subagent by operation of law",
   "Became a dual agent when paid from the seller's proceeds"], 1,
  "Written authority is the whole point of BRRETA",
  "BRRETA defines agency as representation by the client's WRITTEN authority, and states that paying compensation does not by itself create an engagement. There was no agency - which is exactly the accidental-agency problem the Act was passed to prevent. The conduct is still a liability risk."),
Q("brreta",
  "Before entering a brokerage engagement with a prospective seller, a Georgia broker must advise the seller of all of the following EXCEPT:",
  ["The types of agency relationships available through the broker",
   "That the broker also represents three other sellers in the same subdivision",
   "The broker's compensation and whether it will be shared",
   "The broker's obligations to keep information confidential"], 1,
  "The four disclosures, and what they expressly exclude",
  "BRRETA requires disclosure of agency types available, conflicting relationships actually known, compensation and sharing, and confidentiality obligations - but EXPRESSLY excludes having to reveal that the broker represents other sellers or landlords generally."),

# ----------------------------------------------------------- trust accounts
Q("trust-accounts",
  "A Georgia buyer's offer states the broker will hold the earnest money check uncashed until the seller accepts. The seller has not yet seen the offer. The broker may:",
  ["Hold the check, because the stipulation is in the offer the buyer signed",
   "Hold the check only once the seller has also agreed to that stipulation in writing",
   "Hold the check for up to three banking days without any authority",
   "Not hold the check under any circumstances"], 1,
  "Written authority means ALL parties",
  "Trust funds are deposited promptly unless clear written authority from all parties says otherwise. Until the seller accepts - including that stipulation - there is no agreement of all parties, so the broker cannot rely on it."),
Q("trust-accounts",
  "A Georgia broker's trust account is at First Bank. A client already holds $250,000 in personal deposits at First Bank and gives the broker a $12,000 earnest money deposit. First Bank fails. Which is TRUE?",
  ["Pass-through coverage insures the $12,000 as a separate account",
   "The $12,000 is uninsured, and the broker may be liable if the client was never told which bank holds trust funds",
   "The broker's own FDIC coverage protects the deposit",
   "The client's personal deposits are reduced pro rata"], 1,
  "The limit of FDIC pass-through coverage",
  "Pass-through treats each client as a separate owner, but the FDIC AGGREGATES that person's deposits at the same institution against the $250,000 cap. The InfoBase warns the broker may be liable for the uninsured excess where the bank and the limitation were not disclosed."),

# ------------------------------------------------------------- GA contracts
Q("contracts",
  "A Georgia seller signs a buyer's offer Monday at 2 p.m. The listing agent notifies the buyer's agent Wednesday at 9 a.m. The contract gives the buyer a 10-day due diligence period. That period expires at the end of:",
  ["The following Wednesday", "The following Monday",
   "Ten business days from Monday", "The date the contract is recorded"], 0,
  "Everything runs from the binding agreement date",
  "The binding agreement date is when acceptance is COMMUNICATED - Wednesday, not Monday. Ten days from Wednesday ends the following Wednesday. Counting from the signature date shifts every deadline in the contract by two days."),
Q("contracts",
  "A Georgia licensee types a special stipulation giving the buyer the right to terminate 'if financing is not obtained on satisfactory terms.' The preprinted form contains a specific financing contingency with a stated rate ceiling. The buyer later terminates citing a rate he dislikes. Which is TRUE?",
  ["The preprinted contingency controls, because it is more specific",
   "The typed stipulation controls, and its vagueness now works against the seller",
   "The contract is void for ambiguity",
   "GREC must interpret the conflicting terms"], 1,
  "Typed terms beat preprinted ones - which is why drafting them is dangerous",
  "Handwritten and typed additions reflect the parties' specific intent and prevail over the preprinted text. A vague stipulation therefore governs, giving the buyer wide latitude. This is precisely why composing original clauses edges into the unauthorised practice of law."),

# ---------------------------------------------------------- GA disclosures
Q("disclosures",
  "A Georgia buyer asks a listing agent directly whether the previous owner died in the house. The agent knows he did, of natural causes. The agent should:",
  ["Confirm it, since the buyer asked directly",
   "Deny it, since Georgia does not require disclosure",
   "Decline to answer and refer the buyer to sources they can research",
   "Answer only after obtaining the seller's written permission"], 2,
  "Nondisclosure is protected; a denial is not",
  "Georgia shields licensees from liability for NOT disclosing a death, homicide, suicide or felony on the property. That protects silence, not a false statement. Denying it would be misrepresentation; declining keeps the licensee inside the protection."),

# ----------------------------------------------------------- GA procedures
Q("procedures",
  "A Georgia buyer at closing asks the closing attorney whether the contract's repair addendum protects him. Which response by the licensee is correct?",
  ["Let the attorney advise the buyer, since the attorney is neutral",
   "Explain that the attorney customarily represents the lender and the buyer may retain his own counsel",
   "Summarise the addendum's legal effect for the buyer",
   "Postpone the closing until the buyer obtains counsel"], 1,
  "Who the Georgia closing attorney actually represents",
  "Georgia requires attorney supervision of closings, and that attorney customarily represents the LENDER, not the buyer. The licensee must not supply a legal opinion either. Saying so plainly is the correct move; the buyer decides whether to delay."),
Q("procedures",
  "A Georgia property sells for $486,500. Regarding the transfer tax, which is TRUE?",
  ["The buyer pays $486.50 at recording",
   "The seller customarily pays approximately $487, collected by the clerk of superior court",
   "The tax is 1% of the price, or $4,865",
   "No transfer tax applies to residential sales"], 1,
  "Georgia transfer tax: rate, payer, and collector",
  "The rate is $1.00 per $1,000 of consideration - $486,500 / 1,000 = about $487. It is customarily a SELLER expense and is collected by the clerk of superior court when the deed is recorded."),

# --------------------------------------------------------- GA fair housing
Q("fair-housing",
  "A Georgia landlord requires a $400 refundable pet deposit from all tenants with animals, applied uniformly. A tenant with a documented assistance animal objects. The landlord's position is:",
  ["Correct, because the policy is applied to everyone equally",
   "Incorrect - an assistance animal is not a pet and no pet deposit may be charged",
   "Correct, because the deposit is refundable",
   "Incorrect only if the tenant's disability is visible"], 1,
  "Waiving the pet policy is the accommodation",
  "Uniform application is no defence where the rule itself must be waived as a reasonable accommodation. No pet fee or deposit, refundable or not, may be charged for an assistance animal - though the tenant remains liable for actual damage the animal causes."),
]
