# -*- coding: utf-8 -*-
"""Exam-realistic tier, national B: disclosures, contracts, transfer, practice, math."""

def Q(topic, q, choices, answer, concept, explain):
    return {"topic": "national/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain, "difficulty": 3}

ROWS = [
# --------------------------------------------------------------- disclosures
Q("disclosures",
  "A seller of a 1974 home tells the listing agent there is no lead paint, having never tested. The buyer waives the 10-day testing opportunity in writing. Which statement is TRUE?",
  ["The disclosure requirement is satisfied only if the seller tests before closing",
   "The seller must still provide the disclosure form and EPA pamphlet, and the buyer may waive the testing period",
   "The waiver removes the seller's disclosure obligation entirely",
   "The agent must order a lead inspection at the seller's expense"], 1,
  "What is waivable under the lead rule and what is not",
  "The seller is never required to TEST. The disclosure form, any records, and the EPA pamphlet are mandatory for pre-1978 housing and cannot be waived. Only the 10-day opportunity to test is waivable, and the buyer may do that in writing."),
Q("disclosures",
  "During a walkthrough a buyer's agent notices a fresh drywall patch on a ceiling directly beneath an upstairs bathroom. The seller's disclosure reports no plumbing problems. The agent should:",
  ["Say nothing, since the seller's disclosure governs",
   "Point out the patch to the buyer and recommend the inspector examine it",
   "Ask the listing agent to amend the seller's disclosure",
   "Advise the buyer to terminate the contract"], 1,
  "No duty to discover, but no licence to ignore",
  "Agents need not investigate, but must pass on what they actually observe. Flagging it and routing it to the inspector is the duty; you neither alter the seller's form nor push the buyer to terminate over a suspicion."),

# ---------------------------------------------------------------- contracts
Q("contracts",
  "A buyer's written offer states it expires at 6:00 p.m. Tuesday. At 4:00 p.m. Tuesday the seller signs and hands the acceptance to the listing agent, who delivers it to the buyer's agent at 7:30 p.m. At 5:00 p.m. Tuesday, before any delivery, the buyer had phoned the listing agent revoking the offer. Which is TRUE?",
  ["A contract formed at 4:00 p.m. when the seller signed",
   "No contract formed, because the offer was revoked before acceptance was communicated",
   "A contract formed at 7:30 p.m. because the seller signed within the deadline",
   "The revocation is ineffective because it was not in writing"], 1,
  "Revocation is effective on communication, and beats an undelivered acceptance",
  "An offer may be revoked any time before acceptance is COMMUNICATED to the offeror, and revocation itself takes effect when communicated. The buyer revoked at 5:00; the acceptance was not delivered until 7:30. Signing at 4:00 changed nothing, and revocation need not be written."),
Q("contracts",
  "A contract contains a liquidated damages clause fixing the seller's remedy at the $25,000 earnest money on a $300,000 home. The buyer defaults and the seller resells three weeks later for $305,000. The seller sues for the earnest money. The buyer's strongest argument is that:",
  ["Liquidated damages clauses are unenforceable in real estate",
   "The clause operates as a penalty, since the seller suffered no loss",
   "The seller must first prove actual damages",
   "The clause fails because it exceeds 5% of the price"], 1,
  "Liquidated damages must estimate loss, not punish",
  "A clause is enforceable only as a reasonable pre-estimate of hard-to-determine loss. Where the seller resold at a higher price weeks later, retaining $25,000 looks punitive, which is the classic ground for voiding it. There is no fixed percentage rule, and such clauses are certainly enforceable in principle."),
Q("contracts",
  "Which of the following would render a real estate sales contract VOID rather than voidable?",
  ["The seller was 17 years old at signing",
   "The buyer was induced by the seller's fraudulent statement about the septic system",
   "The stated purpose is to operate an unlicensed gambling house",
   "The seller signed under significant time pressure from the buyer's agent"], 2,
  "Void versus voidable",
  "An unlawful object means no contract ever existed - void. A minor's contract and one induced by fraud are VOIDABLE at the protected party's election. Time pressure alone is not duress."),

# ----------------------------------------------------------------- transfer
Q("transfer",
  "A owns land and conveys to B by general warranty deed; B does not record. A then conveys the same land to C, who pays value, has no knowledge of B, and records immediately. B moved onto the land and has been living there openly since the first conveyance. In a race-notice state, who prevails?",
  ["C, because C recorded first without actual knowledge",
   "B, because B's open possession was constructive notice to C",
   "A, because the second conveyance was fraudulent",
   "C, because a general warranty deed must be recorded to be valid"], 1,
  "Possession as constructive notice",
  "Race-notice protects a later buyer who takes WITHOUT NOTICE and records first. C recorded first but B's open, visible possession put C on constructive notice - a buyer is charged with what an inspection of the land would reveal. So C fails the notice half of the test."),
Q("transfer",
  "A title commitment lists as exceptions: a recorded utility easement, an unreleased 1996 mortgage, and rights of parties in possession. The seller must clear which of these to deliver marketable title?",
  ["All three", "The unreleased mortgage only",
   "The mortgage and the easement", "None - exceptions are standard"], 1,
  "Which exceptions actually defeat marketable title",
  "A recorded utility easement is a common encumbrance a buyer normally takes subject to, and 'rights of parties in possession' is a standard survey-type exception. An undischarged mortgage of record is a lien that must be released, and title insurance will not cover it because it is excepted."),

# ----------------------------------------------------------------- practice
Q("practice",
  "A property manager applies a policy of refusing all applicants with any criminal record. Which statement BEST describes the fair housing exposure?",
  ["None, because criminal history is not a protected class",
   "It may create disparate impact liability even without discriminatory intent",
   "It is lawful only if applied to every applicant equally",
   "It violates the Fair Housing Act on its face"], 1,
  "Disparate impact on a facially neutral policy",
  "Criminal history is not itself protected, and uniform application is no defence. A blanket ban falls disproportionately on protected classes, so it can create disparate impact liability. HUD guidance expects an individualised assessment rather than a blanket rule."),
Q("practice",
  "Two competing brokerages' owners meet for lunch and agree not to send referrals to a discount brokerage that recently entered the market. This is:",
  ["A lawful business decision by independent firms",
   "A group boycott, a per se antitrust violation",
   "Market allocation", "Price fixing"], 1,
  "Naming the antitrust violation precisely",
  "Competitors agreeing to refuse to deal with another firm is a GROUP BOYCOTT. Market allocation divides territories or customers; price fixing sets prices. All are per se violations, but the exam expects the right label."),
Q("practice",
  "A broker holds a $15,000 earnest money deposit. The transaction collapses and both parties make written demand. The contract's dispute clause is silent. The broker should:",
  ["Release the funds to the party whose demand arrived first",
   "Continue holding the funds and file an interpleader action",
   "Divide the funds equally and obtain releases",
   "Return the deposit to the buyer, who supplied it"], 1,
  "A stakeholder does not adjudicate",
  "Releasing, splitting, or defaulting to the buyer all substitute the broker's judgement for a court's and invite a conversion claim. Holding and interpleading - or following the state's prescribed procedure - is the safe course."),

# --------------------------------------------------------------------- math
Q("math",
  "A seller must net $265,000 after paying a 6% commission, $3,400 in seller closing costs, and an existing loan payoff of $118,000. What must the property sell for?",
  ["$411,064", "$409,900", "$386,400", "$400,000"], 0,
  "Everything the seller must clear goes above the line before dividing",
  "The seller must clear $265,000 + $3,400 + $118,000 = $386,400. That is the 94% remaining after a 6% commission. $386,400 / 0.94 = $411,063.83. Note the payoff belongs in the amount to be cleared; leaving it out gives $286,596."),
Q("math",
  "Closing is 15 September. Annual taxes of $5,400 are unpaid. September rent of $1,800 was collected by the seller on the 1st. Using a 360-day year, with the seller responsible through 14 September and the buyer owning from closing day, what is the seller's TOTAL debit for these two items?",
  ["$4,770", "$3,810", "$2,850", "$960"], 0,
  "Unpaid taxes and collected rent both debit the seller",
  "Taxes: $5,400 / 360 = $15 a day. The seller owns 1 January through 14 September = 8 full months (240 days) + 14 = 254 days. 254 x $15 = $3,810, debited to the seller because the buyer will pay the whole bill. Rent: $1,800 / 30 = $60 a day. The buyer owns the 15th through the 30th = 16 days x $60 = $960, which the seller is holding, so it is also a seller debit. $3,810 + $960 = $4,770."),
]
