# -*- coding: utf-8 -*-
"""Exam-realistic tier, national A: ownership, land use, valuation, financing, agency.

Written to sit at PSI difficulty: fact-dense stems, four options of similar
weight where more than one is a true statement, and a fine distinction doing
the work. Several require two steps.
"""

def Q(topic, q, choices, answer, concept, explain):
    return {"topic": "national/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain, "difficulty": 3}

ROWS = [
# ---------------------------------------------------------------- ownership
Q("ownership",
  "A grants Blackacre 'to B for life, then to C and her heirs.' B mortgages her interest, then dies with the loan unpaid. Which statement is TRUE?",
  ["C takes the property subject to the mortgage, which survives B's death",
   "C takes free of the mortgage, because B's interest ended at her death",
   "The lender may foreclose against C to satisfy the debt",
   "C must assume the loan to perfect her remainder"], 1,
  "A life tenant can only encumber what they own",
  "B held a life estate, so the mortgage attached only to that estate. When B died the life estate ended and the lien died with it. C's remainder was never encumbered, so the lender's security is gone and it must pursue B's estate on the note."),
Q("ownership",
  "Four siblings own a cabin as joint tenants. One conveys her interest to a friend; a second then dies intestate. Immediately afterward, how is title held?",
  ["The friend owns 1/4 as a tenant in common; the two surviving siblings own 3/4 as joint tenants",
   "All three owners hold as tenants in common in equal shares",
   "The friend owns 1/3 and the surviving siblings 1/3 each, all as tenants in common",
   "The deceased sibling's share passes to her heirs as a tenancy in common interest"], 0,
  "Severance affects only the conveyed share",
  "The conveyance severed only that 1/4, making the friend a tenant in common. The other three remained joint tenants among themselves, so when one died her share passed by survivorship to the remaining two, giving them 3/4 jointly. Nothing passed to her heirs."),
Q("ownership",
  "A tenant installs shelving, a walk-in cooler, and a custom sign at a leased bakery. The lease says nothing about removal. On the last day of the term the tenant removes the cooler and sign but leaves the shelving bolted in place. Which is TRUE?",
  ["All three were trade fixtures and the tenant forfeited only the shelving",
   "None were trade fixtures because they were annexed to the realty",
   "The landlord may sue for the value of the cooler and sign",
   "The tenant may return within a reasonable time to remove the shelving"], 0,
  "Trade fixtures must be removed before the term ends",
  "All three were installed to conduct business, so all three were trade fixtures. The right to remove them expires with the lease. By leaving the shelving past the term the tenant abandoned it to the landlord; removing the other two in time was proper."),
Q("ownership",
  "A condominium declaration allocates a unit 2.5% of the common elements. The association levies a special assessment of $400,000 for roof replacement. The unit owner's share is:",
  ["$10,000", "$4,000", "$1,000", "Determined by unit square footage"], 0,
  "The common-element percentage drives assessments",
  "$400,000 x 2.5% = $10,000. The percentage in the declaration governs both assessments and usually voting weight, and it cannot be separated from the unit or renegotiated by an individual owner."),

# ----------------------------------------------------------------- land use
Q("landuse",
  "A parcel is zoned for single-family use. Recorded subdivision covenants limit structures to one story. The owner obtains a variance from the city permitting a two-story home. Which is TRUE?",
  ["The variance overrides the covenant because zoning is superior to private agreement",
   "The owner may still be enjoined by a neighbouring lot owner enforcing the covenant",
   "The covenant is void once a public body grants relief",
   "The city must join the covenant holders before issuing the variance"], 1,
  "Public relief does not defeat private restrictions",
  "Zoning and covenants operate independently, and the more restrictive controls. A variance only removes the government's objection; any benefited lot owner may still sue to enforce the one-story covenant."),
Q("landuse",
  "A city adopts an ordinance barring all construction on a wetland parcel to protect a watershed. The owner had bought it to build a single home and it now has no other use. The owner's best claim is that the ordinance is:",
  ["Spot zoning, because it targets one parcel",
   "A regulatory taking, because it denies all economically viable use",
   "Void, because police power cannot restrict private land",
   "An improper exercise of eminent domain without condemnation"], 1,
  "Where police power crosses into a taking",
  "Denial of ALL economically viable use is the line. That is a regulatory taking, pursued as inverse condemnation with just compensation. It is not spot zoning (which benefits an owner inconsistently with the plan), and police power certainly can restrict land - just not to that degree without paying."),

# ---------------------------------------------------------------- valuation
Q("valuation",
  "An appraiser must value a 6-unit apartment building. Comparable buildings sold recently, the property is fully leased, and construction costs are well documented. Which approach should be given the MOST weight, and why?",
  ["Cost, because the improvements dominate the value",
   "Income, because a buyer of this property is buying an income stream",
   "Sales comparison, because recent comparable sales exist",
   "An average of all three, since all the data is available"], 1,
  "Weighting follows how buyers actually behave",
  "Reconciliation weights by reliability for that property type, and investment property is bought for its income. Sales comparison supports the conclusion and cost serves as a check, but income leads. Averaging the three is never correct."),
Q("valuation",
  "A property produces $96,000 potential gross income. Vacancy runs 8%, operating expenses are $31,000, annual debt service is $28,000, and the owner spent $15,000 on a new roof this year. Using a 7.5% capitalization rate, the indicated value is closest to:",
  ["$766,000", "$393,000", "$573,000", "$1,053,000"], 0,
  "What belongs in NOI and what does not",
  "$96,000 - 8% vacancy ($7,680) = $88,320 effective gross. Less $31,000 operating expenses = $57,320 NOI. Debt service and the capital roof replacement are BOTH excluded. $57,320 / 0.075 = $764,267, closest to $766,000."),
Q("valuation",
  "A subject home has 2,000 sq ft and no garage. A comparable with 2,200 sq ft and a two-car garage sold for $415,000. Living area adjusts at $60 per sq ft and the garage at $18,000. The adjusted indication is:",
  ["$385,000", "$445,000", "$409,000", "$421,000"], 0,
  "Two adjustments in the same direction",
  "The comp is superior on both counts, so both come off. Size: 200 sq ft x $60 = $12,000. Garage: $18,000. $415,000 - $12,000 - $18,000 = $385,000. Adding either one back gives the distractors."),

# ---------------------------------------------------------------- financing
Q("financing",
  "A buyer purchases at $340,000 with an 80% conventional loan, pays 1.5 discount points and a 1% origination fee, and has already deposited $6,000 in earnest money. Ignoring prorations and all other costs, how much must the buyer bring to closing?",
  ["$68,800", "$74,800", "$62,800", "$80,800"], 0,
  "Points and origination are percentages of the LOAN, and earnest money is a credit",
  "Loan = 80% x $340,000 = $272,000, so the down payment is $68,000. Points = 1.5% x $272,000 = $4,080. Origination = 1% x $272,000 = $2,720. Debits total $74,800. The $6,000 already on deposit is a buyer credit, so $74,800 - $6,000 = $68,800 to bring. $74,800 is the figure before crediting the deposit."),
Q("financing",
  "A borrower assumes an existing loan with the lender's written consent, and the lender releases the seller from liability. This arrangement is BEST described as:",
  ["An assumption creating secondary liability in the seller",
   "A novation",
   "Taking title subject to the loan",
   "A wraparound arrangement"], 1,
  "Assumption plus release equals novation",
  "Assumption alone leaves the seller secondarily liable. The lender's RELEASE is what makes it a novation - a new party substituted and the original discharged. 'Subject to' would mean the buyer accepted no liability at all."),
Q("financing",
  "Under TRID, a lender issues a Closing Disclosure showing a 6.125% APR. Two days before consummation the loan changes from a 30-year fixed to a 5/1 ARM at the same APR. The lender must:",
  ["Provide a corrected disclosure at consummation only",
   "Provide a corrected Closing Disclosure and observe a new three-business-day waiting period",
   "Do nothing, because the APR is unchanged",
   "Issue a new Loan Estimate instead"], 1,
  "The three triggers that restart the CD clock",
  "The clock restarts for an APR inaccurate beyond tolerance, a change in LOAN PRODUCT, or the addition of a prepayment penalty. Fixed to ARM is a product change, so the waiting period runs again even though the APR held steady."),
Q("financing",
  "A lender denies a mortgage application. Under ECOA the applicant is entitled to:",
  ["A statement of specific reasons, or notice of the right to request them within 60 days",
   "A statement of specific reasons only if the applicant is in a protected class",
   "The lender's underwriting guidelines on request",
   "A second review by a different underwriter"], 0,
  "ECOA adverse action applies to everyone",
  "The notice requirement runs to every rejected applicant regardless of protected class - it is not itself a discrimination test. The applicant is not entitled to internal guidelines or a second review."),

# ------------------------------------------------------------------- agency
Q("agency",
  "A listing broker learns that the seller's roof leaks, that the seller is divorcing and must sell quickly, and that a neighbouring lot has been rezoned for a convenience store. A buyer customer asks about the property. The broker must disclose:",
  ["All three facts", "The roof and the rezoning, but not the divorce",
   "The roof only", "The roof and the divorce, but not the rezoning"], 1,
  "Material facts versus client confidences",
  "The roof is a material defect and the rezoning materially affects value and desirability - both must be disclosed even to a customer. The divorce is the seller's motivation, which is confidential and would damage the client's bargaining position."),
Q("agency",
  "A salesperson affiliated with Broker X shows her own listing to a buyer who has signed a buyer agency agreement with Broker Y. During negotiations the buyer asks the salesperson what the seller would accept. The salesperson should:",
  ["Answer, since the buyer is represented by another firm",
   "Decline, because she represents the seller and the information is confidential",
   "Answer only what is in the MLS",
   "Refer the question to Broker Y"], 1,
  "Duties run to your client, not to who else is in the room",
  "The buyer having their own agent changes nothing about the listing salesperson's loyalty and confidentiality to the seller. Declining is correct; referring the question elsewhere does not make disclosure acceptable."),
]
