# -*- coding: utf-8 -*-
"""Georgia bank, part B: contracts, disclosures, closing procedure, fair housing."""

def Q(topic, q, choices, answer, concept, explain):
    return {"topic": "georgia/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain}

ROWS = [
# ------------------------------------------------------------ GA contracts
Q("contracts",
  "In Georgia, a real estate sales contract becomes binding when:",
  ["The offer is signed by the buyer", "Acceptance is communicated to the offeror",
   "The earnest money is deposited", "The contract is recorded"], 1,
  "Formation of the binding agreement",
  "Georgia measures deadlines from the 'binding agreement date' -- the date acceptance is communicated back to the offeror. Signing alone does not bind; the other party must be notified."),
Q("contracts",
  "A Georgia real estate sales contract must contain a legal description sufficient to:",
  ["Impress the lender", "Identify the property with reasonable certainty",
   "Match the tax assessor's value", "Satisfy the MLS"], 1,
  "Georgia description requirements",
  "Georgia courts require a description that identifies the land or provides a 'key' leading to identification. A vague description can make the contract unenforceable for lack of definiteness."),
Q("contracts",
  "Under Georgia law, who may draft a real estate sales contract?",
  ["Only an attorney, in every case", "A licensee may complete Commission-approved or standard preprinted forms",
   "Any party, without limits", "Only the closing attorney"], 1,
  "Unauthorized practice of law",
  "Licensees may fill in the blanks on preprinted forms incident to a transaction they are handling. Drafting custom clauses or giving legal advice about them crosses into the unauthorized practice of law."),
Q("contracts",
  "A special stipulation in a Georgia contract that conflicts with the preprinted text generally:",
  ["Is void", "Controls over the preprinted language",
   "Must be initialed by the broker", "Requires GREC approval"], 1,
  "Interpreting conflicting contract terms",
  "Handwritten or typed additions reflect the parties' specific intent and prevail over standard preprinted terms. This is a general contract-construction rule the Georgia exam likes to test."),
Q("contracts",
  "The Georgia contract term giving a buyer a set number of days to inspect and terminate is commonly the:",
  ["Right of first refusal", "Due diligence period", "Option to renew", "Redemption period"], 1,
  "Due diligence in Georgia contracts",
  "During the due diligence period the buyer may inspect and, in most standard forms, terminate for any reason and recover the earnest money. After it expires, the buyer's exit rights narrow sharply."),
Q("contracts",
  "If a Georgia buyer defaults and the contract provides for liquidated damages, the seller typically:",
  ["Receives three times the deposit", "Retains the earnest money as agreed damages",
   "May not recover anything", "Must sue for specific performance first"], 1,
  "Liquidated damages in Georgia",
  "The earnest money serves as the agreed measure of damages. For the clause to be enforceable rather than a penalty, the amount must be a reasonable pre-estimate of loss, and damages must be hard to determine."),
Q("contracts",
  "A Georgia listing agreement must:",
  ["Be verbal to be enforceable", "Be in writing with a definite expiration date",
   "Automatically renew", "Be recorded with the clerk"], 1,
  "Listing agreement requirements",
  "Georgia requires listings in writing with a definite ending date. Automatic renewal provisions are prohibited -- a licensee cannot roll a listing forward indefinitely."),
Q("contracts",
  "A Georgia brokerage engagement with no definite expiration date is:",
  ["Valid indefinitely", "A violation of license law",
   "Enforceable for one year", "Converted to an open listing"], 1,
  "Definite termination dates",
  "GREC requires a definite expiration date in brokerage engagements. Open-ended agreements are a disciplinary matter for the broker."),
Q("contracts",
  "In Georgia, an offer may be withdrawn by the buyer:",
  ["Never once signed", "Any time before acceptance is communicated",
   "Only with the seller's consent", "Only within 24 hours"], 1,
  "Revocation of an offer",
  "An offer may be revoked any time before the offeror learns of acceptance. Once acceptance is communicated, a binding agreement exists and unilateral withdrawal becomes a breach."),
Q("contracts",
  "A 'time is of the essence' provision in a Georgia contract means:",
  ["Dates are advisory", "Failing to perform by a stated date is a breach",
   "Closing may slip 30 days", "Only the seller must be timely"], 1,
  "Effect of time-is-of-the-essence",
  "Without it, courts allow a reasonable time. With it, deadlines are strict -- particularly important with Georgia's due diligence and financing contingency dates."),
Q("contracts",
  "If a Georgia seller accepts an offer but changes the closing date before signing, the result is:",
  ["A binding contract on the buyer's terms", "A counteroffer the buyer may accept or reject",
   "An automatic 10-day extension", "A voidable contract"], 1,
  "Counteroffers",
  "Any change to terms rejects the original offer and creates a counteroffer. The original buyer is released and becomes the new offeree."),
Q("contracts",
  "A contingency requiring the buyer to sell an existing home is usually paired with a:",
  ["Kick-out clause letting the seller continue marketing", "Mandatory arbitration clause",
   "Prepayment penalty", "Subordination agreement"], 0,
  "Sale-of-buyer's-property contingencies",
  "A kick-out clause lets the seller accept a backup offer and require the first buyer to remove the contingency within a short window or terminate."),

# ----------------------------------------------------------- GA disclosures
Q("disclosures",
  "Georgia law generally does NOT require disclosure that a property was the site of:",
  ["A leaking underground tank", "A homicide or suicide",
   "Active termite infestation", "A failing septic system"], 1,
  "Stigmatized property in Georgia",
  "Georgia expressly protects licensees from liability for not disclosing that a property was the site of a death, homicide, suicide, or felony. Physical CONDITION defects must always be disclosed."),
Q("disclosures",
  "A Georgia licensee who knows the basement floods but says nothing has:",
  ["Properly protected client confidences", "Failed to disclose a known adverse material fact",
   "Committed puffing", "Acted within BRRETA"], 1,
  "Adverse material facts",
  "Confidentiality never shields a known physical defect. Under BRRETA a broker must disclose adverse material facts actually known, even to customers."),
Q("disclosures",
  "Under BRRETA, does a Georgia broker have a duty to independently inspect the property for defects?",
  ["Yes, a full inspection is required", "No -- the duty covers adverse material facts actually known",
   "Only for new construction", "Only if the buyer asks"], 1,
  "No duty to discover",
  "BRRETA limits the obligation to facts ACTUALLY KNOWN. Brokers are not inspectors; the buyer should retain one. But a licensee may not ignore what is plainly visible or make false statements."),
Q("disclosures",
  "The federal lead-based paint disclosure applies in Georgia to homes built before:",
  ["1968", "1972", "1978", "1985"], 2,
  "Lead-based paint",
  "Pre-1978 target housing requires the disclosure, the EPA pamphlet, and a 10-day testing opportunity. This is federal law and applies in Georgia unchanged."),
Q("disclosures",
  "Georgia's Property Disclosure Statement is completed by the:",
  ["Listing broker", "Seller", "Buyer's agent", "Closing attorney"], 1,
  "Who makes the disclosure",
  "The SELLER completes the disclosure from personal knowledge. The licensee should never fill it in for the seller or guess at answers -- doing so transfers the seller's liability to the licensee."),
Q("disclosures",
  "A Georgia licensee learns the seller's disclosure statement contains a false answer about the roof. The licensee must:",
  ["Say nothing -- the seller signed it", "Not pass along information known to be false",
   "Change the form personally", "Cancel the listing without notice"], 1,
  "Passing along false information",
  "A licensee may not knowingly convey false information. Relaying a statement the licensee knows to be untrue makes the licensee a participant in the misrepresentation."),
Q("disclosures",
  "Disclosure that a former occupant had HIV/AIDS is:",
  ["Required in Georgia", "Prohibited, as handicap is a protected class",
   "Optional at the seller's request", "Required only in writing"], 1,
  "Fair housing limits on disclosure",
  "Handicap includes HIV/AIDS status. Disclosing it would be discriminatory under federal fair housing law, and Georgia does not require disclosure of stigma in any event."),
Q("disclosures",
  "A Georgia seller must disclose the presence of a known:",
  ["Neighbor dispute over politics", "Defective septic system",
   "Prior owner's bankruptcy", "Ghost sighting"], 1,
  "Material physical defects",
  "Conditions affecting the property's value, safety, or use must be disclosed. Personal matters and stigma generally need not be."),
Q("disclosures",
  "Georgia requires a licensee acting as a principal in a transaction to disclose their licensed status:",
  ["Verbally at closing", "In writing in the contract or lease",
   "Only to the broker", "Only if asked"], 1,
  "Licensee-as-principal disclosure",
  "Written disclosure of licensed status in the sales contract or lease is mandatory whenever a licensee buys, sells, or leases for their own account."),
Q("disclosures",
  "If a Georgia property is in a flood plain and the seller knows it, the fact is:",
  ["Confidential", "An adverse material fact requiring disclosure",
   "Only the lender's concern", "Disclosed after closing"], 1,
  "Flood plain disclosure",
  "Flood exposure affects value, insurability, and use, making it a material fact. It also drives the lender's flood insurance requirement."),

# ------------------------------------------------------- GA closing/escrow
Q("procedures",
  "Georgia real estate closings must be conducted under the supervision of:",
  ["A licensed real estate broker", "A Georgia-licensed attorney",
   "The lender's underwriter", "A title company escrow officer"], 1,
  "Georgia is an attorney-closing state",
  "Georgia requires a licensed attorney to supervise the closing, because examining title and preparing conveyance documents is the practice of law. This differs sharply from escrow states like California."),
Q("procedures",
  "The Georgia real estate transfer tax is:",
  ["$0.10 per $1,000", "$1.00 per $1,000 of consideration",
   "1% of the sale price", "$10 per $1,000"], 1,
  "Georgia transfer tax",
  "The rate is $1.00 per $1,000 (0.10%), customarily paid by the SELLER and collected by the clerk of superior court when the deed is recorded."),
Q("procedures",
  "The Georgia instrument that secures a loan by conveying title to the lender is a:",
  ["Mortgage", "Security deed", "Deed of trust", "Land contract"], 1,
  "Georgia's security instrument",
  "Georgia uses a SECURITY DEED (deed to secure debt), which passes legal title to the lender until the debt is paid. This is why Georgia foreclosures are nonjudicial and comparatively fast."),
Q("procedures",
  "Foreclosure in Georgia is typically:",
  ["Judicial, requiring a lawsuit", "Nonjudicial, by power of sale with advertisement",
   "Automatic after 30 days", "Prohibited on residences"], 1,
  "Georgia foreclosure procedure",
  "The security deed's power of sale permits nonjudicial foreclosure: notice to the borrower and advertisement in the county legal organ, typically for four weeks, then a sale on the courthouse steps on the first Tuesday of the month."),
Q("procedures",
  "The period for acquiring Georgia title by adverse possession without color of title is:",
  ["7 years", "10 years", "20 years", "30 years"], 2,
  "Georgia adverse possession",
  "20 years without color of title, or 7 years WITH color of title (a defective written instrument the possessor believes is valid). Both require open, notorious, continuous, hostile possession."),
Q("procedures",
  "Georgia does NOT recognize which form of co-ownership?",
  ["Tenancy in common", "Joint tenancy with right of survivorship",
   "Tenancy by the entirety", "Ownership by a partnership"], 2,
  "Georgia co-ownership forms",
  "Georgia abolished tenancy by the entirety. Married Georgians typically hold as joint tenants with right of survivorship or as tenants in common -- a classic national-vs-Georgia contrast question."),
Q("procedures",
  "Recording a deed in Georgia is done in the:",
  ["Secretary of State's office", "Clerk of superior court in the county where the land lies",
   "Department of Revenue", "Probate court"], 1,
  "Where documents are recorded",
  "Deeds, security deeds, and plats are recorded with the clerk of superior court in the county where the property is located, giving constructive notice to the world."),
Q("procedures",
  "In a Georgia transaction the closing attorney generally represents:",
  ["Both buyer and seller equally", "The lender, unless otherwise agreed",
   "The real estate broker", "The county"], 1,
  "Who the closing attorney represents",
  "The closing attorney customarily represents the LENDER. Buyers who want their own advocate must retain separate counsel -- a point licensees should make clear rather than implying the attorney represents the buyer."),
Q("procedures",
  "Georgia property taxes become a lien on real property:",
  ["Only after a court judgment", "On January 1 of the tax year",
   "At closing", "When the bill is mailed"], 1,
  "Georgia tax liens and prorations",
  "The lien attaches as of January 1, which is why closings prorate taxes for the year and why unpaid taxes follow the property regardless of who owned it when they accrued."),
Q("procedures",
  "The document a Georgia buyer receives showing final loan terms and closing figures is the:",
  ["Loan Estimate", "Closing Disclosure", "HUD-1 in all cases", "Settlement affidavit"], 1,
  "TRID at the Georgia closing table",
  "The Closing Disclosure must be received at least 3 business days before consummation. It replaced the HUD-1 for most consumer mortgage transactions in 2015."),

# ------------------------------------------------------ GA fair housing
Q("fair-housing",
  "A Georgia landlord refuses to rent to a family with two young children. This violates:",
  ["No law -- children may be excluded", "The Fair Housing Act's familial status protection",
   "Only local ordinance", "The lead paint rule"], 1,
  "Familial status",
  "Familial status covers households with children under 18, pregnant persons, and those securing custody. The narrow exception is qualified housing for older persons (55+ or 62+)."),
Q("fair-housing",
  "A Georgia licensee tells a buyer 'you'd be more comfortable in a neighborhood on the south side.' This is:",
  ["Good customer service", "Steering", "Blockbusting", "Puffing"], 1,
  "Steering",
  "Directing buyers toward or away from areas based on a protected class is steering, even when the licensee believes they are being helpful. Provide objective information and let the buyer choose."),
Q("fair-housing",
  "A licensee tells owners that property values will drop because a protected group is moving in, hoping to get listings. This is:",
  ["Redlining", "Blockbusting", "Steering", "A permitted market opinion"], 1,
  "Blockbusting (panic peddling)",
  "Inducing sales by claiming a protected group's entry will harm the neighborhood is blockbusting. It is illegal whether or not the statements are true."),
Q("fair-housing",
  "A tenant with a disability asks to install a grab bar. Under fair housing law the landlord must:",
  ["Pay for and install it", "Permit the reasonable modification at the tenant's expense",
   "Refuse if the lease bars changes", "Terminate the lease"], 1,
  "Modification vs. accommodation",
  "Physical MODIFICATIONS are permitted at the tenant's expense, with possible restoration on move-out. Policy ACCOMMODATIONS, like waiving a no-pets rule for a service animal, are at the landlord's expense."),
Q("fair-housing",
  "Which is NOT a protected class under the federal Fair Housing Act?",
  ["Religion", "Familial status", "Marital status", "National origin"], 2,
  "The seven federal protected classes",
  "Race, color, religion, sex, national origin, familial status, and handicap. Marital status is protected by ECOA in LENDING and by some local ordinances, but is not one of the seven federal housing classes."),
Q("fair-housing",
  "A complaint of housing discrimination in Georgia may be filed with:",
  ["GREC only", "HUD, and GREC may also discipline the licensee",
   "The MLS", "The county tax office"], 1,
  "Enforcement channels",
  "HUD handles federal fair housing complaints (generally within one year), and a licensee's conduct can independently cost them their license through GREC discipline."),
Q("fair-housing",
  "A seller instructs a Georgia licensee to reject offers from a particular ethnic group. The licensee should:",
  ["Comply, since the seller is the client", "Refuse and, if the seller persists, withdraw from the engagement",
   "Comply but document it", "Refer the seller to another licensee"], 1,
  "Unlawful client instructions",
  "The duty of obedience covers LAWFUL instructions only. Following the instruction makes the licensee personally liable, and referring the seller to a colleague simply spreads the violation."),
Q("fair-housing",
  "An advertisement for a Georgia rental reading 'no Section 8' is:",
  ["Always a federal fair housing violation", "Not a federal violation, though it may violate local law and can show disparate impact",
   "Required by HUD", "Permitted only for houses"], 1,
  "Source of income and fair housing",
  "Source of income is not one of the seven federal classes, so the phrase is not automatically a federal violation. Some Georgia local ordinances do protect it, and a blanket policy can still create disparate-impact exposure."),
]
