# -*- coding: utf-8 -*-
"""Georgia bank, part A: GREC license law, trust accounts, BRRETA.

Facts verified against the GREC Real Estate InfoBase (chapters 3, 4, 6, 9).
"""

def Q(topic, q, choices, answer, concept, explain):
    return {"topic": "georgia/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain}

ROWS = [
# -------------------------------------------------------------- license law
Q("license-law",
  "To be licensed as a Georgia salesperson an applicant must be at least:",
  ["17 years old", "18 years old", "19 years old", "21 years old"], 1,
  "Georgia age requirements",
  "18 for salesperson or community association manager; 21 for broker or associate broker. An applicant may TAKE the salesperson exam at 17 but cannot activate the license until 18."),
Q("license-law",
  "The Georgia prelicense course required for a salesperson's license is:",
  ["25 hours", "60 hours", "75 hours", "90 hours"], 2,
  "Georgia prelicense education",
  "Georgia requires a 75-hour GREC-approved salesperson prelicense course. Do not confuse it with the 25-hour POSTlicense course due in the first year."),
Q("license-law",
  "A newly licensed Georgia salesperson must complete a 25-hour postlicense course:",
  ["Within one year of original licensure", "Within two years", "Before taking the exam",
   "Only if practicing full time"], 0,
  "Georgia postlicense requirement",
  "The 25-hour Sales Post-license Course is due within ONE year of original licensure. It applies whether the license is active or inactive and whether the licensee is a Georgia resident or not. Missing it costs the license."),
Q("license-law",
  "Active Georgia licensees must complete how much continuing education each four-year renewal period?",
  ["12 hours", "24 hours", "36 hours", "45 hours"], 1,
  "Georgia continuing education",
  "Georgia requires at least 24 hours of GREC-approved CE during each four-year renewal period. Many national study guides quote 36 hours, which is a different state -- Georgia is 24."),
Q("license-law",
  "An applicant for a Georgia broker's license must have held an active license for at least:",
  ["One of the past two years", "Two of the past three years",
   "Three of the five years immediately preceding application", "Five continuous years"], 2,
  "Georgia broker experience requirement",
  "Three years of active licensure within the five years immediately preceding application. Active licensure in ANOTHER state counts, provided the applicant supplies a certified license history."),
Q("license-law",
  "There is no experience requirement for which Georgia license?",
  ["Broker", "Associate broker", "Salesperson", "Qualifying broker"], 2,
  "Which licenses require experience",
  "A salesperson's license has no experience requirement -- only age, education, exam, and background. Broker and associate broker both require the three-of-five-years experience."),
Q("license-law",
  "The Georgia Real Estate Commission's disciplinary powers include all of the following EXCEPT:",
  ["Reprimanding a licensee", "Ordering a licensee to repay a consumer's financial loss",
   "Suspending or revoking a license", "Imposing a fine and requiring education"], 1,
  "Limits on GREC's authority",
  "GREC may reprimand, suspend, revoke, fine, require education, and require accountant reports on trust accounts. It has NO power to force a licensee to compensate someone for a financial loss -- that requires a civil suit. This is a favorite exam distinction."),
Q("license-law",
  "A GREC investigation that finds a violation causing no significant public harm is most likely resolved by:",
  ["Immediate revocation", "A consent order the licensee may sign",
   "Referral for criminal prosecution", "Automatic license suspension"], 1,
  "The GREC disciplinary process",
  "The Commission may offer a Consent Order stating the violation and a proposed sanction, usually a reprimand, fine, and/or education. The licensee may sign it, propose an alternative, present evidence, or demand a formal hearing."),
Q("license-law",
  "A formal GREC disciplinary hearing is conducted by:",
  ["The full Commission", "An Administrative Law Judge from the Office of State Administrative Hearings",
   "A superior court judge", "The Attorney General"], 1,
  "Who hears GREC cases",
  "An ALJ hears the case and issues a decision. A dissatisfied respondent may then ask to appear before the Commission, and ultimately may appeal to the courts."),
Q("license-law",
  "Who may initiate a GREC investigation of a licensee?",
  ["Only a party to the transaction", "Only the licensee's broker",
   "Anyone, by sworn written request -- and the Commission on its own motion", "Only the Attorney General"], 2,
  "Initiating an investigation",
  "Anyone may file a sworn, written request for investigation, and the Commission may also act on its own motion. The licensee will be notified that they are the subject of an investigation."),
Q("license-law",
  "A Georgia licensee selling a property he personally owns must:",
  ["Ignore license law because he is the owner", "Disclose his licensed status in writing in the contract",
   "Obtain a separate owner's permit", "Use another broker exclusively"], 1,
  "Licensee acting as a principal",
  "O.C.G.A. 43-40-29(c) says the exceptions to licensure never apply to someone who holds a license. A licensee selling his own property must disclose licensed status in writing and put any trust funds in a broker-approved trust account."),
Q("license-law",
  "A licensee whose license is on inactive status:",
  ["Has no education obligations", "Must still meet the postlicense education requirement",
   "May still list property", "Loses the license automatically"], 1,
  "Inactive status obligations",
  "Postlicense education still applies to an inactive salesperson, and renewal fees still come due. Inactive licensees may not perform licensed activity."),
Q("license-law",
  "Which activity requires a Georgia real estate license?",
  ["An owner selling her own home", "An executor selling estate property",
   "Negotiating a lease for another for compensation", "An attorney performing legal services"], 2,
  "Activities requiring licensure",
  "Negotiating, listing, selling, leasing, or collecting rents FOR ANOTHER for compensation requires a license. Owners, executors, and attorneys acting in their own roles are excepted -- but never a person who already holds a license."),
Q("license-law",
  "A Georgia licensee must notify GREC of a change of address or broker affiliation:",
  ["Only at renewal", "By filing a change application with the Commission",
   "Verbally to the broker only", "Within one year"], 1,
  "Keeping the license record current",
  "Changes in affiliation or status are made by filing a change application. Operating without a current, properly affiliated license is itself a violation."),
Q("license-law",
  "A salesperson's license in Georgia is held by:",
  ["The salesperson personally, independent of any firm", "The broker with whom the salesperson is affiliated",
   "The MLS", "The Commission until renewal"], 1,
  "Broker supervision",
  "A salesperson may only act through and under the supervision of the affiliated broker. All compensation for licensed activity must come from that broker, not directly from a client or another licensee."),
Q("license-law",
  "The qualifying broker of a real estate firm is responsible for:",
  ["Only the broker's own transactions", "Supervising affiliated licensees and the firm's trust accounts",
   "Paying affiliates' income taxes", "Guaranteeing affiliates' commissions"], 1,
  "Qualifying broker duties",
  "The qualifying broker answers to GREC for the firm's compliance -- supervision, trust accounts, records, and advertising. Failure to supervise is an independent violation."),
Q("license-law",
  "Georgia advertising rules require that a licensee's advertising:",
  ["Use only the licensee's personal name", "Clearly identify the licensee's firm",
   "Omit the firm name for brevity", "Appear only in the MLS"], 1,
  "Advertising and the firm name",
  "Advertising must not be misleading and must identify the brokerage firm. A licensee may never advertise in a way that suggests they operate independently of their broker."),
Q("license-law",
  "A licensee convicted of a felony after licensure must:",
  ["Do nothing until renewal", "Report the conviction to the Commission",
   "Surrender the license automatically", "Notify only the broker"], 1,
  "Reporting convictions",
  "Licensees must report criminal convictions to GREC. Failing to report is often punished more severely than the underlying offense."),
Q("license-law",
  "Under Georgia law, a net listing is:",
  ["Always prohibited", "Permitted only under strict disclosure conditions",
   "Required for commercial property", "The standard listing form"], 1,
  "Net listings in Georgia",
  "Georgia permits net listings only with careful disclosure, because they create a conflict between the broker's profit and the client's interest. Many brokerages ban them outright by policy."),
Q("license-law",
  "The Georgia Real Estate Commission's members are:",
  ["Elected by licensees", "Appointed by the Governor",
   "Selected by the state association of REALTORS", "Appointed by the Attorney General"], 1,
  "GREC structure",
  "Commission members are appointed by the Governor. GREC administers the license law, issues rules, investigates complaints, and disciplines licensees."),

# ------------------------------------------------------------ trust accounts
Q("trust-accounts",
  "A Georgia broker's trust account must be:",
  ["Any personal savings account", "A federally insured checking account the bank designates as a trust or escrow account",
   "An investment brokerage account", "Held in the salesperson's name"], 1,
  "Trust account requirements",
  "It must be a separate, federally insured bank checking account that the BANK designates as trust or escrow, registered with the Commission, with the broker holding signatory power."),
Q("trust-accounts",
  "A Georgia broker should open the trust account under:",
  ["The broker's Social Security Number", "An Employer Identification Number",
   "The client's tax ID", "No tax identification"], 1,
  "Protecting the trust account from seizure",
  "Accounts opened under a broker's SSN have been seized by the IRS, awarded in divorce, and attached by banks for the broker's personal debts. An EIN keeps the account identifiable as trust property."),
Q("trust-accounts",
  "Georgia law requires a broker to deposit trust funds:",
  ["Within 30 days", "Promptly, unless all parties give written authority otherwise",
   "Only after closing", "Whenever the broker chooses"], 1,
  "Timing of trust deposits",
  "Funds must be deposited promptly into a non-interest-bearing checking account. To hold a check until offer acceptance, or to use an interest-bearing account, the broker needs clear WRITTEN authority agreed to by all parties."),
Q("trust-accounts",
  "A broker who deposits earnest money into the firm's operating account has committed:",
  ["A permissible practice", "Commingling", "Novation", "Subrogation"], 1,
  "Commingling in Georgia",
  "Trust funds must stay separate from the broker's own money. Commingling is one of the most frequently disciplined license law violations; actually spending the funds is conversion."),
Q("trust-accounts",
  "How many trust accounts may a Georgia broker maintain?",
  ["Exactly one", "At least one, and more if each is registered with the Commission",
   "No more than two", "One per affiliated licensee"], 1,
  "Multiple trust accounts",
  "Brokers must have at least one but may have several -- commonly separate accounts for earnest money, rents, and security deposits. Each must be bank-designated as trust and registered with GREC, with the broker holding signatory power."),
Q("trust-accounts",
  "The Georgia Real Estate Commission's authority over a broker's trust account includes:",
  ["No access without a warrant", "Examining the account upon reasonable request",
   "Freezing the account at will", "Setting the interest rate"], 1,
  "GREC audit authority",
  "GREC may examine trust accounts on reasonable request and does so routinely. The Commission may accept a CPA's certification of compliance in lieu of its own examination, at its discretion."),
Q("trust-accounts",
  "Which of these is NOT trust money that must go into the trust account?",
  ["A tenant's security deposit", "Rents collected for an owner",
   "The broker's earned commission after disbursement", "A buyer's advance for a credit report"], 2,
  "What counts as trust funds",
  "Once a transaction closes and the commission is properly earned and disbursed, it is the broker's money. Everything held ON BEHALF OF another -- deposits, rents, advances -- is trust money."),
Q("trust-accounts",
  "A broker must notify the Commission in writing when:",
  ["The account balance changes", "The trust account's bank, name, or number changes or the account closes",
   "A new client is added", "Interest is earned"], 1,
  "Trust account recordkeeping duties",
  "Any change in the bank, account name or number, or closure of the account requires written notice to GREC on Commission forms."),
Q("trust-accounts",
  "FDIC 'pass-through' coverage on a broker's trust account means:",
  ["The broker is insured for $250,000 total", "Each client depositor is treated as a separate account owner",
   "Coverage is unlimited", "No coverage applies to trust accounts"], 1,
  "FDIC coverage of trust accounts",
  "With proper records, each buyer, seller, or tenant is insured separately up to $250,000. But the FDIC ADDS that person's other deposits in the same bank, so a client near the limit may be underinsured -- brokers should disclose which bank they use."),
Q("trust-accounts",
  "An affiliated licensee permitted to hold a trust account for personally owned rentals must:",
  ["Keep no records", "Provide the broker at least quarterly written reconciliation statements",
   "Register the account personally with the IRS only", "Avoid telling the broker"], 1,
  "Affiliate-held trust accounts",
  "The broker must register the account with GREC and remains responsible for it. The affiliate must provide at least quarterly written reconciliations comparing total trust liability with the reconciled bank balance."),

# ------------------------------------------------------------------- BRRETA
Q("brreta",
  "Under BRRETA, an agency relationship in Georgia is created by:",
  ["Showing a buyer three properties", "A written brokerage engagement",
   "Paying the broker a commission", "A verbal promise to represent"], 1,
  "How agency is created in Georgia",
  "BRRETA defines agency as representing another as a client 'by the latter's WRITTEN authority.' A brokerage engagement is a written contract. This is why accidental agency is far harder to create in Georgia than in many states."),
Q("brreta",
  "Under BRRETA, does paying a broker's commission by itself create an agency relationship?",
  ["Yes, always", "No -- there must be an express written agreement",
   "Yes, if the payer is the seller", "Only in residential transactions"], 1,
  "Compensation does not equal agency",
  "A seller paying the buyer's broker does NOT make that broker the seller's agent. Source of compensation and agency are separate questions -- a frequently tested point."),
Q("brreta",
  "Under BRRETA, a person NOT represented by a broker but for whom the broker performs ministerial acts is a:",
  ["Client", "Customer", "Principal", "Subagent"], 1,
  "Client vs. customer under BRRETA",
  "A CLIENT is represented under a written brokerage engagement. A CUSTOMER is unrepresented; the broker may perform ministerial acts for them under a verbal OR written agreement."),
Q("brreta",
  "A significant difference between BRRETA and traditional common-law agency is that under BRRETA a broker:",
  ["Owes unlimited fiduciary duties", "Is not deemed to have a fiduciary relationship, but must exercise reasonable care in the duties specified",
   "Owes no duties at all", "May not represent buyers"], 1,
  "BRRETA limits the scope of duties",
  "BRRETA states a broker 'shall not be deemed to have a fiduciary relationship with any party' and is responsible for reasonable care in discharging the duties the statute and the engagement specify. This narrowing of liability is the heart of the Act."),
Q("brreta",
  "BRRETA requires a broker, before or at the time of entering a brokerage engagement, to advise the prospective client of all of the following EXCEPT:",
  ["The types of agency relationships available", "The broker's compensation and whether it is shared",
   "The names of the broker's other clients buying similar property",
   "The broker's confidentiality obligations"], 2,
  "The four BRRETA pre-engagement disclosures",
  "The broker discloses agency types available, conflicting relationships actually known, compensation and sharing, and confidentiality obligations. It expressly EXCLUDES having to reveal that the broker represents other buyers or sellers generally."),
Q("brreta",
  "Under BRRETA, dual agency is:",
  ["Prohibited in Georgia", "Allowed with written consent from both clients",
   "Allowed with verbal consent", "Allowed only for commercial property"], 1,
  "Dual agency in Georgia",
  "Georgia permits dual agency but requires written consent. Consent is presumed if the writing contains the required elements, including a statement that the client does NOT have to consent."),
Q("brreta",
  "A required element of a valid Georgia dual agency consent is a statement that:",
  ["The client must consent to proceed", "The client does not have to consent to the dual agency",
   "The commission will be doubled", "The broker will favor the seller"], 1,
  "Contents of dual agency consent",
  "The writing must describe the transactions involved, state that the broker represents two clients with potentially adverse interests, explain the disclosure of adverse material facts, and state that consent is voluntary."),
Q("brreta",
  "Two licensees of the same Georgia firm represent the buyer and the seller in one transaction. This is:",
  ["Automatically illegal dual agency", "Designated agency, permitted with written consent",
   "Subagency", "A conflict requiring withdrawal"], 1,
  "Designated agency -- a Georgia distinction",
  "Many states treat this as firm-wide dual agency. BRRETA lets the broker assign different affiliated licensees to represent opposing clients, with the parties' written consent. Each designated agent represents only their own client."),
Q("brreta",
  "A designated agent under BRRETA may share a client's confidential information with:",
  ["The other designated agent in the firm", "Their broker only",
   "Any licensee in the firm", "The other party's attorney"], 1,
  "Confidentiality between designated agents",
  "Designated agents may not disclose confidential client information except to their broker, and except for information BRRETA allows or requires to be disclosed. The two designated agents must not share confidences with each other."),
Q("brreta",
  "A dual agent must disclose to both parties:",
  ["All confidential information from each client", "All adverse material facts actually known to the dual agent",
   "Nothing at all", "Only the property's list price"], 1,
  "What a dual agent must and must not reveal",
  "The dual agent discloses adverse material facts actually known, but NOT information a client has asked be kept confidential. Balancing these two rules is the practical difficulty of dual agency."),
Q("brreta",
  "A brokerage engagement under BRRETA terminates upon:",
  ["The first showing", "Any expiration date agreed to by the parties",
   "The broker's request only", "Delivery of a CMA"], 1,
  "Duration of the engagement",
  "It begins when the client engages the broker and runs until the agreed expiration date or another statutory ending event. An engagement with no ending date invites disputes."),
Q("brreta",
  "Under BRRETA, when must a licensee discuss agency status with a prospect?",
  ["At the first contact, by statute", "By the time of the brokerage engagement, though earlier is better practice",
   "Only after an offer is made", "Never"], 1,
  "Timing of the agency conversation",
  "BRRETA does not require the discussion until the engagement, but the InfoBase urges doing it as early as possible so a customer never presumes they are represented."),
Q("brreta",
  "A Georgia broker representing the seller shows a home to an unrepresented buyer. The broker owes that buyer:",
  ["Full fiduciary duties", "Honesty, fairness, and disclosure of adverse material facts, plus ministerial acts",
   "No duties whatsoever", "The duty to negotiate the lowest price"], 1,
  "Duties owed to customers",
  "Customers get honesty and disclosure of adverse material facts the broker knows, and may receive ministerial assistance. They do not get advocacy, advice on price, or confidentiality."),
Q("brreta",
  "Under BRRETA, the duties a broker owes a client are:",
  ["Whatever the common law of agency provides", "Those set out in the chapter and specified in the brokerage engagement",
   "Unlimited and non-negotiable", "Determined by the MLS"], 1,
  "Contractual scope of duties",
  "BRRETA ties the broker's obligations to the statute plus the engagement, unless the parties expressly agree otherwise in a signed writing. This lets Georgia brokers define the scope of what they promise."),
Q("brreta",
  "The main problem BRRETA was enacted to solve was:",
  ["Commission disputes between brokers", "Accidental or unintended agency relationships with customers",
   "Fair housing violations", "Appraisal fraud"], 1,
  "Purpose of BRRETA",
  "Licensees treating customers like clients created implied agency and lawsuits from buyers who believed they were represented. BRRETA fixed this by requiring written engagements and defining each role."),
]
