# -*- coding: utf-8 -*-
"""Georgia bank, HARD tier. Grounded in the GREC InfoBase (ch. 3, 4, 6, 9)."""

def Q(topic, q, choices, answer, concept, explain):
    return {"topic": "georgia/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain, "difficulty": 2}

ROWS = [
# -------------------------------------------------------------- license law
Q("license-law",
  "A Georgia salesperson licensed 14 months ago never took the postlicense course. The licensee's status is that the license:",
  ["Renews normally at the four-year mark", "Lapses -- the 25-hour course was due within the first year",
   "Converts automatically to inactive", "Is fine if the licensee took CE instead"], 1,
  "The postlicense deadline is absolute",
  "The 25-hour Sales Post-license Course is due within ONE year of original licensure and applies whether active or inactive, resident or nonresident. CE does not substitute for it. Missing the deadline costs the license."),
Q("license-law",
  "A consumer loses $18,000 because of a Georgia licensee's mishandling of funds and files a GREC complaint. The most GREC itself can do is:",
  ["Order the licensee to repay the $18,000",
   "Revoke or suspend the license, fine, and require education or accountant reports",
   "Garnish the licensee's commissions", "Award treble damages"], 1,
  "GREC cannot order restitution",
  "GREC's powers are reprimand, suspension, revocation, fines, required education, and required CPA reports on trust accounts. It has NO authority to compel repayment of a financial loss -- the consumer must sue civilly, and should not wait for the investigation to finish."),
Q("license-law",
  "An applicant held an active Florida broker's license for four of the last five years and now applies for a Georgia broker's license. Regarding experience, the applicant:",
  ["Must first hold a Georgia salesperson license for three years",
   "Satisfies the requirement, with a certified license history from Florida",
   "Cannot qualify, since out-of-state experience does not count",
   "Must have five continuous years"], 1,
  "Out-of-state experience counts in Georgia",
  "Georgia requires three of the five years immediately preceding application in ACTIVE status, and active licensure in another state qualifies. The applicant must obtain a certified copy of license history and education from every state where they have held a license."),
Q("license-law",
  "A Georgia licensee owns a rental duplex personally and advertises it for lease. The licensee:",
  ["May act as an ordinary owner, since owners are exempt from licensure",
   "Must disclose licensed status in writing in the lease and use a broker-approved trust account",
   "Must transfer the property to the brokerage", "Needs a separate property management license"], 1,
  "Exceptions to licensure never apply to a licensee",
  "O.C.G.A. 43-40-29(c) provides that none of the exceptions to licensure applies to a person who holds a license. Selling or leasing your own property means written disclosure of licensed status and placing any trust funds in an account approved by your broker."),
Q("license-law",
  "An ALJ rules against a Georgia licensee. The licensee disagrees and does nothing for 35 days. The result is:",
  ["The decision is void for lack of a hearing before the Commission",
   "The decision became final after 30 days",
   "An automatic appeal to superior court", "A new hearing is scheduled"], 1,
  "The 30-day window after an ALJ decision",
  "If the respondent does not ask the Commission to review within 30 days of the ALJ's decision, it becomes final. The Commission also has 30 days to request review if IT disagrees. After that, the route is an appeal to the courts."),
Q("license-law",
  "A qualifying broker discovers an affiliated salesperson has been advertising without naming the firm. The broker's exposure is:",
  ["None, since the salesperson acted alone",
   "Potential discipline for failure to supervise, in addition to the salesperson's violation",
   "Limited to a fine against the firm", "Only if a consumer complains"], 1,
  "Failure to supervise is its own violation",
  "The qualifying broker answers to GREC for the firm's compliance, and inadequate supervision is an independent charge. GREC can act on its own motion, so a consumer complaint is not a prerequisite."),
Q("license-law",
  "A licensee is convicted of a felony unrelated to real estate and does not report it, believing renewal is two years away. The licensee has:",
  ["Acted properly, since disclosure occurs at renewal",
   "Violated the reporting requirement, often punished more harshly than the underlying offense",
   "No obligation, as the crime was unrelated", "An obligation only to notify the broker"], 1,
  "Reporting convictions to GREC",
  "Convictions must be reported to the Commission, not saved for renewal. GREC treats concealment as a separate and often more serious matter than the conviction itself, because it goes to honesty and trustworthiness."),
Q("license-law",
  "A Georgia licensee with license number above 100,000 completed 24 hours of CE in the first year of a four-year renewal period and none after. At renewal the licensee:",
  ["Must complete 24 more hours", "Has satisfied the requirement",
   "Must complete 6 hours per year regardless", "Must complete 36 hours total"], 1,
  "Georgia CE is per renewal period, not per year",
  "The requirement is at least 24 hours of GREC-approved CE during each FOUR-YEAR renewal period. There is no annual minimum. National guides quoting 36 hours are describing a different state."),

# ------------------------------------------------------------------ BRRETA
Q("brreta",
  "A Georgia buyer works with a licensee for weeks, and the licensee gives advice on price and negotiation. No written agreement is ever signed. Under BRRETA the licensee:",
  ["Is the buyer's agent by implication",
   "Has no agency relationship, since BRRETA requires written authority, but has acted well outside the customer role",
   "Is a dual agent", "Is a subagent of the seller automatically"], 1,
  "Written engagement is required -- but conduct still matters",
  "BRRETA defines agency as representation 'by the latter's WRITTEN authority,' so no engagement means no agency. That is exactly why the statute exists. But behaving like an agent invites a claim and confusion, which is why the InfoBase urges clarifying status early."),
Q("brreta",
  "A Georgia seller asks her broker to keep confidential that she will accept $20,000 less. The broker later serves as a DUAL agent for both sides. The broker must:",
  ["Disclose the seller's bottom line, since dual agents disclose everything",
   "Keep it confidential -- a dual agent discloses adverse material facts, not information a client asked be kept confidential",
   "Withdraw from the transaction", "Disclose it only if the buyer asks directly"], 1,
  "The dual agent's two competing rules",
  "A dual agent must disclose adverse MATERIAL FACTS actually known, but expressly not information made confidential by a client's request. A negotiating position is confidential, not a material fact. Balancing these is the practical difficulty of dual agency."),
Q("brreta",
  "A Georgia broker assigns one licensee to the buyer and another to the seller in the same deal. Under BRRETA the broker is:",
  ["A dual agent, because the firm represents both clients",
   "Expressly NOT deemed a dual agent, and neither is the firm or its other licensees",
   "Required to withdraw from the transaction",
   "The agent of whichever client signed first"], 1,
  "Designated agency is not dual agency in Georgia",
  "O.C.G.A. 10-6A-13(b) states that where designated agents are appointed, neither the broker, the broker's licensees, nor the firm is deemed a dual agent. The statute also removes imputed knowledge: the broker and each designated agent are treated as having only their own actual knowledge, and the broker may not reveal confidential information received from a designated agent or client."),
Q("brreta",
  "In a Georgia transaction the seller pays the buyer-broker's commission out of closing proceeds. This means the buyer-broker:",
  ["Becomes the seller's agent or subagent",
   "Still represents only the buyer -- compensation does not create agency",
   "Becomes a dual agent", "Must disclose the payment as a conflict"], 1,
  "Compensation and agency are independent under BRRETA",
  "BRRETA is explicit that paying compensation does not by itself create a brokerage engagement; only an express written agreement does. This is heavily tested because the intuition runs the other way."),
Q("brreta",
  "Before entering a brokerage engagement, a Georgia broker who already represents three other buyers looking in the same neighborhood must:",
  ["Disclose the identity of those buyers",
   "Advise of agency types available, known conflicting relationships, compensation and sharing, and confidentiality duties -- but need not reveal that other buyers are represented",
   "Decline the new engagement", "Obtain the other buyers' written consent"], 1,
  "The four BRRETA pre-engagement disclosures and their limit",
  "BRRETA lists four disclosures and then expressly EXCLUDES having to reveal that the broker represents other buyers or sellers in similar transactions. Competing clients are normal; naming them would breach confidentiality."),
Q("brreta",
  "A Georgia client sues a broker for breach of fiduciary duty, citing common-law agency standards. Under BRRETA the broker's best position is that:",
  ["Fiduciary duties never apply to brokers anywhere",
   "BRRETA provides a broker is not deemed a fiduciary and owes reasonable care in the duties the statute and engagement specify",
   "The client waived all duties by signing", "Only the Commission can decide the claim"], 1,
  "BRRETA narrowed broker liability",
  "BRRETA states a broker 'shall not be deemed to have a fiduciary relationship with any party' and is responsible for exercising reasonable care in its specified duties. That statutory narrowing -- unless the parties agree otherwise in a signed writing -- is the heart of the Act."),
Q("brreta",
  "A brokerage engagement in Georgia is signed with no expiration date. This is:",
  ["Valid until either party cancels", "A license law violation -- a definite date is required",
   "Automatically one year", "Valid for commercial property only"], 1,
  "Definite termination dates",
  "GREC requires a definite expiration date in brokerage engagements, and automatic renewal clauses are prohibited. An open-ended agreement is a disciplinary matter for the broker, independent of whether the client is happy."),

# ----------------------------------------------------------- trust accounts
Q("trust-accounts",
  "A Georgia buyer asks the broker to hold the earnest money check uncashed until the seller accepts. The broker may:",
  ["Do so only with clear written authority agreed to by all parties",
   "Do so on the buyer's verbal request", "Never do so under any circumstances",
   "Do so if the check is under $5,000"], 0,
  "Deviating from prompt deposit",
  "Georgia requires prompt deposit into a non-interest-bearing trust account. Holding a check until acceptance, using an interest-bearing account, or accepting a postdated check all require clear WRITTEN authority from all parties -- not just the buyer's say-so."),
Q("trust-accounts",
  "A Georgia broker opened the firm's trust account using her Social Security Number. The IRS later levies it for her personal tax debt. The InfoBase's guidance is that the broker should have:",
  ["Used a second bank", "Opened all trust accounts under an Employer Identification Number",
   "Kept balances under $250,000", "Notified clients of the risk"], 1,
  "EIN, not SSN, for trust accounts",
  "The InfoBase recounts trust accounts seized by the IRS, awarded in a divorce, and attached by a bank -- the common thread being accounts opened under the broker's SSN. An EIN keeps the account identifiable as trust property rather than the broker's asset."),
Q("trust-accounts",
  "A client already has $250,000 on deposit at the same bank holding the broker's trust account, and gives the broker a $10,000 earnest money deposit. If the bank fails, the broker:",
  ["Is fully protected by pass-through coverage",
   "May be liable for the $10,000 if the client was not told which bank holds trust funds",
   "Has no exposure, as FDIC covers brokers separately", "Must reimburse the full $260,000"], 1,
  "The limit of FDIC pass-through coverage",
  "Pass-through treats each client as a separate owner, but the FDIC ADDS the client's other deposits at the same bank against the $250,000 cap. The InfoBase warns that a broker who failed to disclose the bank and this limitation may be liable for the uninsured excess."),
Q("trust-accounts",
  "A Georgia broker lets an affiliated licensee maintain a trust account for the licensee's own rental properties. The broker must:",
  ["Do nothing further, since the properties are the licensee's",
   "Register the account with GREC, remain responsible for it, and obtain at least quarterly written reconciliations",
   "Close the account and consolidate", "Obtain GREC approval for each transaction"], 1,
  "Affiliate-held trust accounts",
  "The broker registers the account with the Commission and stays responsible for it. The affiliate must provide at least QUARTERLY written reconciliation statements comparing total trust liability with the reconciled bank balance, and keep the same records a broker keeps."),
Q("trust-accounts",
  "GREC staff asks a Georgia broker to produce trust account records. The broker has a CPA's compliance certification on file. The broker may:",
  ["Refuse the examination outright", "Request that GREC accept the CPA report instead, which GREC may accept at its discretion",
   "Insist GREC obtain a subpoena", "Provide only bank statements"], 1,
  "CPA certification in lieu of examination",
  "GREC may examine trust accounts on reasonable request. The Commission MAY accept a CPA's certification of compliance instead, but that is discretionary -- the broker can request it, not demand it."),

# ------------------------------------------------------- Georgia contracts
Q("contracts",
  "A Georgia seller signs a buyer's offer on Tuesday but the agent does not notify the buyer until Thursday. The binding agreement date is:",
  ["Tuesday, when the seller signed", "Thursday, when acceptance was communicated",
   "Wednesday, splitting the difference", "The date the contract is recorded"], 1,
  "Georgia's binding agreement date",
  "Georgia measures contract deadlines -- due diligence, financing, closing -- from the binding agreement date, which is when acceptance is communicated to the offeror. Getting this wrong shifts every subsequent deadline."),
Q("contracts",
  "A Georgia buyer terminates during the due diligence period without stating a reason. Under a standard form the buyer:",
  ["Forfeits the earnest money for failing to state cause",
   "Is generally entitled to the earnest money back",
   "Must pay the seller's costs", "May terminate only for inspection defects"], 1,
  "What the due diligence period buys",
  "Georgia's standard due diligence provision lets the buyer terminate for any reason or no reason within the window and recover the earnest money. That latitude is exactly why the period is negotiated hard -- once it expires, the buyer's exits narrow sharply."),
Q("contracts",
  "A Georgia licensee adds a handwritten special stipulation that conflicts with the preprinted form language. A dispute arises. A court will MOST likely:",
  ["Void the whole contract for ambiguity", "Give effect to the handwritten stipulation",
   "Give effect to the preprinted text", "Refer the matter to GREC"], 1,
  "Specific terms beat boilerplate",
  "Handwritten or typed additions reflect the parties' specific intent and prevail over standard preprinted terms. That is also why licensees must be careful: a poorly drafted stipulation controls the deal, and drafting original clauses edges into the unauthorized practice of law."),
Q("contracts",
  "A Georgia licensee, asked by a buyer to add a complex owner-financing clause, should:",
  ["Draft the clause, since filling in forms is permitted",
   "Advise the buyer to have an attorney draft it",
   "Copy a clause from another transaction", "Refuse to write the offer at all"], 1,
  "Where form-filling ends and law practice begins",
  "Licensees may complete blanks on approved preprinted forms incident to a transaction they are handling. Composing an original financing clause is drafting a legal instrument -- the unauthorized practice of law, and a liability trap even when the clause happens to work."),

# ----------------------------------------------------- Georgia disclosures
Q("contracts",
  "A Georgia listing agreement provides that it automatically renews monthly unless cancelled. This provision is:",
  ["Enforceable if initialed", "Prohibited -- Georgia requires a definite expiration date",
   "Enforceable for 90 days", "Valid only for commercial property"], 1,
  "No automatic renewals",
  "GREC requires listings and brokerage engagements in writing with a definite ending date, and automatic renewal clauses are not permitted. A broker cannot roll a listing forward indefinitely by default."),
Q("disclosures",
  "A Georgia seller knows a murder occurred in the home three years ago. The buyer does not ask. The seller and licensee:",
  ["Must disclose it as a material fact",
   "Generally need not disclose it, and Georgia protects against liability for that nondisclosure",
   "Must disclose only if the buyer has children", "Must disclose it in the MLS"], 1,
  "Georgia's stigmatized-property protection",
  "Georgia expressly shields licensees from liability for not disclosing that a property was the site of a death, homicide, suicide, or felony. Physical CONDITION defects are a different matter and must always be disclosed."),
Q("disclosures",
  "A Georgia buyer asks the listing agent directly whether anyone died in the house. The agent knows someone did. The safest response is:",
  ["Deny it, since disclosure is not required",
   "Decline to answer and refer the buyer to other sources, since nondisclosure is protected but an affirmative lie is not",
   "Answer fully, waiving the protection", "Refuse to continue the showing"], 1,
  "Nondisclosure is protected; lying is not",
  "Georgia's protection covers NOT volunteering the information. It does not license an affirmative misstatement, which would be misrepresentation. Declining to answer keeps the licensee inside the protection."),
Q("disclosures",
  "Under BRRETA a Georgia broker's disclosure duty regarding property condition extends to:",
  ["All defects a competent inspector would find",
   "Adverse material facts actually known to the broker",
   "Only defects listed on the seller's disclosure form",
   "Nothing, if the buyer is a customer"], 1,
  "No duty to discover in Georgia",
  "BRRETA limits the obligation to adverse material facts ACTUALLY KNOWN. Brokers are not inspectors and need not investigate. But the duty runs to customers as well as clients, so 'the buyer is unrepresented' is never the answer."),

# --------------------------------------------------------- GA procedures
Q("procedures",
  "At a Georgia closing the buyer asks the closing attorney whether the contract's repair clause protects them. The attorney typically represents the lender. The licensee should:",
  ["Let the attorney advise the buyer as a courtesy",
   "Make clear the attorney represents the lender and the buyer may retain their own counsel",
   "Answer the buyer's legal question personally", "Postpone the closing"], 1,
  "Who the Georgia closing attorney represents",
  "Georgia requires an attorney to supervise the closing, and that attorney customarily represents the LENDER. Letting a buyer believe otherwise is a common and costly misunderstanding -- and the licensee must not supply the legal opinion instead."),
Q("procedures",
  "A Georgia property sells on March 10. County taxes for the year became a lien on January 1 and are unpaid. At closing the taxes are:",
  ["Ignored, since the bill has not arrived", "Prorated, with the seller debited for their share",
   "Paid entirely by the buyer", "Paid entirely by the seller"], 1,
  "Georgia tax liens attach January 1",
  "The lien attaches January 1 and follows the property, so closings prorate. Because the taxes are unpaid, the seller is DEBITED for the portion covering their ownership and the buyer is credited, since the buyer will pay the full bill later."),
Q("procedures",
  "A Georgia borrower defaults. The lender holds a security deed with a power of sale. Foreclosure will typically proceed by:",
  ["A judicial action in superior court",
   "Advertisement in the county legal organ and a sale on the courthouse steps the first Tuesday of the month",
   "Repossession without notice", "Automatic transfer after 90 days"], 1,
  "Georgia nonjudicial foreclosure",
  "The security deed's power of sale permits nonjudicial foreclosure: notice to the borrower plus advertisement in the county legal organ, typically four weeks, then a public sale on the first Tuesday. This is why Georgia foreclosures move comparatively fast."),
Q("procedures",
  "A married Georgia couple wants title with automatic survivorship. The correct advice is that Georgia:",
  ["Recognizes tenancy by the entirety for spouses",
   "Does not recognize tenancy by the entirety; they may hold as joint tenants with right of survivorship",
   "Requires tenancy in common for spouses", "Requires a trust"], 1,
  "Georgia abolished tenancy by the entirety",
  "This is a frequent national-vs-Georgia contrast. Georgians achieve survivorship through joint tenancy with right of survivorship, expressly stated in the deed. A licensee should route the actual titling decision to an attorney."),
Q("procedures",
  "A Georgia parcel has been occupied openly and continuously by a neighbor for 12 years under a defective deed the neighbor believed valid. The neighbor's claim is:",
  ["Not ripe -- 20 years is required", "Complete, because 7 years applies under color of title",
   "Barred, because a defective deed defeats the claim", "Limited to a prescriptive easement"], 1,
  "Georgia's two adverse possession periods",
  "Georgia requires 20 years without color of title, but only 7 years WITH color of title -- a written instrument that appears to convey title but is defective. Twelve years under a defective deed satisfies the shorter period."),

# --------------------------------------------------------- GA fair housing
Q("fair-housing",
  "A Georgia seller instructs the listing agent to reject offers from a protected class. The agent refuses; the seller insists. The agent's correct course is:",
  ["Continue the listing but ignore the instruction quietly",
   "Withdraw from the engagement",
   "Refer the seller to a colleague", "Comply, documenting that the seller directed it"], 1,
  "Unlawful instructions end the relationship",
  "Obedience covers LAWFUL instructions only. Quietly ignoring the instruction leaves the agent working for a client who will discriminate; referring the seller to a colleague simply relocates the violation. Withdrawing is the clean answer."),
Q("fair-housing",
  "A Georgia property manager charges a $300 non-refundable fee to tenants with assistance animals, applied uniformly. This is:",
  ["Lawful, since it applies to everyone equally",
   "Unlawful -- an assistance animal is not a pet and no pet fee may be charged",
   "Lawful if disclosed in the lease", "Lawful for commercial property"], 1,
  "Assistance animals and reasonable accommodation",
  "Waiving a pet policy for an assistance animal is a reasonable ACCOMMODATION, made at the housing provider's expense. Charging a pet fee or deposit defeats the accommodation. The tenant remains liable for actual damage the animal causes."),
Q("fair-housing",
  "A licensee provides school ratings and crime statistics only when buyers of a certain background ask. This practice is:",
  ["Fine, since the data is publicly available",
   "Steering, because selective delivery of information channels buyers by protected class",
   "Required by fair housing law", "A disclosure violation only"], 1,
  "Steering by selective information",
  "Steering does not require saying anything negative. Providing or withholding neighborhood information based on who is asking channels buyers just as effectively. The safe practice is a consistent policy for every buyer -- typically pointing everyone to the same public sources."),
]
