# -*- coding: utf-8 -*-
"""National bank, HARD tier A: ownership, land use, valuation, financing.

Harder means: a scenario rather than a definition, distractors that are true
statements but do not answer the question asked, and at least one step of
reasoning between the stem and the key.
"""

def Q(topic, q, choices, answer, concept, explain):
    return {"topic": "national/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain, "difficulty": 2}

ROWS = [
# ---------------------------------------------------------------- ownership
Q("ownership",
  "A owns property in fee simple determinable, to revert automatically if liquor is ever sold there. A conveys to B, who opens a bar. At that moment:",
  ["B holds a fee simple absolute because A already conveyed away the whole estate",
   "Title reverts to A or A's heirs automatically, without any court action",
   "A must sue to re-enter and recover title",
   "The restriction is void as an unreasonable restraint on alienation"], 1,
  "Determinable fee vs. fee on condition subsequent",
  "A DETERMINABLE fee ends automatically -- the possibility of reverter takes effect the instant the condition occurs. A fee subject to a CONDITION SUBSEQUENT requires the grantor to exercise a right of re-entry, which is where a lawsuit would be needed. A cannot convey a larger estate than A held."),
Q("ownership",
  "Two sisters own a lake house as joint tenants. One dies leaving a will devising 'all my real property to my son.' The son receives:",
  ["A one-half interest as a tenant in common", "A one-half interest as a joint tenant",
   "Nothing in this property", "A life estate in one-half"], 2,
  "Survivorship defeats a will",
  "The right of survivorship operates at the instant of death, before the will takes effect -- the deceased joint tenant has no interest left to devise. The surviving sister owns the whole property. A will can only pass what the decedent still owned."),
Q("ownership",
  "A commercial tenant bolts specialized refrigeration units to the floor of a leased space. The lease is silent. At lease end the tenant may:",
  ["Not remove them, because bolting made them fixtures",
   "Remove them, repairing any damage, because they are trade fixtures",
   "Remove them only with the landlord's written consent",
   "Remove them only if they can be taken out without any damage"], 1,
  "Trade fixtures are the exception to the fixture rule",
  "Items a commercial tenant installs to conduct business remain the tenant's personal property and may be removed before the lease ends, provided the tenant repairs damage. The annexation test that would make them fixtures does not apply to trade fixtures. Leaving them past lease end can forfeit them."),
Q("ownership",
  "An owner grants a utility company the right to run a line across her land. She later sells. The easement:",
  ["Terminates at the sale because it was personal to the grantor",
   "Continues, because an easement in gross benefiting a commercial entity is assignable and survives transfer",
   "Continues only if the buyer expressly assumes it",
   "Converts to an easement appurtenant on transfer"], 1,
  "Easement in gross vs. appurtenant",
  "A utility easement is an easement in gross -- it benefits a person or entity, not a parcel, so there is no dominant tenement. Commercial easements in gross are assignable and bind later owners of the servient land once recorded. Only a personal (non-commercial) easement in gross would arguably end."),
Q("ownership",
  "A life tenant fails to pay property taxes for three years and lets the roof fail. The remainderman's BEST characterization of this is:",
  ["Waste, for which the remainderman may sue now",
   "A breach the remainderman must wait until the life estate ends to raise",
   "Permissible, since the life tenant owns the present interest",
   "Grounds to terminate the life estate automatically"], 0,
  "Waste and the life tenant's duties",
  "A life tenant must pay taxes and ordinary carrying costs and avoid permissive waste. The remainderman has a present interest to protect and may sue for waste immediately -- waiting could mean the property is lost to a tax sale. The estate does not terminate automatically."),
Q("ownership",
  "A condominium declaration allots each unit an undivided percentage of the common elements. That percentage MOST directly determines each owner's:",
  ["Voting power and share of assessments", "Square footage of the unit",
   "Right to lease the unit", "Property tax rate"], 0,
  "How the common-element percentage functions",
  "The undivided percentage drives assessments and usually voting weight. It is set in the declaration, not by unit size alone, and it cannot be separated from the unit -- you cannot sell your common-element share by itself."),

# ----------------------------------------------------------------- land use
Q("landuse",
  "A city downzones an area, leaving an owner's lot usable but worth 40% less. The owner sues claiming a taking. The owner will MOST likely:",
  ["Win, because the value loss exceeds one third",
   "Lose, because the regulation left economically viable use of the land",
   "Win, because downzoning is per se a taking",
   "Lose, because zoning can never be challenged"], 1,
  "Regulatory taking vs. valid police power",
  "A regulation becomes a taking when it denies ALL economically viable use, not merely when it reduces value. Diminution in value alone -- even substantial -- is generally a cost of regulation. Zoning can certainly be challenged, but on grounds like arbitrariness, not mere value loss."),
Q("landuse",
  "A legal nonconforming gas station burns down. The owner wants to rebuild it as it was. Under a typical ordinance the owner will:",
  ["Be permitted, because nonconforming status runs with the land",
   "Likely be barred, because destruction usually extinguishes nonconforming status",
   "Be permitted only if rebuilt larger", "Need only a building permit"], 1,
  "How nonconforming use is lost",
  "Nonconforming rights are meant to phase out, not persist forever. Most ordinances end the status on destruction beyond a stated percentage, on abandonment for a set period, or on a change to a different nonconforming use. Rebuilding then requires conforming to current zoning or obtaining a variance."),
Q("landuse",
  "A subdivision's recorded covenants bar fences over four feet. For fifteen years owners have built six-foot fences with no objection. A neighbor now sues to enforce. The BEST defense is:",
  ["The covenant expired automatically after ten years",
   "Laches and abandonment of the covenant through a pattern of non-enforcement",
   "Covenants are unenforceable against later buyers",
   "Only the developer may enforce covenants"], 1,
  "Defenses to enforcement of covenants",
  "Long, widespread non-enforcement can waive a covenant through abandonment, and delay that prejudices the defendant supports laches. Covenants do not expire on their own unless they say so, they do bind later buyers, and any benefited owner may enforce them."),
Q("landuse",
  "A property owner's land is landlocked after the seller conveys away the parcel fronting the road. The owner's strongest claim to access is:",
  ["An easement by prescription", "An easement by necessity",
   "A license from the neighbor", "Eminent domain against the neighbor"], 1,
  "Easement by necessity",
  "When a single parcel is severed and one part is left without access, the law implies an easement by necessity over the retained land. Prescription requires long adverse use, which has not occurred here; a license is revocable; private owners cannot condemn."),

# ---------------------------------------------------------------- valuation
Q("valuation",
  "An appraiser must value a two-year-old home in a subdivision where twelve nearly identical homes sold in the last six months. The cost approach would MOST likely:",
  ["Be the only reliable approach", "Serve as a check, with sales comparison given the most weight",
   "Be meaningless for new construction", "Replace the need for reconciliation"], 1,
  "Weighting the approaches in reconciliation",
  "Abundant near-identical sales make sales comparison the strongest indicator. Cost is genuinely useful on nearly new homes (little depreciation to estimate) but serves as support here. An appraiser reconciles by weighting reliability, never by averaging."),
Q("valuation",
  "A comparable superior to the subject sold for $420,000; its extra half-bath is worth $12,000 and its inferior lot costs $8,000. The adjusted value indication is:",
  ["$400,000", "$416,000", "$424,000", "$440,000"], 1,
  "Netting adjustments on the comparable",
  "Adjust the COMP toward the subject. Superior feature: subtract $12,000. Inferior feature: add $8,000. $420,000 - $12,000 + $8,000 = $416,000. Adjusting the subject instead, or moving both in the same direction, produces the distractors."),
Q("valuation",
  "A four-unit building rents for $1,400 per unit monthly with 5% vacancy and $19,000 annual operating expenses. At an 8% cap rate its value is closest to:",
  ["$625,000", "$690,000", "$560,000", "$840,000"], 2,
  "Building NOI before applying the cap rate",
  "Gross annual = 4 x $1,400 x 12 = $67,200. Less 5% vacancy ($3,360) = $63,840 effective gross. Less $19,000 expenses = $44,840 NOI. $44,840 / 0.08 = $560,500, closest to $560,000. Skipping vacancy or expenses produces the higher distractors -- debt service is never an operating expense."),
Q("valuation",
  "An appraiser notes the subject's roof needs $9,000 of work that would add $9,000 of value. This is BEST classified as:",
  ["Curable physical deterioration", "Incurable physical deterioration",
   "Functional obsolescence", "External obsolescence"], 0,
  "Curable vs. incurable depreciation",
  "Curability is an economic test, not a physical one: an item is curable when the cost to fix it is recovered in added value. Spending $9,000 to gain $9,000 sits right at the line and is treated as curable. If the fix cost more than it returned, it would be incurable."),
Q("valuation",
  "A house on a busy corner sells for less than identical houses mid-block. When the appraiser accounts for this, the deduction is properly assigned to:",
  ["The improvements, as functional obsolescence",
   "The land, as external obsolescence",
   "The improvements, as physical deterioration",
   "Neither -- it is a financing concession"], 1,
  "Where external obsolescence is charged",
  "External obsolescence comes from outside the property. Because a location penalty attaches to the site rather than the building, appraisers charge it against the LAND. Functional problems attach to the improvements; physical deterioration is wear."),

# ---------------------------------------------------------------- financing
Q("financing",
  "A buyer takes title 'subject to' the seller's existing loan and later defaults. The lender forecloses and the sale leaves a $40,000 shortfall. The lender may pursue a deficiency judgment against:",
  ["The buyer only", "The original seller-borrower only",
   "Both buyer and seller jointly", "Neither party"], 1,
  "'Subject to' vs. assumption",
  "Taking 'subject to' means the buyer accepts NO personal liability on the note -- the buyer just risks losing the property. The original borrower remains fully liable. Had the buyer ASSUMED, both would be liable (buyer primarily, seller secondarily) absent a novation."),
Q("financing",
  "A borrower is offered 6.5% with no points, or 6.0% with 2 points on a $300,000 loan. Roughly how long must the borrower keep the loan for the points to pay off, using simple first-year interest?",
  ["About 1 year", "About 4 years", "About 8 years", "The points never pay off"], 1,
  "Break-even analysis on discount points",
  "Points cost 2% x $300,000 = $6,000. The rate saving is 0.5% x $300,000 = $1,500 in the first year. $6,000 / $1,500 = 4 years to break even. A buyer planning to sell or refinance sooner should decline the points."),
Q("financing",
  "Under TRID, which change after the Closing Disclosure is delivered REQUIRES a new three-business-day waiting period?",
  ["The seller agrees to pay an extra $500 toward closing costs",
   "The APR increases beyond tolerance", "A typo in the borrower's name is corrected",
   "The loan amount decreases by $200"], 1,
  "The three CD re-disclosure triggers",
  "Only three changes restart the clock: the APR becomes inaccurate beyond tolerance, the loan PRODUCT changes, or a prepayment penalty is added. Other changes require a corrected CD at or before consummation but no new waiting period."),
Q("financing",
  "A lender's appraisal comes in $15,000 below the contract price on a 95% LTV loan. Absent an appraisal contingency, the buyer must:",
  ["Renegotiate or bring the $15,000 difference in cash, on top of the down payment",
   "Accept a loan of 95% of the contract price", "Terminate with the earnest money returned",
   "Require the seller to lower the price"], 0,
  "The appraisal gap",
  "The lender lends on the LOWER of price or appraised value, so the loan shrinks and the shortfall becomes the buyer's cash problem. Without an appraisal contingency the buyer has no automatic right to terminate and no power to force a price reduction -- only to ask."),
Q("financing",
  "A veteran's VA loan is assumed by a non-veteran buyer with VA approval, but the veteran does not obtain a release of liability. The veteran's entitlement:",
  ["Is fully restored at closing", "Remains tied up until the loan is paid or a substitution of entitlement occurs",
   "Is lost permanently", "Was never at risk"], 1,
  "VA entitlement and assumption",
  "Entitlement stays committed to the loan until it is paid off or another eligible veteran substitutes their entitlement. Without a release of liability the veteran also remains liable for a deficiency, and cannot use that entitlement for a new home."),
Q("financing",
  "A lender denies a loan and tells the applicant only 'you did not meet our standards.' Under ECOA the lender has:",
  ["Complied, because reasons are optional",
   "Violated the Act by failing to give specific reasons or notice of the right to them",
   "Violated the Act only if the applicant is in a protected class",
   "Complied, provided the denial was in writing"], 1,
  "ECOA adverse action notice",
  "ECOA entitles a rejected applicant to a statement of SPECIFIC reasons, or notice of the right to request them within 60 days. The obligation applies to every applicant regardless of protected class -- the notice requirement is not itself a discrimination question."),
Q("financing",
  "A blanket mortgage covering twelve subdivision lots contains a release clause. Its practical effect is that the developer can:",
  ["Sell individual lots free of the lien as portions of the debt are paid",
   "Avoid personal liability on the note", "Substitute other collateral at will",
   "Prepay without penalty"], 0,
  "Blanket mortgages and partial releases",
  "The release (or partial release) clause lets the developer clear the lien lot by lot as agreed payments come in, so buyers get clear title. Without it, the whole debt would have to be retired before any lot could convey free of the blanket lien."),
]
