# -*- coding: utf-8 -*-
"""National bank, part B: financing, agency, disclosures."""

def Q(topic, q, choices, answer, concept, explain):
    return {"topic": "national/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain}

ROWS = [
# ---------------------------------------------------------------- financing
Q("financing",
  "The clause allowing a lender to declare the entire balance due immediately upon default is the:",
  ["Defeasance clause", "Acceleration clause", "Alienation clause", "Subordination clause"], 1,
  "Standard mortgage clauses",
  "ACCELERATION makes the whole balance due on default -- a prerequisite to foreclosure. The ALIENATION (due-on-sale) clause triggers on TRANSFER, not default; DEFEASANCE requires the lender to release the lien when the debt is paid."),
Q("financing",
  "A buyer assumes the seller's existing loan. Unless the lender releases the seller, the seller remains:",
  ["Free of all liability", "Secondarily liable for the debt",
   "The legal owner of the property", "Entitled to the tax deduction"], 1,
  "Assumption vs. 'subject to' vs. novation",
  "On assumption the buyer becomes primarily liable, but the original borrower stays SECONDARILY liable until the lender grants a release -- a NOVATION. Taking title 'subject to' the loan means the buyer accepts no personal liability at all."),
Q("financing",
  "Discount points are charged by a lender primarily to:",
  ["Cover the appraisal cost", "Increase the lender's yield on the loan",
   "Pay the mortgage broker's commission", "Fund the escrow account"], 1,
  "Points and lender yield",
  "Points are prepaid interest that raise the lender's effective yield, allowing a lower note rate. One point equals 1% of the LOAN amount, and roughly 8 points change the yield by about 1%."),
Q("financing",
  "Which loan feature makes a mortgage 'fully amortized'?",
  ["Interest-only payments with a balloon", "Equal payments that retire principal and interest by maturity",
   "Payments that increase every year", "A single payment at the end of the term"], 1,
  "Amortization vs. term loans",
  "A fully amortized loan's level payments pay off the entire balance by the last payment. A TERM (straight) loan pays interest only with principal due at the end; a partially amortized loan leaves a balloon."),
Q("financing",
  "The federal law requiring lenders to disclose the Annual Percentage Rate to consumers is:",
  ["RESPA", "Truth in Lending (Regulation Z)", "ECOA", "The Fair Housing Act"], 1,
  "Consumer credit disclosure",
  "Reg Z / TILA governs cost-of-credit disclosure including APR and triggering terms in advertising. RESPA governs settlement services, kickbacks, and the Loan Estimate/Closing Disclosure timing."),
Q("financing",
  "Under RESPA, a lender may NOT:",
  ["Require a survey", "Pay a referral fee to a broker for sending it business",
   "Collect an escrow cushion", "Charge an origination fee"], 1,
  "RESPA Section 8 anti-kickback",
  "Paying or receiving anything of value for the mere REFERRAL of settlement business is prohibited. Fees for services actually performed are allowed."),
Q("financing",
  "A borrower with a conventional loan and less than 20% down will typically be required to carry:",
  ["FHA mortgage insurance premium", "Private mortgage insurance",
   "A VA funding fee", "Title insurance for the borrower"], 1,
  "Mortgage insurance by loan type",
  "PMI protects the LENDER on conventional loans above 80% LTV. FHA loans carry MIP instead; VA loans carry a funding fee and need no monthly mortgage insurance."),
Q("financing",
  "The secondary mortgage market's primary function is to:",
  ["Originate loans to consumers", "Purchase existing loans, restoring lenders' funds to lend again",
   "Set federal interest rates", "Insure loans against default"], 1,
  "Primary vs. secondary mortgage market",
  "Fannie Mae, Freddie Mac, and Ginnie Mae buy loans from originators, providing liquidity so lenders can make new loans. Consumers never deal with the secondary market directly."),
Q("financing",
  "In a deed of trust there are three parties: the borrower, the lender, and the:",
  ["Escrow agent", "Trustee", "Grantor", "Mortgagee"], 1,
  "Mortgage vs. deed of trust",
  "The TRUSTEE holds bare legal title for the lender (beneficiary) and can conduct a nonjudicial foreclosure sale. Georgia uses a similar instrument called a security deed."),
Q("financing",
  "A loan where the interest rate adjusts periodically based on a published index is a:",
  ["Fixed-rate mortgage", "Adjustable-rate mortgage", "Wraparound mortgage", "Purchase-money mortgage"], 1,
  "ARM structure",
  "An ARM's rate equals INDEX + MARGIN, adjusted at intervals subject to periodic and lifetime caps. The margin is the lender's constant markup; the index moves with the market."),
Q("financing",
  "Usury laws limit:",
  ["The number of points charged", "The maximum interest rate a lender may charge",
   "Loan-to-value ratios", "Prepayment penalties"], 1,
  "Usury",
  "Usury statutes cap the maximum lawful interest rate. Exceeding the cap can cost the lender interest or subject it to penalties."),
Q("financing",
  "A seller finances part of the buyer's purchase and takes back a note secured by the property. This is a:",
  ["Blanket mortgage", "Purchase-money mortgage", "Package mortgage", "Open-end mortgage"], 1,
  "Specialty loan types",
  "A purchase-money mortgage is seller financing taken back at the sale. A BLANKET mortgage covers multiple parcels with a release clause; a PACKAGE mortgage includes personal property; an OPEN-END loan lets the borrower re-borrow."),
Q("financing",
  "The Equal Credit Opportunity Act prohibits discrimination in lending based on all of the following EXCEPT:",
  ["Marital status", "Receipt of public assistance",
   "Amount of verifiable income", "Age (if the applicant can contract)"], 2,
  "ECOA protected bases",
  "ECOA bars race, color, religion, national origin, sex, marital status, age, and receipt of public assistance. A lender MAY absolutely evaluate the amount and stability of income -- that is legitimate underwriting."),
Q("financing",
  "Under TRID, the Closing Disclosure must be received by the borrower at least:",
  ["1 business day before consummation", "3 business days before consummation",
   "7 business days before consummation", "10 business days before consummation"], 1,
  "TRID timing rules",
  "The Closing Disclosure must be in the borrower's hands 3 business days before closing. The Loan Estimate is due within 3 business days of APPLICATION, and there is a separate 7-business-day wait between the LE and consummation."),

# ------------------------------------------------------------------- agency
Q("agency",
  "A seller's agent learns the seller will accept far less than list price. The agent must:",
  ["Tell any buyer who asks", "Keep it confidential unless the seller authorizes disclosure",
   "Disclose it in the MLS", "Tell only buyers who are also clients"], 1,
  "Fiduciary duty of confidentiality",
  "The seller's motivation and bottom line are confidential. Disclosing it would breach loyalty and confidentiality and cost the client bargaining power. Confidentiality survives termination of the agency."),
Q("agency",
  "The fiduciary duties owed by an agent to a principal are often remembered as OLD CAR. The 'O' stands for:",
  ["Openness", "Obedience", "Objectivity", "Oversight"], 1,
  "The six fiduciary duties",
  "Obedience, Loyalty, Disclosure, Confidentiality, Accounting, Reasonable care. OBEDIENCE means following lawful instructions -- an agent must refuse instructions that are unlawful, such as an instruction to discriminate."),
Q("agency",
  "An agency relationship created by the conduct of the parties, without a written agreement, is:",
  ["Express agency", "Implied agency", "Agency by ratification", "Agency coupled with an interest"], 1,
  "How agency is created",
  "Implied agency arises from behavior that leads a party to reasonably believe they are represented -- a common accidental-agency trap. RATIFICATION is approving an unauthorized act after the fact."),
Q("agency",
  "In a dual agency, the agent's ability to fully represent both parties is limited primarily because:",
  ["Commission must be split", "Loyalty and full disclosure to one party conflict with the other",
   "Only one party may be a client", "The MLS prohibits it"], 1,
  "The structural conflict in dual agency",
  "A dual agent cannot advocate for both sides on price and terms without breaching loyalty to someone, so the duties are reduced to neutrality. Dual agency requires informed written consent from BOTH parties and is illegal in some states."),
Q("agency",
  "A buyer's agent discovers the property has a cracked foundation the seller did not disclose. The buyer's agent must:",
  ["Say nothing -- it is the seller's duty", "Disclose the material defect to the buyer client",
   "Report it only to the listing broker", "Withdraw from the transaction"], 1,
  "Duty to disclose material facts to one's own client",
  "The buyer's agent owes the buyer disclosure of all known material facts. Agents also owe honesty about material defects to CUSTOMERS -- there is no duty to stay silent about a known defect for anyone."),
Q("agency",
  "An agent who represents the principal in a single transaction with limited authority is a:",
  ["Universal agent", "General agent", "Special agent", "Designated agent"], 2,
  "Scope of agency authority",
  "A SPECIAL agent has narrow authority for one transaction -- the typical listing broker. A GENERAL agent handles ongoing matters (a property manager); a UNIVERSAL agent may act in all matters under power of attorney."),
Q("agency",
  "An agency relationship terminates by operation of law upon all of the following EXCEPT:",
  ["Death of the principal", "Destruction of the property",
   "The client refusing an offer", "Bankruptcy of the principal"], 2,
  "Termination of agency",
  "Refusing an offer is simply the client exercising judgment -- the agency continues. Death, incapacity, destruction of the property, bankruptcy, expiration, and mutual agreement all end it."),
Q("agency",
  "When an agent places client funds in the agent's personal account, the violation is:",
  ["Novation", "Commingling", "Subrogation", "Estoppel"], 1,
  "Handling client money",
  "COMMINGLING is mixing client funds with the broker's own. Actually SPENDING them is conversion -- a more serious offense that typically costs the license."),
Q("agency",
  "A seller instructs the listing agent not to show the home to families with children. The agent must:",
  ["Comply -- the seller is the principal", "Refuse; the instruction is unlawful",
   "Comply but document the instruction", "Ask the buyer's agent to screen"], 1,
  "Limits on the duty of obedience",
  "Obedience extends only to LAWFUL instructions. Familial status is a protected class under the Fair Housing Act; following the instruction would make the agent liable alongside the seller."),
Q("agency",
  "A subagent of the seller owes fiduciary duties to:",
  ["The buyer", "The seller", "Both equally", "Neither"], 1,
  "Subagency",
  "A subagent works through the listing broker and owes full fiduciary duties to the SELLER, even though the subagent may spend all day driving the buyer around. This is why many states moved to buyer agency."),
Q("agency",
  "Puffing becomes actionable misrepresentation when the statement:",
  ["Is an opinion about the view", "Is a statement of material fact that is false",
   "Praises the neighborhood", "Predicts future appreciation"], 1,
  "Puffing vs. misrepresentation",
  "Exaggerated opinion ('the best view in town') is puffing. A false statement of MATERIAL FACT ('the roof is three years old' when it is twenty) is misrepresentation and creates liability."),
Q("agency",
  "A broker earns a commission when the broker produces a buyer who is:",
  ["Merely interested in the property", "Ready, willing, and able to buy on the seller's terms",
   "Pre-qualified by any lender", "Willing to make any offer"], 1,
  "When commission is earned",
  "The classic standard is a ready, willing, and able buyer meeting the seller's stated terms. Under most modern listing agreements, commission is actually earned at that moment even if the seller then refuses to close."),
Q("agency",
  "The principal in an agency relationship is also called the:",
  ["Customer", "Client", "Third party", "Fiduciary"], 1,
  "Client vs. customer",
  "The CLIENT is the principal, owed fiduciary duties. A CUSTOMER is an unrepresented third party owed only honesty, fairness, and disclosure of material defects."),

# --------------------------------------------------------------- disclosures
Q("disclosures",
  "A latent defect is one that is:",
  ["Visible on inspection", "Hidden and not discoverable by ordinary inspection",
   "Disclosed in the listing", "Always structural"], 1,
  "Latent vs. patent defects",
  "A LATENT defect is concealed -- the seller and agent must disclose known latent defects because a buyer cannot find them. A PATENT defect is obvious on reasonable inspection."),
Q("disclosures",
  "Under federal law, the lead-based paint disclosure applies to residential dwellings built:",
  ["Before 1978", "Before 1988", "Before 1968", "Any year, if paint is peeling"], 0,
  "Residential Lead-Based Paint Hazard Reduction Act",
  "The rule covers target housing built before 1978. Sellers must disclose known hazards, provide records and the EPA pamphlet, and give buyers a 10-day opportunity to test."),
Q("disclosures",
  "A naturally occurring radioactive gas that enters homes through foundation cracks is:",
  ["Asbestos", "Radon", "Formaldehyde", "Methane"], 1,
  "Environmental hazards",
  "Radon is a colorless, odorless gas and the second leading cause of lung cancer. Mitigation is typically a sub-slab depressurization vent system -- relatively inexpensive."),
Q("disclosures",
  "Under CERCLA, liability for cleanup of hazardous waste on a property may be imposed on:",
  ["Only the party that caused the contamination", "Current owners even if innocent of causing it",
   "Only commercial owners", "Only the original developer"], 1,
  "CERCLA / Superfund liability",
  "Liability is strict, joint and several, and retroactive -- a current owner can be liable without fault. The 'innocent landowner' defense requires having done appropriate due diligence, such as a Phase I assessment, before purchase."),
Q("disclosures",
  "A stigmatized property is one that:",
  ["Has a structural defect", "Buyers may find undesirable for psychological reasons",
   "Is in a flood zone", "Has an unrecorded easement"], 1,
  "Stigmatized property",
  "Stigma comes from events -- a death, crime, or rumor -- not physical condition. Most states, including Georgia, do NOT require disclosure of such events, and some expressly protect against liability for nondisclosure."),
Q("disclosures",
  "Federal law prohibits disclosing that a former occupant had:",
  ["A mortgage default", "AIDS or another protected medical condition",
   "A pending divorce", "An unpaid tax lien"], 1,
  "Fair housing limits on disclosure",
  "Handicap (including HIV/AIDS status) is a protected class under the Fair Housing Act, so disclosure would itself be discriminatory. Property CONDITION facts are disclosable; protected personal characteristics are not."),
Q("disclosures",
  "Friable asbestos is dangerous chiefly because:",
  ["It is flammable", "It crumbles and releases fibers into the air",
   "It conducts electricity", "It attracts moisture"], 1,
  "Asbestos hazards",
  "Friable material can be crumbled by hand and releases airborne fibers. Intact asbestos is often best ENCAPSULATED rather than removed, since improper removal raises exposure."),
Q("disclosures",
  "An underground storage tank triggers a disclosure concern mainly because of:",
  ["Property tax assessment", "Potential soil and groundwater contamination",
   "Zoning nonconformity", "Loss of riparian rights"], 1,
  "USTs as an environmental hazard",
  "Leaking tanks contaminate soil and groundwater, and the cleanup obligation can fall on the current owner under CERCLA-style liability."),
Q("disclosures",
  "A seller's agent who knows the basement floods after heavy rain and stays silent has committed:",
  ["Puffing", "Fraudulent concealment of a material fact",
   "A permissible withholding of client confidences", "Novation"], 1,
  "Material fact vs. client confidence",
  "Confidentiality never covers material defects. A known physical condition affecting value or desirability must be disclosed to buyers -- silence about it is fraudulent concealment, not loyalty."),
Q("disclosures",
  "The purpose of a Phase I Environmental Site Assessment is to:",
  ["Remediate contamination", "Identify potential contamination through records and inspection",
   "Establish market value", "Certify the septic system"], 1,
  "Environmental due diligence",
  "A Phase I is a non-invasive review of records, interviews, and a site visit. Only if it finds a concern does a Phase II involve sampling and testing."),
Q("disclosures",
  "Most states require a residential seller's property disclosure to be delivered:",
  ["After closing", "Before or at the time the buyer makes an offer",
   "Only if the buyer requests it", "Only for new construction"], 1,
  "Timing of seller disclosure",
  "Disclosure must come early enough for the buyer to weigh it before committing. Delivery after a binding contract typically gives the buyer a right to rescind."),
]
