# -*- coding: utf-8 -*-
"""National bank, part C: contracts, transfer of title, practice, math concepts."""

def Q(topic, q, choices, answer, concept, explain):
    return {"topic": "national/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain}

ROWS = [
# ---------------------------------------------------------------- contracts
Q("contracts",
  "A buyer makes an offer; the seller changes the closing date and signs. This is legally a:",
  ["Valid acceptance", "Counteroffer that rejects the original offer",
   "Voidable acceptance", "Conditional acceptance binding both"], 1,
  "Mirror-image rule of acceptance",
  "Any change to terms is a COUNTEROFFER, which terminates the original offer and makes the former seller the new offeror. The original buyer is then free to accept, reject, or counter again."),
Q("contracts",
  "A contract signed by a minor is:",
  ["Void", "Voidable by the minor", "Voidable by the adult party", "Unenforceable by anyone"], 1,
  "Capacity and the void/voidable distinction",
  "The minor may disaffirm, so the contract is VOIDABLE at the minor's option -- the adult party remains bound. A VOID contract (illegal purpose) never existed at all."),
Q("contracts",
  "The Statute of Frauds requires that contracts for the sale of real estate be:",
  ["Notarized", "In writing and signed by the party to be charged",
   "Recorded within 30 days", "Witnessed by two parties"], 1,
  "Statute of Frauds",
  "Writing and signature are required for enforceability -- notarization and recording are separate matters. Leases for one year or less are commonly exempt."),
Q("contracts",
  "Earnest money in a sales contract serves primarily as:",
  ["The consideration that makes the contract valid", "Evidence of the buyer's good faith and a potential source of damages",
   "A down payment required by lenders", "The broker's commission"], 1,
  "Purpose of earnest money",
  "A promise-for-a-promise supplies the consideration, so a contract is valid without earnest money. The deposit demonstrates good faith and gives the seller a fund to look to if the buyer defaults."),
Q("contracts",
  "A contract in which only one party is obligated to perform until the other acts is:",
  ["Bilateral", "Unilateral", "Executed", "Implied"], 1,
  "Bilateral vs. unilateral contracts",
  "An OPTION is the classic unilateral contract: the seller must sell if the optionee exercises, but the optionee need not buy. A typical purchase contract is bilateral -- both promise."),
Q("contracts",
  "A buyer defaults. The seller sues to force the buyer to complete the purchase. This remedy is:",
  ["Liquidated damages", "Specific performance", "Rescission", "Novation"], 1,
  "Remedies for breach",
  "Specific performance compels the actual transfer, available because each parcel of land is legally unique. LIQUIDATED DAMAGES is keeping an agreed sum (usually the earnest money) instead."),
Q("contracts",
  "The 'time is of the essence' clause means:",
  ["Deadlines are approximate", "Stated dates must be met exactly or the party is in breach",
   "Closing may be extended once", "The contract expires in 30 days"], 1,
  "Effect of time-is-of-the-essence",
  "Without the clause, courts allow performance within a reasonable time. With it, missing a stated date is a breach."),
Q("contracts",
  "An option contract requires the optionor to sell and the optionee to:",
  ["Buy at the stated price", "Do nothing unless the option is exercised",
   "Pay the full purchase price up front", "Record the option"], 1,
  "Option contracts",
  "The optionee buys the RIGHT to decide, paying option consideration that is usually nonrefundable. Only exercise creates a bilateral obligation."),
Q("contracts",
  "Assignment of a contract transfers:",
  ["Rights only, with the assignor remaining secondarily liable",
   "All liability, releasing the assignor completely",
   "Ownership of the real property", "Nothing without a new contract"], 0,
  "Assignment vs. novation",
  "An assignment passes rights but leaves the original party secondarily liable. Only a NOVATION -- substituting a new party with everyone's consent -- releases the original party."),
Q("contracts",
  "A contract that has been fully performed by both parties is:",
  ["Executory", "Executed", "Void", "Unilateral"], 1,
  "Executory vs. executed",
  "EXECUTED means fully performed. A contract signed but not yet closed is EXECUTORY -- a distinction the exam likes, since 'executed' also loosely means 'signed' in everyday speech."),
Q("contracts",
  "A financing contingency in a purchase agreement protects the:",
  ["Seller, by guaranteeing the sale", "Buyer, by allowing withdrawal if the loan is denied",
   "Lender, by fixing the rate", "Broker, by securing commission"], 1,
  "Contingencies as conditions precedent",
  "If the buyer applies in good faith and the loan is denied within the contingency period, the buyer may terminate and recover the earnest money."),
Q("contracts",
  "Mutual assent in a contract is destroyed by:",
  ["A low sale price", "Fraud, duress, menace, undue influence, or mistake",
   "Failure to record", "Absence of earnest money"], 1,
  "Genuine assent",
  "The four essentials are competent parties, mutual assent (offer and acceptance), consideration, and lawful object. Fraud or duress makes the contract VOIDABLE by the injured party."),
Q("contracts",
  "An offer terminates in all of the following ways EXCEPT:",
  ["Revocation before acceptance", "Death of the offeror",
   "The offeree telling a friend she will probably accept", "Lapse of the stated time"], 2,
  "Termination of an offer",
  "Acceptance must be communicated TO THE OFFEROR. Private intent changes nothing. Offers end by revocation, rejection, counteroffer, lapse, death or incapacity, or destruction of the property."),
Q("contracts",
  "A land contract (contract for deed) is characterized by the seller:",
  ["Delivering the deed at signing", "Retaining legal title until the price is paid",
   "Recording a satisfaction", "Providing title insurance"], 1,
  "Installment land contracts",
  "The buyer takes possession and equitable title while the seller keeps legal title as security. The buyer's risk is losing everything on default if the contract lacks protection."),
Q("contracts",
  "Liquidated damages differ from actual damages in that liquidated damages are:",
  ["Determined by a jury after trial", "Agreed to in advance in the contract",
   "Always three times the deposit", "Unenforceable in real estate"], 1,
  "Liquidated damages clauses",
  "Parties fix the amount in advance -- typically the earnest money -- to avoid litigating actual loss. Courts will void the clause if the sum is so large it functions as a penalty."),
Q("contracts",
  "If a buyer and seller sign an agreement to cancel their contract and restore each party to their prior position, this is:",
  ["Rescission", "Novation", "Assignment", "Reformation"], 0,
  "Discharge of contracts",
  "RESCISSION unwinds the contract and returns the parties to the status quo. REFORMATION is a court rewriting the document to reflect the parties' true intent -- usually to fix a scrivener's error."),

# ------------------------------------------------------------------ transfer
Q("transfer",
  "The deed offering the greatest protection to the grantee is the:",
  ["Quitclaim deed", "Special warranty deed", "General warranty deed", "Bargain and sale deed"], 2,
  "Deed types and covenants",
  "A general warranty deed warrants title against ALL defects, back through the entire chain, including before the grantor owned it. A SPECIAL warranty covers only the grantor's own period; a QUITCLAIM warrants nothing."),
Q("transfer",
  "The covenant in a general warranty deed promising the grantor will defend against lawful claims is:",
  ["Covenant of seisin", "Covenant against encumbrances",
   "Covenant of quiet enjoyment", "Covenant of further assurance"], 2,
  "The covenants of title",
  "Quiet enjoyment promises undisturbed possession and defense against lawful claims. SEISIN promises the grantor owns and can convey; FURTHER ASSURANCE promises to sign whatever documents are later needed."),
Q("transfer",
  "For a deed to be valid between grantor and grantee, it must be:",
  ["Recorded", "Delivered to and accepted by the grantee", "Notarized", "Signed by the grantee"], 1,
  "Requirements for a valid deed",
  "Title passes on DELIVERY AND ACCEPTANCE. Recording is not required for validity -- it gives CONSTRUCTIVE NOTICE to the world and establishes priority against later claimants."),
Q("transfer",
  "Recording a deed provides:",
  ["Actual notice to the grantee", "Constructive notice to the world",
   "A guarantee of clear title", "Proof of the purchase price"], 1,
  "Notice: actual vs. constructive",
  "Recording gives constructive (legal) notice -- everyone is charged with knowledge whether or not they looked. ACTUAL notice is what a person genuinely knows."),
Q("transfer",
  "Title insurance differs from other insurance in that it protects against:",
  ["Future losses from fire", "Defects that already existed when the policy was issued",
   "Declines in market value", "Tenant damage"], 1,
  "Title insurance",
  "Title insurance is retrospective: it covers hidden past defects such as forgeries, undisclosed heirs, and recording errors. It is paid once at closing rather than by ongoing premiums."),
Q("transfer",
  "Acquiring title by open, notorious, hostile, and continuous possession for the statutory period is:",
  ["Accretion", "Adverse possession", "Dedication", "Alienation"], 1,
  "Involuntary alienation",
  "Adverse possession requires possession that is open, notorious, hostile, actual, and continuous for the statutory term. Georgia's period is 20 years, or 7 years under color of title."),
Q("transfer",
  "A person who dies leaving a valid will dies:",
  ["Intestate", "Testate", "In escheat", "By devise"], 1,
  "Transfer at death",
  "TESTATE means with a will; INTESTATE means without, in which case state succession laws control. Real property passed by will is a DEVISE; personal property is a bequest or legacy."),
Q("transfer",
  "The gradual addition of land by waterborne deposits of soil is:",
  ["Erosion", "Accretion", "Avulsion", "Reliction"], 1,
  "Natural changes to land",
  "ACCRETION is gradual buildup (the new land is alluvion). AVULSION is sudden loss or addition; RELICTION is land exposed when water permanently recedes."),
Q("transfer",
  "A title search that traces ownership back through successive owners produces the:",
  ["Abstract of title", "Chain of title", "Title commitment", "Certificate of occupancy"], 1,
  "Chain of title and abstracts",
  "The CHAIN OF TITLE is the sequence of ownership. An ABSTRACT is the condensed written history of all recorded documents; the attorney's OPINION OF TITLE interprets it."),
Q("transfer",
  "A cloud on title is BEST removed by:",
  ["Recording a quitclaim deed from the claimant or a suit to quiet title",
   "Purchasing title insurance", "Obtaining a survey", "Filing a lis pendens"], 0,
  "Clearing title defects",
  "A quitclaim from whoever might hold the interest releases it; if the claimant will not sign, a quiet title action asks a court to settle ownership. A LIS PENDENS actually CREATES a cloud by giving notice of pending litigation."),
Q("transfer",
  "In most closings, real property taxes already paid by the seller beyond the closing date result in a:",
  ["Debit to the seller", "Credit to the seller and debit to the buyer",
   "Credit to both parties", "Debit to the lender"], 1,
  "Closing prorations and their direction",
  "The seller prepaid a benefit the buyer will enjoy, so the seller is reimbursed: seller CREDIT, buyer DEBIT. Unpaid taxes reverse it -- seller debit, buyer credit."),
Q("transfer",
  "A legal description that uses distances and compass bearings from a point of beginning is:",
  ["Lot and block", "Metes and bounds", "Rectangular survey", "Monument reference"], 1,
  "Legal description systems",
  "Metes (distances) and bounds (directions/boundaries) must return to the point of beginning to close. LOT AND BLOCK references a recorded plat and is the most common system in Georgia subdivisions."),

# ------------------------------------------------------------------ practice
Q("practice",
  "Two competing brokerages agree to charge the same commission rate. This is:",
  ["Legal if disclosed", "Illegal price fixing under antitrust law",
   "A permissible trade practice", "Allowed if the MLS approves"], 1,
  "Antitrust: price fixing",
  "Competitors setting prices together is a per se violation of the Sherman Act -- no defense, no disclosure cure. Commission rates must always be negotiated independently between a broker and a client."),
Q("practice",
  "Brokers agreeing not to show each other's listings to certain buyers is:",
  ["Steering", "A group boycott", "Market allocation", "Tie-in arrangement"], 1,
  "Antitrust violations",
  "A GROUP BOYCOTT is competitors conspiring to refuse dealing with someone. MARKET ALLOCATION is dividing territories or customer types; a TIE-IN conditions one sale on buying another product."),
Q("practice",
  "Directing buyers toward or away from neighborhoods based on race is:",
  ["Blockbusting", "Steering", "Redlining", "Puffing"], 1,
  "Fair housing violations",
  "STEERING channels people by protected class. BLOCKBUSTING induces panic selling by claiming a protected group is moving in; REDLINING is a lender refusing loans in an area based on its demographics."),
Q("practice",
  "The federal Fair Housing Act protects all of the following classes EXCEPT:",
  ["Familial status", "Handicap", "Source of income", "National origin"], 2,
  "The seven federal protected classes",
  "Race, color, religion, sex, national origin, familial status, and handicap. Source of income is protected in some states and cities but is NOT one of the seven federal classes."),
Q("practice",
  "An advertisement stating 'perfect for a mature Christian couple' violates fair housing because it indicates a preference based on:",
  ["Familial status and religion", "Marital status only", "Income", "Occupation"], 0,
  "Discriminatory advertising",
  "'Mature' signals age/familial status and 'Christian' signals religion. Advertising must describe the PROPERTY, not the desired occupant."),
Q("practice",
  "Under the Fair Housing Act, a landlord must permit a tenant with a disability to:",
  ["Make reasonable modifications at the tenant's expense",
   "Remodel the entire unit at the landlord's expense",
   "Break the lease without notice", "Sublet without approval"], 0,
  "Reasonable accommodation vs. modification",
  "MODIFICATIONS are physical changes, generally at the tenant's expense (and the tenant may be required to restore). ACCOMMODATIONS are changes to rules or policies -- like waiving a no-pets rule for a service animal -- at the landlord's expense."),
Q("practice",
  "A broker's trust account must be:",
  ["Combined with operating funds for efficiency", "Separate from the broker's own funds",
   "Held in the agent's name", "Interest-bearing in all cases"], 1,
  "Trust fund handling",
  "Client money must be segregated in a designated trust or escrow account. Mixing it with business funds is commingling, one of the most common license-law violations."),
Q("practice",
  "The Americans with Disabilities Act requires commercial property owners to:",
  ["Rebuild all facilities", "Remove barriers to public accommodations when readily achievable",
   "Give preference to disabled tenants", "Provide free parking"], 1,
  "ADA Title III",
  "Existing public accommodations must remove barriers where readily achievable -- cheap and easy relative to resources. New construction and alterations face stricter accessibility standards."),
Q("practice",
  "An independent contractor relationship between a broker and a salesperson means the broker:",
  ["Controls the hours and methods of work", "Controls the results but not the details of how work is done",
   "Must withhold income taxes", "Must provide health insurance"], 1,
  "Independent contractor vs. employee",
  "The broker sets goals and must supervise for license-law compliance, but does not dictate schedules or methods. The IRS safe harbor requires a license, pay based on output rather than hours, and a written IC agreement."),
Q("practice",
  "A net listing is one in which the broker:",
  ["Receives a flat fee", "Keeps everything above a price the seller sets",
   "Splits commission with the buyer's broker", "Charges by the hour"], 1,
  "Net listings and why they are disfavored",
  "Net listings invite the broker to profit at the client's expense and are illegal in many states. Georgia permits them only under strict disclosure conditions."),
Q("practice",
  "An open listing differs from an exclusive right to sell in that with an open listing:",
  ["Only one broker may market the property", "The seller owes no commission if the seller finds the buyer",
   "The listing must be in the MLS", "The term is unlimited"], 1,
  "Listing agreement types",
  "OPEN: many brokers, and the seller pays nothing if the seller sells it. EXCLUSIVE AGENCY: one broker, but the seller may still sell it themselves commission-free. EXCLUSIVE RIGHT TO SELL: the broker is paid no matter who sells."),
Q("practice",
  "A broker who deposits a buyer's earnest money into the brokerage operating account has committed:",
  ["Conversion only", "Commingling", "A permissible practice with disclosure", "Novation"], 1,
  "Commingling",
  "Placing trust funds in a business account is commingling as soon as it happens. If the broker then spends the money, it becomes conversion."),
Q("practice",
  "The 'do not call' rules generally allow a licensee to call a consumer on the registry if:",
  ["The number was found in the MLS", "The consumer has an established business relationship or gave written consent",
   "The call is made before 9 p.m.", "The licensee identifies themselves"], 1,
  "Telephone Consumer Protection Act",
  "An existing business relationship or express written consent permits the call. FSBO and expired-listing calls to registered numbers are a frequent source of violations."),
Q("practice",
  "Which activity may an unlicensed personal assistant legally perform?",
  ["Hold an open house alone and answer questions about terms",
   "Schedule appointments and prepare marketing materials for broker approval",
   "Negotiate a price reduction with a buyer", "Explain contract contingencies"], 1,
  "Unlicensed assistants",
  "Ministerial and clerical tasks are fine. Anything involving negotiating, soliciting, showing, or giving advice about terms requires a license -- and letting an assistant do it exposes the broker to discipline."),

# ---------------------------------------------------------- math (concepts)
Q("math",
  "A property sells for $250,000 with a 6% commission split 50/50 between two brokerages. Each brokerage receives:",
  ["$7,500", "$15,000", "$3,750", "$30,000"], 0,
  "Commission is a percentage of the SALE price",
  "$250,000 x 6% = $15,000 total; split 50/50 gives each brokerage $7,500. The most common error is stopping at the total commission."),
Q("math",
  "One acre contains how many square feet?",
  ["43,560", "5,280", "36,000", "640"], 0,
  "Core memorized conversions",
  "1 acre = 43,560 sq ft. Also memorize: 1 mile = 5,280 feet; 1 section = 640 acres = 1 square mile; 36 sections = 1 township."),
Q("math",
  "A buyer pays 2 discount points on a $200,000 loan. The cost is:",
  ["$400", "$2,000", "$4,000", "$40,000"], 2,
  "Points are a percentage of the LOAN",
  "One point = 1% of the loan = $2,000, so 2 points = $4,000. The classic trap is applying points to the sale price instead of the loan amount."),
Q("math",
  "A home appraises at $300,000 and the buyer obtains an 80% LTV loan. The down payment on a $310,000 purchase price is:",
  ["$60,000", "$62,000", "$70,000", "$50,000"], 2,
  "Lenders lend on the LESSER of price or appraised value",
  "Loan = 80% x $300,000 (the lower figure) = $240,000. Down payment = $310,000 - $240,000 = $70,000. The buyer must cover the $10,000 appraisal gap in cash."),
Q("math",
  "Annual taxes are $3,600, paid in arrears. Closing is on July 1 in a 360-day year. The seller's share is approximately:",
  ["$1,800", "$1,500", "$2,100", "$300"], 0,
  "Proration on the closing calendar",
  "Six months elapsed x $300/month = $1,800 owed by the seller and credited to the buyer, who will pay the full bill later. Unpaid taxes always produce a seller debit."),
Q("math",
  "A seller wants to net $190,000 after a 5% commission and no other costs. The sale price must be:",
  ["$199,500", "$200,000", "$180,500", "$209,000"], 1,
  "Net-to-seller problems require division",
  "$190,000 / 0.95 = $200,000. Adding 5% to $190,000 gives $199,500 -- the wrong answer the exam always offers, because 5% of the higher price is more than 5% of the net."),
]
