# -*- coding: utf-8 -*-
"""National bank, part A: ownership, land use, valuation, financing."""

def Q(topic, q, choices, answer, concept, explain):
    return {"topic": "national/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain}

ROWS = [
# ---------------------------------------------------------------- ownership
Q("ownership",
  "A tenant's lease expires and the landlord takes back possession. The landlord's interest during the lease term was a:",
  ["Leasehold estate", "Leased fee estate", "Life estate", "Estate at sufferance"], 1,
  "Freehold vs. leasehold interests",
  "The LANDLORD holds the leased fee estate (ownership subject to the lease); the TENANT holds the leasehold. A tenant who stays past expiration without permission creates an estate at sufferance, but that describes the tenant, not the landlord."),
Q("ownership",
  "Three people own property as joint tenants. One sells her interest to a stranger. The new owner holds title as a:",
  ["Joint tenant with the other two", "Tenant in common with the other two",
   "Tenant by the entirety", "Trustee for the other two"], 1,
  "Severance of joint tenancy",
  "Selling a joint tenancy interest severs the four unities as to that share. The buyer takes as a tenant in common; the two remaining original owners stay joint tenants with each other and keep survivorship between themselves."),
Q("ownership",
  "Which of these is the MOST complete form of ownership recognized in law?",
  ["Fee simple defeasible", "Life estate pur autre vie",
   "Fee simple absolute", "Leasehold for 99 years"], 2,
  "The bundle of rights and degrees of ownership",
  "Fee simple absolute is ownership without condition or time limit -- the entire bundle of rights. A defeasible fee can be lost if a condition occurs, and a life estate ends at a death."),
Q("ownership",
  "A built-in dishwasher installed by the seller is BEST classified at closing as:",
  ["Personal property the seller may remove", "A trade fixture",
   "A fixture that conveys with the real estate", "An emblement"], 2,
  "Fixtures: personal property becoming real property",
  "Courts look at method of annexation, adaptation to the property, and intent. A built-in appliance is annexed and adapted, so it conveys unless the contract excludes it. Trade fixtures belong to a commercial TENANT and are removable."),
Q("ownership",
  "In a condominium, the individual owner holds fee simple title to the unit and owns the common elements:",
  ["As a tenant in common with the other unit owners", "As a joint tenant with the association",
   "Not at all -- the association owns them", "Under a proprietary lease"], 0,
  "Condominium vs. cooperative ownership",
  "Condo owners own their unit in fee plus an undivided tenancy-in-common interest in common elements. A COOPERATIVE is the one where a corporation owns the building and the resident holds stock plus a proprietary lease."),
Q("ownership",
  "A property abuts a navigable river. The owner's rights to use the water are called:",
  ["Littoral rights", "Riparian rights", "Prior appropriation", "Percolating rights"], 1,
  "Water rights",
  "Riparian rights attach to flowing water -- rivers and streams. LITTORAL rights attach to static bodies: lakes, seas, oceans. Prior appropriation is the western doctrine where use is granted by permit regardless of adjacency."),
Q("ownership",
  "A husband and wife hold title with right of survivorship that neither can defeat by a separate conveyance. This is:",
  ["Tenancy in common", "Joint tenancy", "Tenancy by the entirety", "Community property"], 2,
  "Forms of co-ownership between spouses",
  "Tenancy by the entirety is the marital form where neither spouse can convey separately and survivorship is automatic. Note that Georgia does NOT recognize tenancy by the entirety -- a fact the state portion may test."),
Q("ownership",
  "An owner grants a neighbor the right to cross her land to reach a road. The neighbor's parcel is the:",
  ["Servient tenement", "Dominant tenement", "Encroaching parcel", "Licensed parcel"], 1,
  "Easement appurtenant terminology",
  "The parcel that BENEFITS is the dominant tenement; the parcel burdened by the crossing is the servient tenement. An easement appurtenant runs with the land and passes to later owners."),
Q("ownership",
  "A life tenant may do all of the following EXCEPT:",
  ["Lease the property", "Mortgage the life estate",
   "Devise the property by will", "Collect rents from the property"], 2,
  "Rights and limits of a life estate",
  "A life estate ends at the measuring life's death, so there is nothing left to pass by will -- it cannot be devised. The life tenant may otherwise use, lease, and encumber the interest, subject to not committing waste."),
Q("ownership",
  "A fence built two feet onto the neighbor's lot is an example of:",
  ["An easement by prescription", "An encroachment", "A license", "A deed restriction"], 1,
  "Encroachments and how they are discovered",
  "An unauthorized physical intrusion onto another's land is an encroachment, typically revealed by a survey. If it continues openly for the statutory period it may ripen into a prescriptive easement, but the intrusion itself is the encroachment."),
Q("ownership",
  "Ownership of a timeshare that gives the buyer a deeded fractional interest is a:",
  ["Right-to-use interest", "Timeshare estate", "Leasehold interest", "License"], 1,
  "Timeshare estates vs. right-to-use",
  "A timeshare ESTATE conveys a real property interest by deed. A right-to-use timeshare is only a contract right to occupy for a term, with no ownership interest -- it expires when the contract ends."),
Q("ownership",
  "A homeowner's association enforces a rule barring commercial signs. The authority for that rule comes from:",
  ["State police power", "Zoning ordinance",
   "Recorded covenants, conditions and restrictions", "The doctrine of eminent domain"], 2,
  "Private land use control vs. public",
  "CC&Rs are PRIVATE restrictions recorded against the subdivision and enforced by the HOA or owners through injunction. Zoning and police power are PUBLIC controls enforced by government."),

# ----------------------------------------------------------------- land use
Q("landuse",
  "A city rezones an area from commercial to residential. An existing store may continue operating as a:",
  ["Variance", "Special use", "Nonconforming use", "Spot zoning"], 2,
  "Nonconforming use ('grandfathering')",
  "A lawful use that predates the new zoning may continue as a legal nonconforming use. A VARIANCE is permission to deviate granted on hardship; a SPECIAL USE permit allows a listed conditional use like a church or school."),
Q("landuse",
  "Government's power to take private property for public use upon payment of just compensation is:",
  ["Escheat", "Eminent domain", "Police power", "Condemnation"], 1,
  "The four government powers over land (PETE)",
  "EMINENT DOMAIN is the power itself; CONDEMNATION is the legal proceeding that exercises it. Police power regulates without paying (zoning, codes); escheat passes property to the state when an owner dies with no heirs or will."),
Q("landuse",
  "A lot is too narrow to meet the setback requirement. The owner should seek a:",
  ["Variance", "Nonconforming use permit", "Rezoning", "Conditional use permit"], 0,
  "Variance as relief from a dimensional requirement",
  "A variance permits a deviation from a dimensional rule when strict compliance creates a unique hardship not caused by the owner. Rezoning changes the classification for everyone; a conditional use permits a different TYPE of use."),
Q("landuse",
  "Rezoning a single parcel for the benefit of one owner, inconsistent with the surrounding area, is:",
  ["Downzoning", "Spot zoning", "Inverse condemnation", "A buffer zone"], 1,
  "Illegal zoning practices",
  "Spot zoning singles out one parcel for treatment inconsistent with the comprehensive plan and is generally invalid. Downzoning reduces intensity across an area; inverse condemnation is an owner's suit claiming a regulation effectively took the property."),
Q("landuse",
  "The primary purpose of a building permit and subsequent inspections is to:",
  ["Raise revenue for the municipality", "Ensure compliance with building codes for public safety",
   "Establish the property's assessed value", "Confirm marketable title"], 1,
  "Building codes as an exercise of police power",
  "Codes and permits exist to protect public health and safety. The certificate of OCCUPANCY issued at the end confirms the structure may lawfully be occupied."),
Q("landuse",
  "A subdivision developer records a plat with restrictions limiting lots to single-family homes. These restrictions are enforceable by:",
  ["The zoning board only", "Any lot owner in the subdivision",
   "The state real estate commission", "Only the original developer"], 1,
  "Enforcement of private deed restrictions",
  "Restrictive covenants run with the land and any benefited lot owner may sue to enforce them, usually by injunction. Government bodies do not enforce private covenants."),
Q("landuse",
  "A comprehensive (master) plan differs from zoning in that the plan:",
  ["Has the force of law immediately", "Is a long-range policy guide for future development",
   "Applies only to commercial districts", "Replaces the need for building codes"], 1,
  "Planning vs. zoning",
  "The comprehensive plan states long-term goals; ZONING ordinances are the legal tool that implements the plan parcel by parcel."),
Q("landuse",
  "Land that reverts to the state when an owner dies leaving no heirs and no will passes by:",
  ["Eminent domain", "Escheat", "Adverse possession", "Dedication"], 1,
  "Escheat",
  "Escheat prevents land from being ownerless. It applies only when there is neither a will nor any locatable heir."),
Q("landuse",
  "An environmental impact statement is MOST likely required when:",
  ["Any home is resold", "A federal action may significantly affect the environment",
   "A property is refinanced", "A lease exceeds one year"], 1,
  "Environmental review under NEPA",
  "NEPA requires an EIS for major FEDERAL actions significantly affecting the human environment -- typically large developments involving federal funding, permits, or land."),
Q("landuse",
  "The strip of land separating incompatible zoning districts, often landscaped, is a:",
  ["Setback", "Buffer zone", "Right-of-way", "Easement in gross"], 1,
  "Zoning transition devices",
  "A buffer zone cushions between, say, industrial and residential districts. A SETBACK is the required distance from a lot line to a structure."),

# ---------------------------------------------------------------- valuation
Q("valuation",
  "An appraiser valuing a 40-year-old church would rely MOST heavily on the:",
  ["Sales comparison approach", "Income approach", "Cost approach", "Gross rent multiplier"], 2,
  "Choosing the appropriate approach to value",
  "Special-purpose properties rarely sell and produce no rent, so the COST approach (reproduction cost less depreciation plus land) is most reliable. Sales comparison needs comparables; income needs rental income."),
Q("valuation",
  "The principle stating that a property's maximum value tends to be set by the cost of an equally desirable substitute is:",
  ["Substitution", "Progression", "Conformity", "Anticipation"], 0,
  "Appraisal principles",
  "SUBSTITUTION underlies the whole sales comparison approach. Progression is a modest home gaining value near larger ones; anticipation is value based on expected future benefits."),
Q("valuation",
  "A comparable sold for $310,000 but has one fewer bathroom than the subject, worth $9,000. The adjusted sale price is:",
  ["$301,000", "$310,000", "$319,000", "$328,000"], 2,
  "Direction of adjustments in the sales comparison approach",
  "Always adjust the COMPARABLE, never the subject. The comp is inferior, so ADD the value of the missing feature: $310,000 + $9,000 = $319,000. Memory hook: CIA -- Comp Inferior, Add."),
Q("valuation",
  "A modest home located among much larger, expensive homes tends to gain value. This illustrates:",
  ["Regression", "Progression", "Contribution", "Plottage"], 1,
  "Progression and regression",
  "PROGRESSION: the lesser property is pulled up by superior neighbors. REGRESSION is the reverse -- a superior property dragged down by lesser surroundings."),
Q("valuation",
  "Loss in value because a home has only one bathroom and buyers expect two is:",
  ["Physical deterioration", "Functional obsolescence",
   "External obsolescence", "Economic appreciation"], 1,
  "The three types of depreciation",
  "FUNCTIONAL obsolescence is a defect within the structure's design or utility. Physical deterioration is wear and tear; EXTERNAL obsolescence comes from outside the property line and is always incurable."),
Q("valuation",
  "A highway is built next to a residence, reducing its value. This is:",
  ["Curable physical deterioration", "Functional obsolescence",
   "External obsolescence", "Deferred maintenance"], 2,
  "External (economic) obsolescence",
  "The cause is outside the property boundaries and beyond the owner's control, so it is external obsolescence -- by definition incurable, because the owner cannot remove the highway."),
Q("valuation",
  "In the income approach, a property with $60,000 net operating income and a 8% capitalization rate is valued at:",
  ["$480,000", "$600,000", "$750,000", "$4,800,000"], 2,
  "IRV formula in the income approach",
  "Value = NOI / Rate = $60,000 / 0.08 = $750,000. Remember IRV: Income = Rate x Value. Note that cap rate and value move INVERSELY -- a higher cap rate means lower value."),
Q("valuation",
  "The highest and best use of a property is the use that is:",
  ["Most profitable regardless of legality", "Legally permitted, physically possible, financially feasible, and maximally productive",
   "The current use in all cases", "Chosen by the owner"], 1,
  "Highest and best use",
  "All four tests must be met, and legality comes first -- an illegal use can never be highest and best no matter how profitable."),
Q("valuation",
  "A broker preparing a CMA for a seller is:",
  ["Performing an appraisal requiring a license", "Estimating market value using recent comparable sales",
   "Required to use the cost approach", "Determining assessed value for taxation"], 1,
  "CMA vs. appraisal",
  "A CMA is a broker's pricing opinion built from comparables to help set a list price. It is NOT an appraisal, may not be represented as one, and does not require an appraiser's license."),
Q("valuation",
  "Market value differs from market price in that market value is:",
  ["What the property actually sold for", "The most probable price under normal, arm's-length conditions",
   "Always equal to assessed value", "The seller's asking price"], 1,
  "Value vs. price vs. cost",
  "MARKET VALUE is an opinion of the most probable price assuming an informed buyer and seller, adequate exposure, and no duress. MARKET PRICE is the historical fact of what a property actually sold for -- which may reflect a distress sale."),
Q("valuation",
  "Combining two adjacent lots so the whole is worth more than the sum of the parts creates:",
  ["Plottage increment", "Progression", "Assemblage cost", "Contribution"], 0,
  "Assemblage and plottage",
  "ASSEMBLAGE is the act of joining parcels; PLOTTAGE (or plottage increment) is the added value that results. The exam frequently pairs these two terms as distractors."),
Q("valuation",
  "The appraisal step in which the three approaches are weighted into a single conclusion is:",
  ["Averaging", "Reconciliation", "Correlation of assessments", "Adjustment"], 1,
  "The appraisal process",
  "Reconciliation weighs each approach by its reliability for that property type. An appraiser never simply averages the three values."),
]
