# -*- coding: utf-8 -*-
"""National bank, HARD tier B: agency, disclosures, contracts, transfer, practice."""

def Q(topic, q, choices, answer, concept, explain):
    return {"topic": "national/" + topic, "q": q, "choices": choices,
            "answer": answer, "concept": concept, "explain": explain, "difficulty": 2}

ROWS = [
# ------------------------------------------------------------------- agency
Q("agency",
  "A listing agent learns from the seller, in confidence, that the seller must move for a job in 30 days. A buyer's agent asks why the seller is selling. The listing agent should:",
  ["Answer truthfully, since honesty is owed to customers",
   "Decline to answer, saying the seller has not authorized disclosure of motivation",
   "Say the seller has no particular reason", "Answer only if the buyer submits an offer first"], 1,
  "Confidentiality vs. honesty",
  "Motivation is confidential, not a material defect, so it stays private. But honesty forbids the affirmative lie in option C -- the agent must decline rather than misstate. Declining to answer is not deceit; inventing an answer is."),
Q("agency",
  "An agent's listing expires unsold. Six months later the agent mentions to a friend that the former seller had been desperate. This is:",
  ["Permissible, since the agency ended",
   "A breach -- confidentiality survives termination of the agency",
   "Permissible if the property has since sold", "A breach only if it causes provable damage"], 1,
  "Which duties survive termination",
  "Accounting and CONFIDENTIALITY survive the end of the relationship indefinitely. Loyalty, obedience, disclosure, and reasonable care end with the agency. Damage is not required for the breach to exist."),
Q("agency",
  "A broker represents the seller. The broker's own son wants to buy the property. The broker's FIRST obligation is to:",
  ["Refuse to present the son's offer",
   "Disclose the relationship to the seller in writing before presenting the offer",
   "Present the offer without comment, as with any other",
   "Resign the listing immediately"], 1,
  "Disclosure of a personal interest",
  "A family or financial interest in a buyer is a material conflict the principal must know about, disclosed before the offer is considered. The broker must still present all offers -- refusing to present one breaches the duty. Resigning may follow, but disclosure comes first."),
Q("agency",
  "A buyer's agent shows a property and the buyer asks, 'Is this a good price?' The agent has a written buyer agency agreement. The agent should:",
  ["Decline to advise on price to avoid liability",
   "Give an informed opinion supported by comparable sales",
   "Repeat the listing agent's opinion", "Say only that the seller set the price"], 1,
  "Advocacy is the point of representation",
  "A client is owed advice, not just information. Withholding a price opinion from a CLIENT under-serves the fiduciary-style duty of reasonable care and skill. The agent who declines is behaving as though the buyer were a customer."),
Q("agency",
  "A seller's agent receives two offers. The higher offer is from an unrepresented buyer, meaning the agent would keep the whole commission. The agent must:",
  ["Present both offers and disclose the compensation difference to the seller",
   "Present only the higher offer, since it serves the seller best",
   "Present both without mentioning compensation", "Let the seller's attorney decide"], 0,
  "Presenting all offers plus conflict disclosure",
  "All offers go to the seller. Additionally, the prospect of a larger commission on one offer is a conflict of interest the principal is entitled to know about, so the agent discloses it and lets the seller weigh it. Silence here is the trap answer."),
Q("agency",
  "An unlicensed assistant, alone at an open house, answers a visitor's question about whether the seller would take less. The broker's exposure is:",
  ["None, since the assistant is not licensed",
   "Liability for unlicensed activity and breach of confidentiality by the firm",
   "Limited to a warning letter", "Only the assistant's problem"], 1,
  "Supervision and unlicensed activity",
  "Discussing terms is licensed activity, and the answer also leaked the seller's negotiating position. The broker is responsible for supervising assistants; letting one host an open house unaccompanied and field substantive questions is a classic disciplinary case."),

# --------------------------------------------------------------- disclosures
Q("disclosures",
  "A seller repaired a chronic basement leak two years ago and it has not recurred. On the disclosure form the seller should:",
  ["Say nothing, since the condition is fixed",
   "Disclose the past problem and the repair",
   "Disclose only if the buyer's inspector finds evidence",
   "Note it only if the repair is under warranty"], 1,
  "Past defects are still material",
  "A history of water intrusion is material to value and desirability even after repair, because it bears on recurrence risk and insurability. Disclosing the problem AND the fix protects the seller; silence is the classic post-closing lawsuit."),
Q("disclosures",
  "A buyer's agent sees a fresh paint patch on a ceiling and a faint stain edge. The agent should:",
  ["Say nothing, as the agent is not an inspector",
   "Point it out to the buyer and recommend the inspector examine it",
   "Ask the listing agent to repaint it",
   "Assume the seller disclosed everything material"], 1,
  "No duty to discover, but no license to ignore",
  "Agents are not inspectors and have no duty to hunt for defects -- but a visible red flag they actually observe must be passed on. Seeing it and staying silent converts 'no duty to discover' into concealment of something known."),
Q("disclosures",
  "A property built in 1975 is sold. The seller has never tested for lead and knows of no hazard. The seller must:",
  ["Test the property before closing",
   "Disclose the absence of knowledge, give the pamphlet, and allow the 10-day opportunity",
   "Do nothing, because no hazard is known", "Disclose only if the buyer has children"], 1,
  "Lead disclosure when nothing is known",
  "The federal rule requires the disclosure form, records, EPA pamphlet, and 10-day testing window on all pre-1978 target housing. Having no knowledge is a permitted answer on the form -- but the process still applies. Sellers are never required to test."),
Q("disclosures",
  "A buyer asks a licensee whether a nearby group home houses people with disabilities. The licensee should:",
  ["Answer factually if the licensee knows",
   "Decline, explaining that the question involves a protected class",
   "Refer the buyer to the seller", "Answer only in writing"], 1,
  "Fair housing overrides the impulse to be helpful",
  "Handicap is a protected class, so answering would facilitate discriminatory steering regardless of the licensee's intent. The right move is to decline and direct the buyer to publicly available sources they can research themselves."),
Q("disclosures",
  "A licensee discovers the seller's disclosure understates the age of the roof by twelve years. The seller refuses to correct it. The licensee should:",
  ["Present the form as the seller wrote it, since it is the seller's statement",
   "Refuse to pass on information known to be false, and withdraw if the seller persists",
   "Correct the form personally", "Disclose the truth only to the buyer's agent"], 1,
  "A licensee cannot transmit known falsehoods",
  "The form belongs to the seller, but the licensee cannot become the conduit for a misrepresentation they know to be false -- that is participation in fraud. The licensee never alters the seller's form; if the seller will not fix it, the engagement must end."),

# ---------------------------------------------------------------- contracts
Q("contracts",
  "A buyer's offer says acceptance must be received by 5 p.m. Friday. The seller signs at 3 p.m. Friday but the acceptance is not delivered until Saturday morning. There is:",
  ["A binding contract, because the seller signed in time",
   "No contract, because acceptance was not communicated within the deadline",
   "A binding contract dated Saturday",
   "A counteroffer the buyer may accept"], 1,
  "Acceptance is effective on communication",
  "Signing is not acceptance -- the offeror must receive it within the stated time. Late delivery means the offer lapsed. The late acceptance may operate as a new offer the buyer can accept, but no contract exists on the original terms."),
Q("contracts",
  "A contract is contingent on the buyer obtaining financing at no more than 6.5%. The buyer is approved at 6.75% and terminates. The seller argues bad faith. The buyer will MOST likely:",
  ["Lose, because the buyer was approved", "Prevail, because the approval did not meet the stated term",
   "Lose, because 0.25% is immaterial", "Prevail only if the buyer applied to three lenders"], 1,
  "Contingencies are read as written",
  "The condition specified a rate ceiling, and an approval above it does not satisfy it. Courts enforce the stated terms; materiality is not re-argued after the parties fixed the number. The buyer must still have applied in good faith, which a single genuine application satisfies."),
Q("contracts",
  "A seller and buyer sign a contract. Before closing the house burns down. In a state that has adopted the Uniform Vendor and Purchaser Risk Act, the loss falls on the:",
  ["Buyer, who holds equitable title", "Seller, because possession and title had not passed",
   "Insurer only", "Parties equally"], 1,
  "Equitable conversion vs. the Risk Act",
  "Under the older doctrine of equitable conversion the BUYER bore the risk from contract signing. The Uniform Act reverses that: risk stays with the seller until title or possession transfers. Knowing which rule the question invokes is the whole point."),
Q("contracts",
  "A buyer assigns her purchase contract to a third party. The contract is silent on assignment. The seller objects. Generally:",
  ["The assignment is void without consent",
   "The assignment is valid, and the original buyer remains secondarily liable",
   "The seller may terminate the contract", "The assignment converts the deal to a novation"], 1,
  "Assignability of real estate contracts",
  "Real estate purchase contracts are assignable unless they say otherwise. The assignee gains the rights; the assignor stays secondarily liable unless the seller agrees to a novation. Personal-service contracts are the category that resists assignment."),
Q("contracts",
  "An option agreement gives a tenant the right to buy for $500,000 within one year, for $5,000 consideration. Six months in, the owner sells to someone else. The tenant's BEST remedy is:",
  ["Recovery of the $5,000 only", "Specific performance against the owner and the buyer if the buyer had notice",
   "Nothing, since options are revocable", "Damages capped at the option price"], 1,
  "Options create an enforceable interest",
  "An option supported by consideration is a binding contract, and land is unique, so specific performance is available. A later buyer with actual or constructive notice (a recorded option) takes subject to it. Options are not revocable once consideration is paid."),
Q("contracts",
  "A contract states 'closing on or before June 30' with no time-is-of-the-essence clause. The buyer is ready on July 3. The seller declares a breach. The seller will MOST likely:",
  ["Prevail, because the date passed", "Not prevail, because performance within a reasonable time is allowed",
   "Prevail only if damages are shown", "Not prevail, because closing dates are unenforceable"], 1,
  "Effect of omitting time-is-of-the-essence",
  "Without the clause, courts permit performance within a reasonable time and three days is ordinarily reasonable. The clause exists precisely to convert a date into a hard deadline. Closing dates are enforceable -- just not automatically strict."),
Q("contracts",
  "Two parties sign a contract that misstates the parcel number due to a typing error, though both intended the same lot. The proper remedy is:",
  ["Rescission", "Reformation", "Specific performance as written", "Novation"], 1,
  "Reformation for scrivener's error",
  "Reformation asks a court to rewrite the document to reflect the parties' actual agreement. Rescission would unwind a deal both sides want; enforcing the erroneous description would convey the wrong lot."),

# ----------------------------------------------------------------- transfer
Q("transfer",
  "A buyer records a deed on Monday. An earlier buyer of the same parcel, who had paid and taken possession, records on Wednesday. In a race-notice state the winner is:",
  ["The Monday recorder, if that buyer had no notice of the earlier sale",
   "The earlier buyer, because that purchase came first",
   "The Wednesday recorder, because possession controls", "Neither -- the deeds cancel"], 0,
  "Race-notice recording acts",
  "A race-notice statute protects the party who both takes WITHOUT NOTICE and records FIRST. The catch: open possession by the earlier buyer can itself be constructive notice, which would defeat the Monday recorder. The stem's 'no notice' condition is what decides it."),
Q("transfer",
  "A general warranty deed's covenant of seisin is breached. When does the breach occur?",
  ["At the moment of conveyance", "Only when the grantee is evicted",
   "When the grantee resells", "When the defect is recorded"], 0,
  "Present vs. future covenants",
  "Seisin, right to convey, and against encumbrances are PRESENT covenants -- breached, if at all, at delivery, which starts the limitations clock then. Quiet enjoyment, warranty, and further assurances are FUTURE covenants, breached only on later disturbance."),
Q("transfer",
  "A grantor hands a signed deed to an escrow agent with instructions to deliver on payment. The grantor dies before payment. The deed:",
  ["Is void, because delivery requires a living grantor",
   "Is valid on payment, relating back to the original deposit",
   "Passes only a life estate", "Must be re-executed by the estate"], 1,
  "Relation-back doctrine in escrow delivery",
  "Once a grantor deposits a deed in escrow beyond recall, delivery relates back to the deposit date when the condition is met. This defeats the argument that death revoked it. The doctrine exists precisely to prevent death from unwinding completed bargains."),
Q("transfer",
  "A title commitment lists an unreleased mortgage from 1978 as an exception. To convey marketable title the seller must:",
  ["Buy title insurance covering it", "Obtain and record a release or satisfaction",
   "Disclose it and proceed", "Wait for the statute of limitations"], 1,
  "Marketable title and Schedule B exceptions",
  "An exception is a defect the policy will NOT cover, so insurance does not solve it. Marketable title requires clearing the lien of record with a recorded release. A buyer cannot be forced to accept title subject to an undischarged mortgage."),
Q("transfer",
  "An adverse possessor occupies land for the statutory period but pays no taxes, and the state's statute requires tax payment. The possessor:",
  ["Acquires title anyway, since possession is the main element",
   "Fails, because every statutory element must be satisfied",
   "Acquires a prescriptive easement instead", "Acquires title after twice the period"], 1,
  "Adverse possession is all-elements",
  "Every element of the statute must be met -- possession that is open, notorious, hostile, actual, continuous for the period, plus any state-specific requirement like tax payment or color of title. Missing one defeats the claim entirely."),

# ----------------------------------------------------------------- practice
Q("practice",
  "A brokerage tells its agents never to quote a commission below 5%, and the firm's competitors independently do the same. The brokerage has:",
  ["Committed price fixing with its competitors",
   "Set a lawful internal company policy",
   "Violated antitrust by publishing a rate", "Committed a group boycott"], 1,
  "Company policy vs. conspiracy",
  "A single firm may set its own rates -- that is competition, not conspiracy. Antitrust requires an AGREEMENT between competitors. Parallel behavior alone is not proof; what would make it illegal is evidence the firms coordinated."),
Q("practice",
  "A landlord's ad says 'quiet building, ideal for professionals, no children under 12.' The clearest violation involves:",
  ["Familial status", "National origin", "Handicap", "Nothing -- occupancy limits are lawful"], 0,
  "Reading an ad for the actual violation",
  "'No children under 12' is a direct familial status violation. 'Ideal for professionals' is a weaker signal about income or occupation, which is not federally protected. Reasonable OCCUPANCY limits by number of persons are lawful, but limits by age of occupant are not."),
Q("practice",
  "A property manager applies a rule requiring all applicants to have income of three times the rent. Statistically it screens out a protected class at a much higher rate. This may be challenged as:",
  ["Intentional discrimination only", "Disparate impact, even without discriminatory intent",
   "Not actionable, since the rule is neutral", "A steering violation"], 1,
  "Disparate impact",
  "A facially neutral policy that falls disproportionately on a protected class can violate fair housing law without any intent to discriminate. The landlord's defense is that the rule serves a substantial, legitimate business need that no less discriminatory rule would serve."),
Q("practice",
  "A broker holds a $10,000 earnest money deposit. Buyer and seller both demand it after a failed closing. The broker should:",
  ["Release it to whoever demands first",
   "Continue holding it and use interpleader or the state's prescribed dispute procedure",
   "Split it evenly between them", "Keep it as compensation for the failed sale"], 1,
  "Disputed trust funds",
  "A broker holding disputed funds must not choose sides. The safe course is to hold and let a court (interpleader) or the state-prescribed process decide. Releasing, splitting, or keeping the money all expose the broker to a conversion claim."),
Q("practice",
  "A licensee advertises 'Just sold! Call me to sell yours' with a photo of a property listed and sold by another firm. This is MOST directly:",
  ["Puffing", "A misleading advertisement misrepresenting the licensee's involvement",
   "A permissible market update", "A RESPA violation"], 1,
  "Truthful advertising",
  "Implying credit for another firm's transaction misrepresents the licensee's role. Market-update advertising is legitimate only when it clearly attributes the sale and does not suggest the advertiser handled it."),
]
