# -*- coding: utf-8 -*-
"""Vocabulary the notes explain in passing but never defined in the term list.

Found by matching every "Term - explanation" bullet in the study notes against
the vocabulary of every category, then writing a proper entry for the ones with
no equivalent anywhere. Merged in by tools/build_study.py.
"""

EXTRA = {
"national/ownership": [
  ("Fee simple defeasible", "Ownership that can be lost if a stated condition occurs."),
  ("Estate for years", "A leasehold with a fixed start and end date; it ends automatically with no notice."),
  ("Periodic estate", "A leasehold that renews itself, such as month to month, until someone gives notice."),
  ("Estate at will", "A leasehold continuing at the pleasure of both parties, endable at any time."),
  ("Community property", "A marital ownership form used in nine states. Georgia is not one of them."),
  ("Condominium", "Fee simple ownership of a unit plus an undivided tenancy-in-common share of the common elements."),
  ("Cooperative", "A corporation owns the building; the resident owns shares of stock plus a proprietary lease."),
  ("Timeshare estate", "A deeded fractional real property interest, as opposed to a contractual right to use."),
  ("Easement appurtenant", "An easement benefiting an adjoining parcel; it runs with the land to later owners."),
  ("Easement by necessity", "An easement implied when a seller's own severance leaves a parcel landlocked."),
  ("Easement by prescription", "An easement acquired by long, open, hostile use over the statutory period."),
  ("Prior appropriation", "The western water doctrine granting use by permit regardless of whether you adjoin the water."),
  ("Annexation", "How firmly an item is attached to the property; one of the three fixture tests."),
  ("Adaptation", "How specifically an item is fitted to the property; one of the three fixture tests."),
  ("Intent", "What the person attaching an item meant to do; the fixture test carrying the most weight."),
  ("CC&Rs", "Covenants, conditions and restrictions: recorded private controls enforceable by benefited owners."),
],
"national/financing": [
  ("Prepayment penalty", "A charge imposed for paying a loan off early."),
  ("Partial release", "A blanket-mortgage clause freeing individual parcels as portions of the debt are paid."),
  ("Partially amortized loan", "Level payments that do not retire the debt, leaving a balloon at maturity."),
  ("Term loan", "A straight loan of interest only, with the whole principal due at the end."),
  ("Conventional loan", "A loan that is not government insured or guaranteed."),
  ("Conforming loan", "A conventional loan meeting Fannie Mae and Freddie Mac purchase limits."),
  ("FHA loan", "A loan insured by the Federal Housing Administration, with a low down payment and required MIP."),
  ("Adjustable-rate mortgage", "A loan whose rate is index plus margin, adjusted periodically within caps."),
  ("Package mortgage", "A loan secured by real property together with personal property."),
  ("Open-end mortgage", "A loan permitting the borrower to re-borrow up to a set limit."),
  ("Construction loan", "Short-term financing disbursed in draws as building progresses."),
  ("Loan Estimate", "The TRID disclosure due within three business days of application."),
],
"national/agency": [
  ("Obedience", "The duty to follow a client's lawful instructions, and to refuse unlawful ones."),
  ("Loyalty", "The duty to put the client's interests ahead of the agent's own."),
  ("Confidentiality", "The duty to protect a client's private information; it survives the end of the relationship."),
  ("Accounting", "The duty to account for all money and documents; it survives closing."),
  ("Reasonable care", "The duty to act with the competence and skill expected of a licensee."),
  ("Undisclosed personal interest", "A family or financial stake in a party that must be disclosed in writing before an offer is considered."),
],
"national/valuation": [
  ("Demand", "Buyers who want the property and can pay for it; the D in DUST."),
  ("Utility", "The property's capacity to satisfy a need; the U in DUST."),
  ("Scarcity", "Limited supply relative to demand; the S in DUST."),
  ("Transferability", "The ability to convey title; the T in DUST."),
  ("Sales comparison approach", "Valuing by comparison with recent sales of similar properties."),
  ("Cost approach", "Reproduction or replacement cost, less depreciation, plus land value."),
  ("Income approach", "Converting a property's income into value, using Value = NOI / rate."),
],
"national/contracts": [
  ("Competent parties", "Parties of legal age and sound mind, a requirement of a valid contract."),
  ("Lawful object", "A legal purpose, without which a contract is void."),
  ("Valid contract", "One meeting all requirements and binding on both parties."),
  ("Compensatory damages", "Money awarded for the actual loss proven, as opposed to an agreed sum."),
],
"national/transfer": [
  ("Bargain and sale deed", "A deed implying the grantor holds title but giving no warranty."),
  ("Present covenants", "Seisin, right to convey, and against encumbrances; breached at delivery if at all."),
  ("Future covenants", "Quiet enjoyment, warranty, and further assurance; breached only on a later disturbance."),
  ("Opinion of title", "An attorney's written interpretation of the abstract of title."),
  ("Rectangular survey", "The government survey system of townships, ranges and sections. Georgia does not use it."),
  ("Title insurance", "Cover against defects that already existed when the policy issued - forgery, undisclosed heirs, recording errors. Paid once."),
  ("Owner's policy", "Title insurance protecting the buyer's interest, as distinct from the lender's policy."),
  ("Township", "Thirty-six sections, six miles square, in the rectangular survey system."),
],
"national/disclosures": [
  ("Asbestos", "A fibrous mineral hazardous when friable; often best encapsulated rather than removed."),
  ("Underground storage tank", "A buried tank whose leakage can contaminate soil and groundwater."),
  ("Mould", "Fungal growth from moisture intrusion; a disclosable condition where known."),
],
"national/landuse": [
  ("Taxation", "The government power to levy against property to fund public services; one of the four in PETE."),
  ("Master plan", "The long-range policy document that zoning ordinances implement."),
],
"national/practice": [
  ("Discriminatory advertising", "Advertising that describes the desired occupant rather than the property."),
  ("Subagency", "An arrangement where a cooperating broker works through the listing broker and owes duties to the seller."),
],
"georgia/contracts": [
  ("Financing contingency", "A term letting the buyer terminate if the stated loan cannot be obtained."),
  ("Appraisal contingency", "A term protecting the buyer if the property appraises below the contract price."),
  ("Sale-of-property contingency", "A term making the purchase conditional on the buyer selling an existing home."),
  ("Automatic renewal", "A clause rolling an agreement forward by default; prohibited in Georgia listings."),
],
"georgia/license-law": [
  ("Experience requirement", "For a Georgia broker or associate broker, an active licence for three of the five years preceding application."),
  ("Prelicense course", "The 75-hour GREC-approved course required before a salesperson may be licensed."),
  ("Wall certificate", "The licence document issued to a firm, surrendered to GREC on suspension."),
],
"georgia/procedures": [
  ("Deed to secure debt", "Another name for Georgia's security deed, conveying title to the lender until payoff."),
  ("Advertisement", "Publication of a foreclosure in the county legal organ, customarily for four weeks."),
],
"comp/closing-math": [
  ("Loan payoff", "The balance required to discharge the seller's existing loan; a seller debit."),
  ("Settlement statement", "The itemised accounting of debits and credits for each party at closing."),
  ("Origination fee", "The lender's charge for making the loan, calculated as a percentage of the loan."),
  ("Commission", "The brokerage fee, a percentage of the sale price and normally a seller debit at closing."),
],
"georgia/disclosures": [
  ("Material defect", "A known physical condition affecting the property's value, safety or use, which must be disclosed."),
  ("Latent defect", "A hidden defect a buyer could not find on ordinary inspection; disclosable where known."),
  ("Patent defect", "A defect obvious on reasonable inspection."),
  ("Seller's property disclosure", "The written statement of known conditions, completed by the seller from personal knowledge."),
  ("Caveat emptor", "'Let the buyer beware' - the old rule, largely displaced by disclosure duties."),
  ("As-is sale", "A sale without seller repairs; it does not remove the duty to disclose known defects."),
  ("Flood plain", "Land subject to flooding, affecting value, insurability and lender requirements."),
  ("Lead-based paint disclosure", "The federal disclosure, records, pamphlet and 10-day test window required for pre-1978 housing."),
  ("Psychological impact", "A stigma arising from events rather than condition; generally not disclosable in Georgia."),
],
"comp/grec-deep": [
  ("Reprimand", "The mildest GREC sanction, a formal censure without loss of licence."),
  ("Suspension", "A temporary withdrawal of licensed authority imposed by GREC."),
  ("Revocation", "Permanent loss of a licence."),
  ("Own motion", "GREC's power to begin an investigation without any complaint being filed."),
  ("Certified licence history", "The official record of licensure from another state, required to prove out-of-state experience."),
  ("Signatory power", "The broker's required authority to sign on a trust account."),
  ("Employer Identification Number", "The tax identifier under which trust accounts should be opened, rather than a Social Security Number."),
  ("Pass-through coverage", "FDIC treatment of each client in a trust account as a separate insured owner."),
  ("Sanction", "Any penalty GREC imposes: reprimand, fine, education, suspension or revocation."),
],
"comp/situational": [
  ("Conflict of interest", "A personal or financial stake that could compromise your duty to a client."),
  ("Ministerial act", "A clerical, non-discretionary service a broker may perform for a customer."),
  ("Interpleader", "A court action letting a stakeholder deposit disputed funds for the court to allocate."),
  ("Referral fee", "Payment for sending business; barred for settlement services under RESPA Section 8."),
  ("Mortgage fraud", "Misrepresenting the terms of a transaction to a lender, such as concealed cash back."),
  ("Withdrawal", "Ending a brokerage engagement, the required response to a client's unlawful instruction."),
  ("Errors and omissions insurance", "Professional liability cover for a licensee's mistakes."),
  ("Fraudulent concealment", "Actively hiding a known material defect."),
],
"comp/vocabulary": [
  ("Estate for years", "A leasehold with fixed start and end dates, ending without notice."),
  ("Periodic tenancy", "A leasehold that renews automatically until notice is given."),
  ("Tenancy at will", "A leasehold endable at either party's pleasure."),
  ("Latent defect", "A defect hidden from ordinary inspection."),
  ("Patent defect", "A defect obvious on reasonable inspection."),
],
}
